### ISSUE TITLE
SIGILL on OS X when a background process (filetype) exits

### ISSUE THREAD

**Issue by cfillion** [vifm/vifm#101]
Hi,

On OS X (10.10), vifm from the master branch randomly crashes when a background process exits.
It doesn't happen before commit 8481b2a7b431fb44324db9820e8bae988706db48.

**Steps to reproduce**

1. Configure vifm:
  
  ```
  filetype *.mp4 echo &
  ```

2. Open a mp4 file
3. Repeat step 2 until vifm crashes (it usually requires less than 10 tries to make it crash):

  ```
Program received signal SIGILL, Illegal instruction.

(gdb) bt
#0  0x00007fff94286caf in _os_lock_corruption_abort () from /usr/lib/system/libsystem_platform.dylib
#1  0x00007fff9428586b in _OSSpinLockLockSlow () from /usr/lib/system/libsystem_platform.dylib
#2  0x00007fff8fb6f6e9 in pthread_mutex_destroy () from /usr/lib/system/libsystem_pthread.dylib
#3  0x0000000100039336 in job_free (job=<optimized out>) at background.c:271
#4  check_background_jobs () at background.c:188
#5  0x0000000100047c61 in event_loop (quit=0x1000786ec <main.quit>) at event_loop.c:109
#6  0x00000001000673df in main (argc=<optimized out>, argv=<optimized out>) at vifm.c:274
```

**Comment by xaizek** [comment]
Hello,

That commit was fine, the actual cause is [this accidental change](https://github.com/vifm/vifm/commit/87eec15e6e95e2f8ae2146ed2776b85959b8948d#diff-83f8b459230c0d0acd2ad2186ccc1b03R267) of 87eec15e6e95e2f8ae2146ed277.

Thank you for a great report! Which is also just in time, I was about to publish 0.8, will do some more testing.
