### ISSUE TITLE
Multiple fileviewer commands?

### ISSUE THREAD

**Issue by mb720** [vifm/vifm#1011]
Hi and thanks again for Vifm!

Is there a way to have alternative `fileviewer` commands that users can switch between?

For example, sometimes I'd like to preview PDF content using `pdftohtml` and sometimes I'd like to see the PDF's metadata with `exiftool`.

It would be nice to be able to define multiple `fileviewer` commands for the same file type and activate the next command with a mapping:

    fileviewer *.pdf bash -c 'pdftohtml -i -stdout %c | w3m -T text/html'
    fileviewer *.pdf exiftool %c
    " I know this command doesn't exist
    nnoremap fn :nextfileviewer<cr>

Is there currently a way in Vifm to achieve something like this?

**Comment by xaizek** [comment]
Hi!

Multiple previewers are allowed and there are several keys in view mode for switching between them: [a](https://vifm.info/vimdoc.shtml#vifm-q_a), [A](https://vifm.info/vimdoc.shtml#vifm-q_A), [i](https://vifm.info/vimdoc.shtml#vifm-q_i).

Picking preview outside of view mode requires switching back and forth in a mapping, see https://github.com/vifm/vifm/issues/794#issuecomment-1123384165.

This issue is related to https://github.com/vifm/vifm/issues/330.

**Comment by mb720** [comment]
Thanks!

This works nicely for me:

    fileviewer *.pdf exiftool %c,
                   " -i makes pdftohtml ignore images
                   " w3m renders the HTML
                   \ bash -c 'pdftohtml -i -stdout %c | w3m -T text/html'

**Comment by xaizek** [comment]
`bash -c` shouldn't be necessary, viewer commands are executed via a shell.

**Comment by mb720** [comment]
Much appreciated! 👍

The command can be reduced to:

    fileviewer *.pdf exiftool %c,
                   " -i makes pdftohtml ignore images
                   " w3m renders the HTML
                   \ pdftohtml -i -stdout %c | w3m -T text/html
