### ISSUE TITLE
:copy! command undoes hard links

### ISSUE THREAD

**Issue by bionota** [vifm/vifm#1044]
I have got some GitLab & GitHub repos stored locally and  we keep them synchronised with hard links. However, when copying an updated (original) file to any file path that has got hard links undoes it, meaning the hard links are not kept because somehow the copied file gets a new inode in such case, I reckon.

When I do the same operations with external command `copy -f` it does not undo the hard links. I would expect the same from the vifm built-in command.

I was unfortunate in finding a "correct syntax" through `man vifm` for this feature, but if there is a correct way of doing this, I'd much appreciate learning it!

**Comment by xaizek** [comment]
There is no way to achieve that effect.  Vifm doesn't truncate the target file, but removes it before making a copy.  This is probably something that could be configured via ['iooptions'](https://vifm.info/vimdoc.shtml#vifm-%27iooptions%27) at least when dealing with files.  I don't think this was done intentional to not update hardlinked files, but rather to handle existing destination the same way regardless of whether it's a file, directory or a special file.

**Comment by bionota** [comment]
Thanks @xaizek for the express reply! That is really understandable how vifm built-ins work, and it is easy for me to have a custom command that executes the external `copy` command!

I will check 'iooptions', thanks for the tip!

So I will just close this GitHub issue, as this is non-issue.
