### ISSUE TITLE
The command :shell's behavior is diffrient from vim's.

### ISSUE THREAD

**Issue by loongw** [vifm/vifm#127]
Suppose we have env:
```
$SHELL=/bin/sh
cfg.shell=/bin/bash\ -l
```
Now type :shell will execve the final command line like this:
```/bin/bash -l -c /bin/sh```
So, we'll got no effect on :shell when modifying cfg.shell value.

I have created a pull request for this issue.

**Comment by xaizek** [comment]
This was the intend, although it wasn't documented until recently: 33558b5a1e0d74. The idea is to use the shell that was used to run vifm on `:shell`, but use `'shell'` in all other cases (for things like `:fileviewer`, `:file[x]type`, `:!command`, `:grep`, ...). Say, if you don't want to use login shell for `:!`, you could set:
```vim
let $SHELL = '/bin/bash -l'
set shell=/bin/bash
```
It might be unexpected and not so easy to notice, but seems to allow better flexibility than having just `'shell'`. It was introduced years ago on a request so that one could use one shell as an interactive one, but another shell for scripting.

**Comment by loongw** [comment]
Got it. Thanks.
