### ISSUE TITLE
%f = %c ("The current file under the cursor.") instead of "All of the selected files." in :!

### ISSUE THREAD

**Issue by aleksejrs** [vifm/vifm#132]
It does "All of the selected files." in "command!" lines in vifmrc.

It is so in 0.8, and I think it was so in 0.7.8.

**Comment by aleksejrs** [comment]
Testcase:
```
:mkdir to
:touch a b c
fat
fc
!cp %f to/
```

**Comment by xaizek** [comment]
Can't reproduce this with 0.7.8, 0.8 or current version, could you try reproducing it in `vifm --no-configs` to make sure it's not something in configuration file? You might want to quit that session with `:q!` afterwards to do not loose contents of `vifminfo` file.

**Comment by aleksejrs** [comment]
Reproduced (0.8).

**Comment by xaizek** [comment]
Still no luck. Also tried on Debian in VM with 0.7.8 from repository and 0.8 build from sources, it's always file `a` that is copied. After <kbd>fat</kbd> is pressed when it says `1 file selected` I don't see what could change state of internal structures so that wrong file is used. It appears as if selection is reset right before `:!` command is executed, but I don't see why would it be reset. I'll check it again later, maybe I'm missing something.

**Comment by aleksejrs** [comment]
Reproduced with 0.7.8 from Debian.

**Comment by xaizek** [comment]
Then we must be doing something differently. Here's how I do it:
* Navigating to empty directory.
* Copying this and inserting it via <kbd>Shift-Insert</kbd> into terminal:
```
:mkdir to
:touch a b c
fatfc:!cp %f to/
:!ls to %m
```
* Now there is `a` in the menu.

**Comment by aleksejrs** [comment]
Indeed, your version works.
In my case, I entered "!!" (which gives ":.!") and not ":!".

```
:mkdir to
:touch a b c
fat
fc
!!cp %f to/
!!ls to %m
```

**Comment by aleksejrs** [comment]
The above testcase gives "c".

**Comment by xaizek** [comment]
Well, the meaning of `.` range is exactly "current file", and as command range naturally has precedence over selection in a view (range itself defines new selection) that's what `%f` expands to. So it's not an issue (except maybe documentation could be improved), you need to type `:!` instead of `!!`, the latter one is a shortcut for composing ranges for `:commands` (`!j`, `!4k`, `!G`, etc.).

**Comment by aleksejrs** [comment]
I guess I confused "!!" with ":!!  same as :!, but pauses before returning."

**Comment by aleksejrs** [comment]
Why do commands beginning with “`:.!`” not add the file name automatically?

**Comment by xaizek** [comment]
> Why do commands beginning with “:.!” not add the file name automatically?

Because it can lead to unexpected results.  Different commands accept files in different position and only user can know for sure where to put file name argument.  `:file[x]type` has this implicit file name, but it's partly historically and generally reasonable as `:file[x]type` command is meant to be used to open a file. While on command-line one can execute arbitrary commands. I'm not sure if it's safe to assume that if range is specified, list of files is expected to be added implicitly (you mention `:.!`, but it's not really different from `:5,$!`, `:'a,+10!`, etc.).
