### ISSUE TITLE
Idea: add directory comparison features (or describe how to add them)

### ISSUE THREAD

**Issue by aleksejrs** [vifm/vifm#134]
The wiki proposes a script which seems to be supposed to just say, binarily, if the two objects differ or not.

mc has a tool to compare directories to various levels of detail (Quick, Size only, Thorough), whose output is selection of the differing files in the directory.

This script: https://github.com/capncodewash/Misc-shell-scripts/blob/master/find_missing_files.sh (not perfect, see issues) uses checksums to list names of files which (_by contents_) are found in one ("source") but not the other ("dest") of two directories.  Such a list could be put into a custom view instead of the "source" directory.

**Comment by xaizek** [comment]
Such feature was mentioned some time ago, but I still don't have a good idea of how it should operate and look like. `mc` seems to highlight files that are missing from each pane, if that's all, it shouldn't be hard to add (I wanted to compare directories only several times and not sure what form of comparison results would be useful).

**Comment by aleksejrs** [comment]
1. Find files common to two directories (even if with different names):
2. Generate a table, show duplicate files in one directory on one pane, and their duplicates in the other directory on the other pane (both are custom views, with paths). Pay attention to sorting.
3. When a file is deleted, hide its duplicate on the other side.

**Comment by xaizek** [comment]
I think I finally know how to implement this in a way that would satisfy my requirements. You described finding duplicates, which is just part of the task, so I was looking for a way to get full featured diffing, which would be better than in mc, because I don't like the way it works there:
 * It can't find duplicates in the same directory.
 * It doesn't show multiple copies of the same file on one side in any way.
 * It doesn't differentiate between missing/added files like diffs usually do.

But it will need some experimenting and time to do, so here's an example of how comparison can be done with the above script (you probably did this already in a different way, but anyway):

* Modified version of that script is [here](https://gist.github.com/xaizek/eaf79a2d36bd1f34a3822e18bc3a6472), which includes your additions and seen some rewrite. It might need some testing, but seems to work.
* Put it under `~/.vifm/scripts` and make it executable.
* Add the following to `vifmrc`:
```vim
command! comparedirs
\ :execute '!find-missing-files %%d %%D %%n'
\ |execute '![ -s a-only.lst ] && cat a-only.lst || echo . %%U'
\ |winrun , execute '![ -s %%D/b-only.lst ] && cat %%D/b-only.lst || echo . %%U'
\ |!rm a-only.lst b-only.lst %i
```
If file is empty, current directory will appear in custom view, which seems to be better than error about empty custom view.

**Comment by aleksejrs** [comment]
It doesn't seem to work with the Vifm build I am using (a little post-0.8.1, IIRC).

**Comment by xaizek** [comment]
> It doesn't seem to work with the Vifm build I am using (a little post-0.8.1, IIRC).

What does `vifm --version | head -2` say? I tried it with 0.8.1 and 0.8.1a versions, both work, 0.8.1 with config containing nothing but the command above also works.

> I'd give the output files more complex names to avoid overwriting something.

Makes sense, added a prefix.

**Comment by aleksejrs** [comment]
Oh, sorry, I was trying to use it like the script itself.  The command actually works.

**Comment by xaizek** [comment]
Finally, initial version is available. There might be some changes later, but the main idea will remain. I suggest reading [documentation](https://github.com/vifm/vifm/blob/0c2ef038871a3a860881dc79b4f9c84d13f5768a/data/vim/doc/app/vifm-app.txt#L4195) for details about current implementation. Below are some screenshots to demonstrate what it's capable of  and to help to get started with using it (these are probably the most popular use cases). Numbers in the second column are file ids, files that are considered identical have the same id.

Note that there might be some bugs in this new code.

#### Comparison of directories with mismatches (`:compare`)
![diff](https://cloud.githubusercontent.com/assets/459736/18131287/e8f6185c-6f9a-11e6-80f7-9b4fbbd9b8dd.png)

#### Finding duplicates within one file system tree (`:compare listdups ofone`)
![dups](https://cloud.githubusercontent.com/assets/459736/18131278/e141f68a-6f9a-11e6-99ff-ecb9d18c59f9.png)

#### Finding unique files in both panes (`:compare listunique byname`)
![unique](https://cloud.githubusercontent.com/assets/459736/18131263/d04b6f82-6f9a-11e6-91e4-dc5849f31466.png)

**Comment by aleksejrs** [comment]
> - exiting one of the views terminates the other immediately;

Maybe that shouldn't happen when finding unique files, so that it is possible to copy the files.

**Comment by xaizek** [comment]
> Maybe that shouldn't happen when finding unique files, so that it is possible to copy the files.

It doesn't happen in that case, because those are regular custom views. Two views are exited simultaneously only when their cursors and list of files are bound to each other, which isn't true for lists of unique files.
