### ISSUE TITLE
Installation fails when configure looks for libncursesw on Linux Mint

### ISSUE THREAD

**Issue by CptMoroni** [vifm/vifm#137]
Hello,
I recently switched to linux mint, which has vifm available, but only version 0.4.  So I am trying to install from the tar file.  When I run the configure script it fails when it searches for libncursesw.  I tried installing the libncurses-dev to see if that helped.  Whe I do that I have the following libncursesw files:
/lib/i386-linux-gnu/libncursesw.so.5
/lib/i386-linux-gnu/libncursesw.so.5.9
/lib/x86_64-linux-gnu/libncursesw.so.5
/lib/x86_64-linux-gnu/libncursesw.so.5.9

My system is 64 bit, I installed linux mint 17.2 and beyond that I really have no idea what else you might want to know.  Thanks for any help!

**Comment by r44083** [comment]
I think that you need first uninstall the old version of vifm, and install the missing packages.
Use make install to install packages on a working system do not need because you will have big problems with the removal of this package. You need to create your own deb package:
./configure
make
sudo checkinstall

I also use Linux Mint and I already create deb package with vifm 0.8 (package in the attachment to this message)
[vifm_0.8-1_i386.zip](https://github.com/vifm/vifm/files/76165/vifm_0.8-1_i386.zip)

**Comment by xaizek** [comment]
Hi,
the package you need is named `libncursesw5-dev` on Debian-based systems. From list of files it seems that you installed something like it, but paths look strange (maybe it's not the full list though). So make sure it's the right one, and consider comment above regarding installation.
If it still won't work, post `config.log` file here, it contains details of the failed check performed by `configure`.

**Comment by CptMoroni** [comment]
Thank you!  libncursesw5-dev appears to be the missing package.  I was able to configure and make the package.  

I have never created a package before so I didn't realize that checkinstall would create AND install the package at the same time, so I had not yet followed the instruction to uninstall the old version (0.4) of vifm that was in the mint channels.  Is the main advantage of creating the package that it is easier to update?  I listed libncursesw5-dev as a dependency but did not know what else to list, should I have listed anything else or made any other changes?

Except for vifmrc-converter failing on the install vifm (now 0.7.7) seems to be running OK.  Should I do anything to fix the error?  Since the system is new, there was really nothing to convert from vifm 0.4, I planned on moving in files from another system (with vifm 0.7.7) I had anyway.  But maybe converter does more than simply convert the old files to new ones.

Thanks again for your help!

**Comment by xaizek** [comment]
> Is the main advantage of creating the package that it is easier to update?

In most cases, as you won't need to remove installed files yourself (`make uninstall` will also do, but you need to keep build directory around for that).

> I listed libncursesw5-dev as a dependency

This is actually build dependency, binary package should need only `libncursesw5` (no `-dev`).

> should I have listed anything else or made any other changes?

I guess it's not very important unless you're planning to use the package somewhere outside your system (not sure due to lack experience with Debian-based distributions).

> Except for vifmrc-converter failing on the install

That's strange, what's the error? It's not very crucial (and the converted is removed in 0.8.1), but I don't remember such error. It does convert files only once.

> vifm (now 0.7.7)

Why this particular version and not 0.8?

**Comment by CptMoroni** [comment]
So, after a reboot the vifm-converter script ran again (I am not sure why) and this time it succeeded.  

I thought I had grabbed the latest stable release, I am not sure what my search keywords were, but now when I go to the sourceforge page version 0.8 shows up as the latest version.  You mention 0.8.1, should I be using that?  If I create the .deb file again, will it just update the old version or do I need to uninstall it first then install the new version?

Thanks

**Comment by xaizek** [comment]
> You mention 0.8.1, should I be using that?

It's in beta, so maybe wait until its released (about two weeks).

> If I create the .deb file again, will it just update the old version or do I need to uninstall it first then install the new version?

I think if `checkinstall` will use the same name for the package, the old one will be upgraded, so you won't need to do anything additional.

**Comment by CptMoroni** [comment]
Thank you.  I just had a chance to upgrade.  It looks like you were correct, at least version 0.8 comes up when I run vifm.
