### ISSUE TITLE
Allow registering mimetypes

### ISSUE THREAD

**Issue by rosshadden** [vifm/vifm#150]
It would be great if you could associate programs with mime types.  Consider the following examples:

```
mimetype text/plain vim
mimetype inode/directory
    \ {SpaceFM}
        \ spacefm %f %i &
mimetype text/* vim
```

The last one, with the wildcard, would mean that `vim` could be used for _every_ file that unix considers to be text.  That is extremely powerful, and much easier on users than listing out every text-ish extension they can think of, which doesn't bode well for dotfiles.

This may be accomplished by using the `file` command.  That is:  `file --mime-type <somefile or list of files>`.

**Comment by xaizek** [comment]
> mimetype text/* vim

I would use existing commands (with new syntax to specify mimetype) so that there is no need for conflict resolution between `:file[x]type` and `:mimetype` and to reuse all that's already there for `:filetype`.

> This may be accomplished by using the file command.

It's already used if `libmagic` is not available and GTK+ isn't enabled (it's used for its database, which is sometimes more accurate).

**Comment by rosshadden** [comment]
Makes sense.  There is certainly a lot of code for `filetype` and it seems like a good idea to reuse it.

**Comment by xaizek** [comment]
The syntax is like this:
```vim
filetype <text/plain> vim
filetype <inode/directory>
    \ {SpaceFM}
        \ spacefm %f %i &
filetype <text/*> vim
```

`<...>` is just a list of comma separated globs applied to mime type.
