### ISSUE TITLE
Path regular expressions do not support ~ for $HOME

### ISSUE THREAD

**Issue by aleksejrs** [vifm/vifm#159]
`~` or `\~` do not work in filetype patterns.

Haven't tested with other pattern formats.

**Comment by xaizek** [comment]
They shouldn't, there are no expansions for regular expressions. It won't work as expected.

**Comment by aleksejrs** [comment]
OK.

**Comment by xaizek** [comment]
I should clarify that they could work in simple cases like `//~/(foo|bar)//`, but anything more sophisticated (e.g. `//^(~|/tmp)//`) won't and can produce strange results. Maybe even `//~/(foo|bar)//` shouldn't work because it means `//.*~/(foo|bar).*//`, so only something like `//^~...//` would make sense.
