### ISSUE TITLE
Feature suggestion: handling of file permissions

### ISSUE THREAD

**Issue by fogine** [vifm/vifm#161]
For example, if I want to perform action (write, delete) on file which I'm not owner of, I get message "Current directory is not writable". This could be handled by showing password input field.
Does the feature make sense?

**Comment by xaizek** [comment]
I would call this very questionable because it would require vifm executable to be marked with suid bit, which is very odd and insecure for a file manager. Spawning separate process using `su` or `sudo` could be an option, but it would probably require `sudo` to do not drive user crazy and it's not always configured; there is no easy way to do the same with system calls implementation, so one won't be able to see operation progress. It's better to run separate instance with more privileges, do it and quit (e.g. do `:!sudo vifm %b`).

**Comment by fogine** [comment]
I  understand now the issue and issues related. It will be better to not implement this kind of things. Thank you.
