### ISSUE TITLE
Suggestion: suggest to use github wiki for 'tutorial/tips'

### ISSUE THREAD

**Issue by ipstone** [vifm/vifm#163]
Hello, nice work on vifm!

As a new user of vifm, I have trouble finding info on the official wiki site. For example, how to select files, - I can not locate the info there easily. I would suggest using the github wiki for some tips/info, which can be accessed quicker for end users.

Thanks again for the great work!

**Comment by xaizek** [comment]
Hi, great to hear you find it useful.

> I would suggest using the github wiki for some tips/info, which can be accessed quicker for end users.

Changed message about obsolete wiki a bit.  I certainly have nothing against using this wiki if you find it more convenient. Feel free to edit it, maybe it will help with #110 (I'm having trouble figuring out what might be useful for new users because I'm too familiar with controls and settings).
