### ISSUE TITLE
Devicons support

### ISSUE THREAD

**Issue by elricbk** [vifm/vifm#164]
[vim-devicons](https://github.com/ryanoasis/vim-devicons) is a Vim plugin which allows to add icons to filenames (based on filetype) in the variety of other plugins. Plugin uses patched fonts to achieve this. Using same fonts we can get more gui-like view:

![2016-02-21 10 27 58](https://cloud.githubusercontent.com/assets/4334930/13201526/d7a81a48-d885-11e5-957d-8b3cfa95d672.png)

I was unable to achieve this with `classify`, so I had to monkey-patch `format_entry_name` function

**Comment by xaizek** [comment]
Hm, that looks nice! I think it makes sense to extend `'classify'` to accept patterns like `:highlight` does. Thanks for the suggestion.

**Comment by elricbk** [comment]
There were multiple problems with `classify`, not only inability to match by the file extension/name:
* Need for the "default" icon (blank file). Could be solved by `*` as pattern maybe?
* Only one symbol is allowed. On the screenshot above two are used – actual icon and space.
* Quick test for unicode symbol in `classify` was a failure. I've tried random glyph from sample font. Same symbol in `format_entry_name` worked just OK.

So, if you are planning to add some syntax to overcome all of the limitations, that's really great. Thanks in advance.

**Comment by xaizek** [comment]
> Need for the "default" icon (blank file). Could be solved by * as pattern maybe?

If there can be at most one match, all that is needed is checking for file name match and then for type match in this order (so type entries will provide generic defaults).  `*` would work too and would shorten the value (no need to enumerate every type).

> Only one symbol is allowed. On the screenshot above two are used – actual icon and space.

Can be changed to strings instead of characters, with some restrictions (like no `:` in prefix/suffix).

> Quick test for unicode symbol in classify was a failure. I've tried random glyph from sample font. Same symbol in format_entry_name worked just OK.

Well, user can provide additional space when needed I guess.  Alternatively, icons could be mapped somewhere in CJK range of characters, although I don't know how correct this would be.  The point is to avoid any special treatment when it's possible.

**Comment by elricbk** [comment]
> Well, user can provide additional space when needed I guess.

Problem was not with space – for now `vifm` disallows using glyphs (multibyte chars?) as prefixes. I believe this will be fixed automatically when `classify` allows using strings instead of single char.

**Comment by xaizek** [comment]
> Problem was not with space – for now vifm disallows using glyphs (multibyte chars?) as prefixes. I believe this will be fixed automatically when classify allows using strings instead of single char.

You're probably right about multibyte chars, that's because of utf8 encoding as glyphs should have values `> 127`. I thought that `wcwidth()` returns wrong width of a glyph (`1` instead of `2`).

**Comment by xaizek** [comment]
Posting example along with configuration, because syntax isn't very easy to grasp and finding icons in those fonts is not straightforward either.

Results of my tests (not all icons are easy to see, others are fine):
![classify](https://cloud.githubusercontent.com/assets/459736/13959072/379a9efc-f05b-11e5-9f3e-f2f3ad25f788.png)
Corresponding configuration (mind that [nerd-fonts](https://github.com/ryanoasis/nerd-fonts) reports some of the characters under different codes and FontForge warns about wrong symbol names, so some of these might be wrong for their other fonts (off by some value, I guess), I used DejaVu Sans Mono):
```
" file types
set classify=' :dir:/, :exe:, :reg:, :link:'
" various file names
set classify+=' ::..::, ::*.sh::, ::*.[hc]pp::, ::*.[hc]::, ::/^copying|license$/::, ::.git,,*.git::, ::*.epub,,*.fb2,,*.djvu::, ::*.pdf::, ::*.htm,,*.html,,**.[sx]html,,*.xml::'
" archives
set classify+=' ::*.7z,,*.ace,,*.arj,,*.bz2,,*.cpio,,*.deb,,*.dz,,*.gz,,*.jar,,*.lzh,,*.lzma,,*.rar,,*.rpm,,*.rz,,*.tar,,*.taz,,*.tb2,,*.tbz,,*.tbz2,,*.tgz,,*.tlz,,*.trz,,*.txz,,*.tz,,*.tz2,,*.xz,,*.z,,*.zip,,*.zoo::'
" images
set classify+=' ::*.bmp,,*.gif,,*.jpeg,,*.jpg,,*.ico,,*.png,,*.ppm,,*.svg,,*.svgz,,*.tga,,*.tif,,*.tiff,,*.xbm,,*.xcf,,*.xpm,,*.xspf,,*.xwd::'
" office files
set classify+=' ::*.doc,,*.docx::, ::*.xls,,*.xls[mx]::, ::*.pptx,,*.ppt::'
```

**Comment by elricbk** [comment]
Thanks a lot!

Couple of questions about configuration:
* why some of the symbols are duplicated from time to time? I.e. sometimes there is single colon, sometimes there are two of them. Same for comma.
* what about "default" case for non-special file type? Should it be handled with asterisk?

**Comment by xaizek** [comment]
> why some of the symbols are duplicated from time to time? I.e. sometimes there is single colon, sometimes there are two of them. Same for comma.

There are [two kinds of patterns](https://github.com/vifm/vifm/blob/70a01af7f559e59083d296fdf701827fbacb09a8/data/vim/doc/app/vifm-app.txt#L2583-L2584) now and there must be a reliable way to differentiate between them. Patterns already use `[]{}/*+` characters, so I doubled colon. Alternatively we could require explicit `{}` or `//` around patterns (`:{..}:` instead of `::..::`).

Commas are used to separate values, so they need some kind of escaping when used for different purpose. They are escaped the same way for `:file[x]type` and `:fileviewer` commands. Here not many alternatives, but with mandatory `{}` and `//` it should be possible to get rid of doubling (actually, I just realized this). Current syntax is similar to those two commands, but maybe it's not worth it.

> what about "default" case for non-special file type? Should it be handled with asterisk?

It can be, as `*` matches all files not matched by anything else. According to [priorities](https://github.com/vifm/vifm/blob/70a01af7f559e59083d296fdf701827fbacb09a8/data/vim/doc/app/vifm-app.txt#L2587-L2590) `*` should go _after_ other patterns.

**Comment by elricbk** [comment]
Thanks for the thorough explanation. And thanks again for the whole devicons support.
