### ISSUE TITLE
Entering a selected directory when both files and directories are selected causes a warning, but not when only directories are selected.

### ISSUE THREAD

**Issue by aleksejrs** [vifm/vifm#177]
1. Select both files and directories.
2. Enter a selected directory.

An error message appears: `Selection error. Selection cannot contain files and directories at the same time. Press Return to continue.`  Pressing Return removes the selection.

No error message appears when entering an unselected directory, or when only directories are selected

**Comment by xaizek** [comment]
It was implemented long time ago, but I don't see any wrong behaviour here. As far as I remember, it's meant to be this way.

> No error message appears when entering an unselected directory

Because selection is ignored then.

> or when only directories are selected

Because it makes some sense, while trying to open both files and directories won't lead to meaningful result. In this case vifm acts as handler of directories and as it can't open more than one, current one is opened.

**Comment by aleksejrs** [comment]
> In this case vifm acts as handler of directories and as it can't open more than one, current one is opened.

I see…  When only files of different types are selected, Vifm uses the lowest common denominator if it can, or says "`Run error. Handlers of selected files are incompatible.`".

**Comment by aleksejrs** [comment]
> Vifm uses the lowest common denominator

That's just a hopeful guess, because:

* PDF + .txt (no matter which one I press `l` on) only opens the PDF in Vim without conversion.
* .txt + .zip opens the .txt twice
* .htm + .txt shows the error message.

**Comment by xaizek** [comment]
It's more complicated than it seems.

* When associated programs use `%c`/`%C` macro (and don't include `%f`/`%F`) and are run in background (` &`) programs are launched individually for each file.
* When all files are handled by the same program which uses `%f` macro, it's invoked.
* If at least one file doesn't have any associated program, editor is spawned (assuming that it can at least try to open files of different types).
* Otherwise, it's a failure.

The checks aren't obvious, but the point was to allow running multiple files of known types or using editor otherwise with exceptional case when files are handled by different programs.

**Comment by xaizek** [comment]
I don't see anything to be done here (feel free to reopen, if I'm missing something), so closed the issue.
