### ISSUE TITLE
Support for 256 colors in preview pane

### ISSUE THREAD

**Issue by rr-** [vifm/vifm#181]
In light of #180 I wrote a stupid character based replacement available [here](https://github.com/rr-/dotfiles/blob/master/bin/asc):

![20160503_002255_svo](https://cloud.githubusercontent.com/assets/1045476/14969906/37079c80-10c5-11e6-98c5-8aed5143e662.png)

However, using it within vifm results in garbage:

![20160503_002334_cuj](https://cloud.githubusercontent.com/assets/1045476/14969920/5e670374-10c5-11e6-863c-1b16b5956ba5.png)

In the script, rather than consulting termcap, I just hardcode `\033[48;5;XXXm` and `\033[38;5;XXXm`; I'm not sure if it matters in this particular case. Terminal is urxvt, `TERM=rxvt-unicode-256color`. I'd expect the escape codes to be left uninterpreted and sent to urxvt so that it can render them.

If this is indeed problem with vifm rather than my script, it's worth considering adding support for [true color](https://gist.github.com/XVilka/8346728) along the way.

**Comment by xaizek** [comment]
> I just hardcode `\033[48;5;XXXm` and `\033[38;5;XXXm`

vifm understands these, but not true color (curses doesn't understand it, if I remember correctly).

> I'd expect the escape codes to be left uninterpreted and sent to urxvt so that it can render them.

ncurses doesn't allow this, escape codes must be translated into appropriate calls of curses API or you won't see anything (which makes sense as otherwise output will be a mess).

I remember [shellpic working](https://sourceforge.net/p/vifm/discussion/158927/thread/3a3237b2/) until they changed something (started to separate characters into top and bottom halves), some others also could work. The thing to keep in mind is that it's not a terminal emulator (embedding one doesn't sound like a good idea) so no fancy tricks or queries to terminal (like the one to determine its size) should be used.

By the way, I don't see anything in terminal if I do `python  asc show canvas3.png`, maybe it's because of python 2, but there are not errors.

**Comment by rr-** [comment]
Off topic, I extracted the script to a [separate project](https://github.com/rr-/termi). Thanks for showing me shellpic, it inspired me to split characters into two halves as well.

**Comment by rr-** [comment]
Personally I'm no longer interested in this function as I worked around the image support with [other scripts](https://github.com/rr-/dotfiles/blob/master/bin/img/thumbs). Would you like me to close the issue?

**Comment by xaizek** [comment]
> By the way, I don't see anything in terminal if I do python asc show canvas3.png, maybe it's because of python 2, but there are no errors.

This indeed was due to python2, because in python3 `/` operator changed its meaning.

And now I see what's wrong: limit on number of color pairs (combinations of foreground and background colors) is reached.  There are only 256 in 256-color terminal and after reaching 256 threshold, pairs start getting reused.

The situation is:
 * we can't emulate terminal behaviour in curses due to limitation on color pairs (we could find closest pair or do something similar, but that seems to be out of scope for just displaying the thing)
 * we can't draw anything unbeknown to curses because it will break the interface (that is even if it's possible, doesn't draw simple text correctly for me, probably because curses changes state of terminal)

So the resolution is "can't fix".
