### ISSUE TITLE
Named pipe on cygwin

### ISSUE THREAD

**Issue by cosminadrianpopescu** [vifm/vifm#189]
The new IPC uses named pipes, which unfortunately do not work in cygwin. Do you have any idea on a workaround in cygwin? If you have any suggestions, maybe I can have a look at it. My main problem is that I only have cygwin at work, not at home (no Window in my house).

**Comment by xaizek** [comment]
Are you sure it shouldn't work in cygwin at all? I tried and I see the pipe and it seems to be opened once, but any successive `open()` calls fail. It might be that cygwin implementation doesn't pass needed flags.
If you run `vifm` and `vifm --server-list` works once, then it "almost works".

[This page](https://cygwin.com/cygwin-ug-net/programming.html) says:
> The 64 bit Cygwin toolchain uses the Microsoft x64 calling convention by default, so you can create applications using the Win32 API just as with the 32 bit Cygwin toolchain.

So I guess there should be a way to call `CreateNamedPipeA()` in cygwin and make `FILE *` out of its result as is done for MinGW (but functions/constants might be different, looks like there is no `_open_osfhandle()` defined).

**Comment by cosminadrianpopescu** [comment]
See [this](http://stackoverflow.com/questions/31655400/cygwin-using-named-pipes-seems-difficult). If you follow the link on the cygwin page, I've followed the test and I cannot connect to an open pipe. 

It's true that the pipe is opened and it can be seen, but we cannot write anything in it, so it's pretty much useless.

But maybe we can have a different implementation on cygwin, using (just an idea) a TCP communication, or something different. I am thinking that I could develop something like this at home using an `#ifdef` and then changing it to `cygwin` to test it at work. 

Please let me know what other ideas you would have. I am willing to implement it, since right now I cannot update my `vifm` installation because I am relying heavily on the remote feature.

**Comment by xaizek** [comment]
I really hoped they have `_open_osfhandle()` analog, but they don't (which is weird). This missing bit prevents us from using `FILE` on all platforms for consistency. On the other hand `ReadFile`/`WriteFile` work like `fread()`/`fwrite()`, so since we can switch to use them, everything else should work as is.

Previous version used UDP, TCP has the same issues and not everything present in current version will work with it. Using WinAPI seems to be saner way, cygwin stands in the way in this particular case.

I can switch the code to use Win32 API for read end of pipe on Cygwin and Windows, as it probably won't be convenient for you to test updated code for Cygwin+WinAPI.

**Comment by cosminadrianpopescu** [comment]
k. Let me know when I can test it. Indeed, using Win32 API I cannot work from home.

Thank you.

**Comment by xaizek** [comment]
See [fix-ipc-on-cygwin](https://github.com/vifm/vifm/tree/fix-ipc-on-cygwin) branch, everything seems to work there. As a side effect cygwin and native instances of vifm can now communicate, but it doesn't seem to be a problem and might even be useful.

**Comment by cosminadrianpopescu** [comment]
Works perfectly. Thank you. I am now on the latest version of vifm.

**Comment by xaizek** [comment]
Great, thanks for reporting and testing.
