### ISSUE TITLE
--remote --select disables preview

### ISSUE THREAD

**Issue by rr-** [vifm/vifm#215]
Reproduction steps:

1. Open preview with `w`
2. Have someone `--remote --select` another file
3. Preview is turned off

IMO it shouldn't happen.

**Comment by xaizek** [comment]
This was done in b38604cad, but I can't remember why. I guess the issue was that you couldn't see just selected file if preview is displayed in place of that pane. If that's the reason, it makes sense to disable preview only if it actually hides selected file, while the current code disables it always.

**Comment by xaizek** [comment]
Wrong commit, this particular change was done a bit later in b6aa6a978. None of the commits explain the reason, so I changed the behaviour for the case when `--select` is passed to reset preview only if it hides target file.
