### ISSUE TITLE
:filter triggers sorting method?

### ISSUE THREAD

**Issue by sudo-nice** [vifm/vifm#235]
Please, consider this minimal vifmrc:
```
:only
set sort=+iname
filter /^.*\.files\/$/
```
So, run vifm and enter the test directory:
![1](http://i.imgur.com/Ak7bYol.png)
Nothing unusual, as we can see. But if we run `:restart`, things change:
![2](http://i.imgur.com/UsexU3D.png)
And even strange thing happens if we check sorting method now `:set sort?`:
![3](http://i.imgur.com/cnDQJFZ.png)
Manual command `:set sort=+iname` has no effect, but running `:sort` and picking <kbd>N</kbd> actually applies `+iname`.
**This strange behavior doesn't happen if we delete `filter /^.*\.files\/$/` from vifmrc.**

Is this a bug or am I missing something? What is the right way to preserve `sort=+iname` on `:restart`?

I'm on Debian Stretch, vifm is installed from debian repos.
`vifm -v` shows:
```
Version: 0.8.2
Git info: built out of repository

Support of extended keys is on
Parsing of .desktop files is enabled
Without GTK+ library
With magic library
With X11 library
With dynamic loading of X11 library
With file program
With -n option for cp and mv
With remote command execution
```

**Comment by xaizek** [comment]
This is definitely a bug. Development version behaves somewhat better in that it doesn't lie about sorting (outputs `+iname` for `:setg`, but `+name` for `:setl`) and here nothing changes if you add/remove filter or any other command after `:set sort=+iname`, so the issue is more stable. Thank you for the report.
