### ISSUE TITLE
Chose program to open file with, instantly

### ISSUE THREAD

**Issue by sudo-nice** [vifm/vifm#238]
**First of all, my `vifmrc` has no filetype associations for `*.doc` files.**

Given:
![list](http://i.imgur.com/h5lyjvC.png)
`:file` shows:
![file](http://i.imgur.com/5JlSTqv.png)
So, if I stay on `test.doc` and press <kbd>l</kbd>, this file is opened with the editor (`set vicmd=editor`). But somehow vifm knows about libreoffice I actually have... Hm...

#### Method 1
1. Run `:file` or press the key mapped for this command (if I have any)
2. Move to the next line (<kbd>j</kbd>)
3. Run it (<kbd>Enter</kbd>)

#### Method 2
1. Enter `:file<space>` or press the mapped key (if I have any)
2. Hit <kbd>Tab</kbd> to complete `libreoffice` into command line
3. Run it (<kbd>Enter</kbd>)

### What could I do?
<kbd>1l</kbd> - which means: run the first line from `:file` menu (we presume the current line is 0).

Sure, I can add to `vifmrc` something like `filetype *.doc libreoffice`, but sometimes we really need several programs to deal our file with. E.g. images could be viewed with `sxiv`, edited with `gimp` and set as wallpaper with `feh`.

Sure, I can't know the number of line in `:file` beforehand and I'll have to learn it for some times. But then this feature will work without any need to think.

**Comment by xaizek** [comment]
> But somehow vifm knows about libreoffice I actually have... Hm...

It comes from parsing of `*.desktop`-files.

**Method 3** (you mentioned it)

Copy provided definition to `vifmrc` file. These entries are not considered by <kbd>l</kbd> because their order and contents depends is volatile (depends on installation and removal of applications).

**Method 4**

1. Enter `:f l`.
2. Run it (<kbd>Enter</kbd>).

Using numbers is too fragile I think. Something like this (long and quite ugly, I know) seems better:
```vim
noremap xa :f a<cr>
noremap xb :f b<cr>
noremap xc :f c<cr>
noremap xd :f d<cr>
noremap xe :f e<cr>
noremap xf :f f<cr>
noremap xg :f g<cr>
noremap xh :f h<cr>
noremap xi :f i<cr>
noremap xj :f j<cr>
noremap xk :f k<cr>
noremap xl :f l<cr>
noremap xm :f m<cr>
noremap xn :f n<cr>
noremap xo :f o<cr>
noremap xp :f p<cr>
noremap xq :f q<cr>
noremap xr :f r<cr>
noremap xs :f s<cr>
noremap xt :f t<cr>
noremap xu :f u<cr>
noremap xv :f v<cr>
noremap xw :f w<cr>
noremap xx :f x<cr>
noremap xy :f y<cr>
noremap xz :f z<cr>
```
This way you can run <kbd>xl</kbd> to run something that starts with `"l"`, <kbd>xs</kbd> for something that starts with `"s"`, etc.

**Comment by sudo-nice** [comment]
I see, thank you!
