### ISSUE TITLE
Shell commands don't work on directories with spaces or cyrillic symbols

### ISSUE THREAD

**Issue by khaoos-abominable** [vifm/vifm#265]
Hello. I started using vifm a day ago. And I find it's awesome. 

Today I bumped into a cofusing problem on my job. It's a windows 8 x64 machine. Running shell command (e.g `:!!dir /p`) on a pane with the current directory (a whole path) which contains either spaces or cyrillic symbols make it run on a (fallback?) directory, where vifm.exe lives (on my system it is C:\util\vifm).

I haven't tried it on my home linux machine, maybe it's somehow os-dependent.

I believe I miss something simple and it is not really an issue. Any help will be appreciatied.

**Version information:**
Version: 0.8.2
Git info: v0.8.2-0-g3bd3d3965bd6
Compiled at: Jul 16 2016 18:05:13

Support of extended keys is on
Parsing of .desktop files is disabled
Without GTK+ library
Without magic library
Without X11 library
Without dynamic loading of X11 library
Without file program
With remote command execution

Also I use a bit edited sample vifmrc.

**Comment by xaizek** [comment]
Hi. Can you reproduce it when running vifm like `.\vifm --no-configs` option (quit it with `:q!` to do not overwrite `vifminfo` file)? It seems to work fine for me.

There is a fallback to temporary directory (which shouldn't be location of executable), but it happens only if your current path is a UNC path (e.g., `\\machine\shareddir\...`) and this is because `cmd.exe` is not capable of handling such paths.

**Comment by khaoos-abominable** [comment]
Apparently, I can't. It works just fine without config on the windows machine. Thank you for your suggestion. And it works fine with the same config on my home linux machine. I'll try to bisect a config file tomorrow and figure out what happens. And if something is wrong in the sample config file, I'll let you know. Maybe I spoilt it somehow. It's true that I changed line endings to unix ones to share the config between machines. I think the issue could be closed.

**Comment by xaizek** [comment]
> I'll try to bisect a config file tomorrow and figure out what happens.

I just did on your `vifmrc`. I should have checked on sample file initially. It's `set fastrun`. I thought it's disabled by default, it probably should be because of somewhat unexpected behaviour.

With `fastrun` set, vifm doesn't restore original directory with non-latin characters, which is a bug. Thanks for the report!

**Comment by khaoos-abominable** [comment]
Thanks for your investigation. But you should've left in on me. There were more chances that I messed something unintentionally and you would've wasted your time as a result. I am glad that the last thing didn't happen.

I removed the option on windows and now it works like a charm!
