### ISSUE TITLE
(Feature request) deleting+creating if move failed

### ISSUE THREAD

**Issue by rr-** [vifm/vifm#267]
Trying to use FUSE across many computers reveals that in some setups, I can't move the files directly, but creating / copying and deleting them seems to be fine.

The filesystem error I get is usually this:

```
 ~/tornado/.../3090646.dat: Rename operation failed (Operation not permitted)
```

My setup:

```text
                                        ┌─────────────┐
                                        │ Directory 1 │
                                        └─────────────┘
                                       ╱
                                   [fuse]      🡩
                                     🡯         │
┌───────────┐           ┌───────────┐          │
│ Machine 1 │ 🡨[sshfs]─ │ Machine 2 │          X (file move)
└───────────┘           └───────────┘          │
                                     🡬         │
                                   [fuse]      🡫
                                       ╲
                                        ┌─────────────┐
                                        │ Directory 2 │
                                        └─────────────┘
```

Machine 2 is mounted as SSHFS resource on Machine 1. Machine 2 has two local shares mounted with FUSE, that get exposed through SSHFS to Machine 1. All mounts are mounted with `allow_other` flag, also the user names and their UIDs are the same on both machines.

`vifm` is run from Machine 1.

No matter what, I can't get this setup to let me move files directly. It would be cool if `vifm` had a setting that'd fall back to non-atomic file moves for such cases.

(The exact workaround is to <kbd>yy</kbd> <kbd>p</kbd> and <kbd>D</kbd> the original - without the use of trash.)<Paste>

**Comment by xaizek** [comment]
> deleting+creating if move failed

That's pretty much current implementation. It doesn't work in this case because sshfs returns "permission error" instead of "move across mounts error". But looking at source code of sshfs it seems to be limitation of underlying SFTP protocol.

Technically they can implement the workaround (there is already at least one for file renaming), but I guess it won't hurt if vifm will fallback to file copying in case of permission error (if there is not enough permissions we should just get the same error again).

Can be reproduced just by connecting to localhost over sshfs and moving files between two file-systems.
