### ISSUE TITLE
Hiding files specific to a folder (question/feature request)

### ISSUE THREAD

**Issue by rbong** [vifm/vifm#268]
Is it possible to hide files only in a specific folder? I hate how programs clutter up my home directory. I'd like to hide them.
Intuitively, this should work.

```
filter /\/home\/user\/\(files\|to\|hide\)/
```

However it does not.

Currently, I have this in my `vifmrc`.

```
autocmd DirEnter * :filter
autocmd DirEnter /home/user :filter /\(files\|to\|hide\)/
```

**Comment by xaizek** [comment]
> Intuitively, this should work.

This doesn't work because `:filter` is applied only to file names, not whole paths.

It seems to make sense to use the same syntax for `:filter` that is used in `:filetype` and `:highlight` commands that allows multiple types of patterns (`{}`, `{{}}`, `//` and `////`). Then in addition to `////` patterns for this case one would be able to do `:filter {*.o}` and alike, which is simpler than regular expressions.

**Comment by rbong** [comment]
Makes sense that the expression couldn't apply to both the full filename and partial filename.

**Comment by xaizek** [comment]
The implementation is in the `make-filter-take-matcher` branch.  The following should work there:
```
filter ///home/user/\(files\|to\|hide\)//
```
It's a good time for a new release, and as this change might have some non-obvious side effects, it will be merged into the `master` after the release.

**Comment by jhessin** [comment]
I really like the idea of having a `.hidden` file with filenames that I want hidden. It's simple and effective and easily toggled with a `za` if you enable that option. Is it possible to enable that?
