### ISSUE TITLE
vifm: cfg/info.c:1464: read_optional_number: Assertion `nread == 1 && "Wrong number of read numbers."' failed. Aborted (core dumped)

### ISSUE THREAD

**Issue by afergadis** [vifm/vifm#275]
I have compiled version 0.8.2

The application was running fine. At some point, in a `tmux` session, the app crashed using (ZZ) (sorry this is the only things I can recall about reproduction) with the message
```
vifm: cfg/info.c:1464: read_optional_number: Assertion `nread == 1 && "Wrong number of read numbers."' failed.
Aborted (core dumped)
```

Ever since, I get the same error. Reboot didn't help. `make clean; make; sudo make install` also didn't solve the problem.

I hope we will fix it because I really found it very usefull.

**Comment by xaizek** [comment]
Something happened to your `vifminfo` file. The format is quite fragile, but is not corrupted normally, this might be due to some weirdly named file or pattern.

The file itself should be at `~/.vifm/vifminfo` or `~/.config/vifm/vifminfo`. Please upload it here or send to [me](mailto:xaizek@openmailbox.org) to see what went wrong. It includes your paths and input, so you might want to check its content in case it might include some sensitive information (usually it isn't, but anyway).

The file might be easy to restore once nature of the breakage is known, but the easiest "fix" is to just remove it (or rename it).

> I have compiled version 0.8.2

0.9 is available now. But I don't remember fixing bugs related to `vifminfo`.

**Comment by afergadis** [comment]
Here is my [viminfo](https://pastebin.com/4dQDDDBZ).

Indeed removing `viminfo` solved the problem. One more thing. In the `.vifm` folder there was a file `vifminfo_33027` with exactly the same content as `vifminfo`.

**Comment by xaizek** [comment]
> Here is my viminfo.

Thanks (by the way, you can attach files to your messages here). There is a history entry describing a file with newline character embedded in its name.

If this snipped is removed (starts at line 323), everything will work:
```
D/dev/shm/TEES/out
	AVxXQ1xDFJDzUCRLgIob
-log.txt
1
```

It's limitation of the format, which needs to be addressed eventually.

> One more thing. In the .vifm folder there was a file vifminfo_33027 with exactly the same content as vifminfo.

That's a leftover from an attempt to modify the file. There is a standard three-step process: make a copy, modify a copy, overwrite original; it guarantees that you won't see `vifminfo` in inconsistent state.
