### ISSUE TITLE
Work around the common pain point of <c-i> and <tab> being the same ASCII char

### ISSUE THREAD

**Issue by dimonomid** [vifm/vifm#283]
Currently, if `cpoptions` does not contain `t` flag, there's no way at all to go forward in directory history. However, I'd like to work around the issue by altering my terminal emulator settings to emit some custom sequence when I type `<c-i>`. Technically I could remap `<tab>` to `<space>` instead, but I don't want to do that, as I still want to have the actual tab sometimes.

My proposal is to add `:hprev` / `:hnext` commands, which will be analogous to `<c-o>` / `<c-i>`, and thus I'll setup my terminal to emit `:hnext\r` when I type `<c-i>`.

@xaizek , what do you think? Let me know if it does or does not sound good; when we settle on something, I'll implement it. (well, actually the proof of the above concept already works for me, just not going to polish and send a PR yet since I might miss some better solution)

**Comment by xaizek** [comment]
> there's no way at all to go forward in directory history

I'm not actually suggesting to use this, but it's possible:
```vim
nnoremap ,W <tab>
nnoremap W :set cpoptions-=t | execute 'normal ,W' | set cpoptions+=t<cr>
```

The ideal solution would probably be to do something like `<fXX>` key codes in Vim, which can be redefined by a user, but it seems too complicated relative to the issue. You could also make up custom keycode and map that to the awful thing above, but that's a weird approach.

So, adding commands to navigate history makes sense. Except that I'd use `:histprev` / `:histnext` to match `:sibl*`, and also because single-char abbreviations tend to become ambiguous.

> and thus I'll setup my terminal to emit `:hnext\r` when I type `<c-i>`

You might want to make a keycode which doesn't contain carriage return and map that instead, otherwise you might accidentally run something (e.g., when in command-line mode).

**Comment by dimonomid** [comment]
Thanks for the tips. Yeah I was also thinking of something like `<fXX>`, and agree that it's not worth right now.

Sure, will do `:histprev` / `:histnext`.

> You might want to make a keycode which doesn't contain carriage return and map that instead, otherwise you might accidentally run something (e.g., when in command-line mode).

Right, good point.
