### ISSUE TITLE
Interactive commands in system("...")

### ISSUE THREAD

**Issue by dimonomid** [vifm/vifm#284]
Some background first: there is an awesome tool `fzf`: [A command-line fuzzy finder](https://github.com/junegunn/fzf). On top of that, I've built a simple shell bookmarking utility: [Fuzzy bookmarks for your shell](https://dmitryfrank.com/articles/shell_shortcuts). So, when I need to `cd` to one of my bookmarked dirs, I type `cdg`, and after a few more keystrokes I'm done. Of course, I wanted to bring that to vifm.

As I quickly found out, `:echo system('fzf')` doesn't work: it hangs untill I hit `Ctrl+C`, then prints some raw terminal escape sequences, and that's it.

Luckily `:!fzf` does work, so currently I worked this around with `--remote`: 

```
command! cdg :execute '!vifm --server-name' v:servername '--remote "+cd $(cdscuts_glob_echo | fzf)"'
```

That hack works, but still, I believe `system()` should be fixed. Must have something to do with the output redirection, controlling terminal, etc; I checked the code and apparently `:!` and 
`system()` use completely separate codepaths, so might not be trivial. What do you think?

**Comment by xaizek** [comment]
This kinda works:
```vim
:echo system('fzf 2> /dev/tty')
```
The reason you need to redirect `stderr` is because that's how `fzf` finds terminal (at least last time a looked into ruby version). Input and output are usually redirected, so they rely on `stderr`.

It actually messes up terminal state a bit, because `system()` isn't meant to be used with interactive commands. Interactive commands need curses interface being turned off before they are run, which you don't usually want for simple things which generate output without user interaction.

Vim operates the same way. To run interactive commands in this manner either interface of `system()` needs to be extended or a new function introduced (say, `systemi()`, `spawn()` or something) to avoid conflicts with Vim.

**Comment by dimonomid** [comment]
Thanks for the tips.

> ... to avoid conflicts with Vim.

Not sure if compatibility with the shortcomings of Vim is a goal for vifm, but anyway, introducing a separate function seems like a fairly minor point, so, up to you of course.

**Comment by xaizek** [comment]
> Not sure if compatibility with the shortcomings of Vim is a goal for vifm, but anyway, introducing a separate function seems like a fairly minor point, so, up to you of course.

This isn't a shortcoming of Vim (although they could have an argument to allow interactivity), dealing with interactivity by default is just out of scope for `system()`. In all use cases for `system()` I have, I don't need extra screen flickering. And in general changing behaviour while preserving the interface is a bad idea, in nvim for example they changed `:!` to not allow interactive applications...

**Comment by dimonomid** [comment]
Ok, I think I missed that adding support for interactivity would break the compatibility. Yes, changing the behaviour in an uncompatible way is a bad idea.

**Comment by xaizek** [comment]
> would break the compatibility for some (many?) use cases

It wouldn't actually break anything, just annoy. By the way, `2> /dev/tty` for `fzf` will be needed either way.

**Comment by xaizek** [comment]
Ended up calling it `term()`. So new command is
```vim
:echo term('fzf 2> /dev/tty')
```
Functional keys and screen cleanup after closing vifm now work fine after using this command.

**Comment by dimonomid** [comment]
Awesome, thank you!
