### ISSUE TITLE
Delete directory from vifm, exit, cd .. leads to ~.vifm/Trash

### ISSUE THREAD

**Issue by arings** [vifm/vifm#286]
Repro:

```
~$ mkdir testdir
~$ cd testdir/
~/testdir$ vifm ~

... from vifm delete directory "testdir" and exit :q or ^ZZ ...

~/testdir$ cd ..
~/.vifm/Trash$ 
```

Technically correct, since `vifm` doesn't actually deleting stuff but moving into ~/.vifm/Trash instead, as I understand.

Or maybe, in such cases, move out of deleted directory one level up on exit?

**Comment by xaizek** [comment]
Vifm doesn't change parent directory of the shell, it's not even possible. This is just somewhat counter-intuitive side-effect of the way shells work with paths (correct and more secure way, but also more cumbersome and with such weird behaviour; most applications (vifm included) operate differently).

 What happens is that shell keeps a handle to the directory, vifm moves the directory and shell then resolves parent directory from the new location. You can reproduce it even with a single shell:
```bash
+[~]$ mkdir a b
+[~]$ cd a
+[~/a]$ mv $PWD ../b
+[~/a]$ cd ..
+[~/b]$ 
```

The only way to alter the behaviour is to do not do real move, but reconstruct directory tree in a trash directory (you can permanently delete files with <kbd>DD</kbd> or `:delete!`, by the way). This doesn't sound like a good idea at all though, because it removes atomicity guarantee from move operation as well as loses original metadata.

**Comment by arings** [comment]
Thank you very much for detail explanation!

I ended up with small function in `~/.bashrc`
It moves one level up or in such cases -- up until first valid path:

```
function cdu() {
  path=$PWD
  if [ -d $path ]; then
    cd "$(dirname $path)"
  else
    while [ ! -d $path ]
    do
      path="$(dirname $path)"
    done
    cd $path
  fi
}
```
