### ISSUE TITLE
Use command names with numbers

### ISSUE THREAD

**Issue by mimadrid** [vifm/vifm#291]
I would like to have in my vifmrc these lines
```
command! md5 md5sum %f %F %m
command! sha1 sha1sum %f %F %m
command! sha256 sha256sum %f %F %m
```
But those lines cause a File Sourcing Error

How I could do it?

Thanks in advance.

**Comment by xaizek** [comment]
Command names can't contain numbers:
```
Command name cannot contain numbers or special symbols (except single trailing '?' or '!').
```

The reason for this is that it allows omitting space after command name if first argument starts with a number (or any non-letter), just like in `:d4`.

I thought Vim has the same rules for user-defined commands, but turns out Vim does allow numbers and requires space. I don't like this inconsistency in behaviour though. And if numbers are allowed, but space isn't required, some forms of commands will be ambiguous...

The best thing you can do at the moment is probably this:
```
command! mdfive md5sum %f %F %m
command! shaone sha1sum %f %F %m
command! shatwofivesix sha256sum %f %F %m

cabbrev md5 mdfive
cabbrev sha1 shaone
cabbrev sha256 shatwofivesix
```

**Comment by mimadrid** [comment]
@xaizek, you're awesome, keep it up and you're totally right, I'll use cabbrev. Thanks a lot.
