### ISSUE TITLE
Feature request: delete trash directories on `:empty`

### ISSUE THREAD

**Issue by rr-** [vifm/vifm#294]
Using trash gets cumbersome when having a lot of mount points: I find myself constantly removing `.vifm-Trash-1000` leftover directories from various places on HDD. It would be nice if `:empty` removed empty directories.

**Comment by xaizek** [comment]
Since we remove all files in them either way, we can as well remove the directory too. Except that some directories might be created by a user, therefore probably only directories specified via `%r`/`%u` in `'trashdir'` should be deleted (there is probably only one that has absolute path, which shouldn't be annoying).
