### ISSUE TITLE
'%e' timefmt doesn't work

### ISSUE THREAD

**Issue by traycerb** [vifm/vifm#295]
Just trying vifm (w32-se-0.9) and can't get `%e` option ( Like `%d`, the day of the month as a decimal number, but a leading zero is replaced by a space.) to work.  The whole time time field is blanked out when the directory is listed, irrespective of position of `%e` in the timefmt string.

**Comment by xaizek** [comment]
Vifm doesn't do any special processing in this case and passes format string directly to `strftime()` function provided by the system. The problem is that on Windows they don't implement many things. In particular I don't see `%e` on the relevant [MSDN page](https://msdn.microsoft.com/en-us/library/fe06s4ak.aspx).

**Comment by traycerb** [comment]
thanks for pointing me in right direction.  that page shows that microsoft offers the alternative notation for equivalent output:

`
%#d, %#H, %#I, %#j, %#m, %#M, %#S, %#U, %#w, %#W, %#y, %#Y | Remove leading zeros (if any).
-- | --

`

So `%#d` is equivalent to `%e` and tested and works.  Thanks.

**Comment by traycerb** [comment]
further tested, there is a slight difference in that the leading zero is indeed stripped, but not subsequently replaced with a space (which messes up formatting).

**Comment by xaizek** [comment]
Depending on where you put day in the format changing alignment to the opposite might help.
