### ISSUE TITLE
100% CPU usage when open file with background app and nonempty STDERR and STDOUT

### ISSUE THREAD

**Issue by petRUShka** [vifm/vifm#296]
I have following code in my `~/.vifm/vifmrc`:

```
filextype *.doc,*.docx,*.xsl,*.xlsx,*.ods,*.odt libreoffice %f &
```

Therefore when I open document in vifm I run libreoffice (I have libreoffice firejailed) and see following output:

```
┌───────────────────── Background Process Error ─────────────────────┐
│                                                                    │
│ Reading profile /etc/firejail/libreoffice.profile                  │
│ Reading profile /etc/firejail/libreoffice.local                    │
│ Reading profile /etc/firejail/globals.local                        │
│ Reading profile /etc/firejail/disable-common.inc                   │
│ Reading profile /etc/firejail/disable-devel.inc                    │
│ Reading profile /etc/firejail/disable-passwdmgr.inc                │
│ Reading profile /etc/firejail/disable-programs.inc                 │
│ Warning: noroot option is not available                            │
│ Warning: /sbin directory link was not blacklisted                  │
│ Warning: /usr/sbin directory link was not blacklisted              │
│                                                                    │
│  Press Return to continue or Ctrl-C to skip other error messages   │
└────────────────────────────────────────────────────────────────────┘
```

And until I press Return in vifm window vifm eats 100% CPU which isn't ok for Laptop for example beacuse of hidden battery drain. And not ok anyway.

**Comment by xaizek** [comment]
Thanks for the report. Doesn't seem to be easy to reproduce, but I've seen it once now, so should be able to track it down eventually.

**Comment by petRUShka** [comment]
In my case it's very easy to reproduce: I have to just open any document in libreoffice.

**Comment by petRUShka** [comment]
My typical workflow:

1. Open document
2. Start editing
3. Reporting sudden fan noise
4. Switch to vifm, press `Enter`
5. Switch back to libreoffice, continue editing

**Comment by xaizek** [comment]
Steps don't seem to be complete: you need to run at least two processes in background since start of vifm, otherwise it won't hog CPU.

This is how I reproduce the issue reliably:
1. `:!sleep 10m &`
2. `:!sleep 1 && echo this is a fake error message 1>&2 &`
3. Don't press Enter and CPU load will increase.

****

As a workaround for now you can change the command in `vifmrc` to:
```
filextype *.doc,*.docx,*.xsl,*.xlsx,*.ods,*.odt libreoffice %f %i &
```
This will suppress the dialog avoiding the issue. This is actually a useful thing to do in general for noisy applications. If needed, pressing <kbd>e</kbd> in `:jobs` menu will show errors from background processes that are still running, but usually you don't care much about that output.

**Comment by petRUShka** [comment]
Thanks. Your steps more accurate than mine.
