### ISSUE TITLE
Find files in subfolders

### ISSUE THREAD

**Issue by GhostValk** [vifm/vifm#302]
One feature i miss from ranger is the possibility of changing the current view to flat chain, so i can see all the files in the current folder and the subfolders in the same "level" and then can easily filter by any pattern to basically make a "find" in the subfolders.

It's possible to make something similar in vifm?

Thanks in advance

**Comment by xaizek** [comment]
I'm not sure how equivalent these approaches are (I guess it depends on use), but there are two ways of doing it in vifm:
1. `:tree` and then search or filter.
2. `!find%u`/`!find -maxdepth 2%u` and then search or filter.

The difference (apart from tree/list representation) is that with second command new files won't be added automatically and regular filters also won't be applied, because the view is more like a snapshot in this case.

Alternatively, there is `:find pattern`, which will open a menu with results (press <kbd>b</kbd> to load it into current view as a list).

**Comment by GhostValk** [comment]
The :tree approach would be EXACTLY what i'm trying to achieve, but the filter command is not filtering in the subdirectories :/

**Comment by xaizek** [comment]
It actually does, this is why they get filtered out. To be displayed all components of a path need to pass through the filter. This is because `:tree` tries to display the same files that you would see if you have visited directories in sequence. Local filter (<kbd>=</kbd>) on the other hand ignores intermediate path components, and I think this is what you actually want to use because `:filter` needs manual resetting back to its previous value.

**Comment by GhostValk** [comment]
Oh, i had a misconception since the first time i started using vifm, i thought filter was actually what `filter!` does. Well `:tree` + = does what i need, really thanks a lot man!

A small final question, how can i revert the view from tree to the default one?

**Comment by xaizek** [comment]
<kbd>h</kbd> at the top level node or <kbd>gh</kbd> at any level will leave tree view.

Also forgot to say that if you want local filter to reset when you enter/leave tree form, see [`cvoptions`](https://vifm.info/vimdoc.shtml#vifm-%27cvoptions%27).
