### ISSUE TITLE
select files in pane, that was created today 

### ISSUE THREAD

**Issue by bubogelderman** [vifm/vifm#315]
Hello!
Im using vifm-w64-se-0.9.1-binary (windows), and try :select *%date%* (files with current date, for exemple "*01.01.2018*")
How can i do that on windows for nnremap binding?

For now i use this keybind
`nnoremap <f1> :normal Scgg3jv6j <cr>`
Sc - sort created time reverse (nnoremap Sc :set sort=-ctime,+iname <cr>)
gg - go top line
3j - down to files (nor dir)
v6j - select 6 archives, that was created today

sry for my eng =(

**Comment by xaizek** [comment]
Hi!

I think the most reliable way would be to use an external application to determine which files match the precondition, since there is no builtin checks for file dates.

On Unix-like system the following selects files that were modified yesterday:
```
:select! !find . -maxdepth 1 -newermt 2018-02-20 ! -newermt 2018-02-21
```
Unfortunately I don't know similar Windows-specific command, but if there is one that outputs list of files, it should work. Alternatively, if you have Unix-tools in your `%PATH%`, `find` should be there.

**Comment by bubogelderman** [comment]
Thank you for advices and examples!
This one work great for me!

    command! seltodays :execute 'select! *'.system('echo %%date%%').'*'
    nnoremap <f1> :seltodays <cr>

I just add keybind for them!
Other two examples i tested too, buthe  just select all files.
Thank you very much for your help with awesome powerfull vifm!
