### ISSUE TITLE
vifm flickers under windows every a few seconds

### ISSUE THREAD

**Issue by randomizedthinking** [vifm/vifm#319]
I am using vifm-0.9.1 under Windows 7, and found that the vifm screen will flicker every a few seconds.

Both cmd and ConEmu have the same issue. It is minor, but would be nice to be handled.

**Comment by xaizek** [comment]
This is probably due to file system being changed and screen being redrawn. I think it happens often when a pane is at root of system drive.

I'm not sure if it's possible to get rid of this in general as I assumed that this is something specific to pdcurses or `cmd.exe` (by the way, you can also try [console2](https://www.maketecheasier.com/console-2-windows-command-prompt-alternative/)), since on other systems even if <kbd>Ctrl-L</kbd> is pressed down for a long time, there is no flickering. However, it's still possible that something is being drawn incorrectly and there is a difference between screen updates on Windows and non-Windows systems.

**Comment by xaizek** [comment]
It's not `cmd.exe`'s fault after all. It was related to Windows specific code and changes made five years ago + incomplete implementation in pdcurses.

Binaries with the fix (but also with [new features](https://github.com/vifm/vifm/blob/5c80aef075a6a375379362cf53d93d347024e834/ChangeLog#L3-L41)): [32-bit](http://builds.vifm.info/builds/vifm-w32-se-v0.9.1-102-g163cf151d451.exe), [64-bit](http://builds.vifm.info/builds/vifm-w64-se-v0.9.1-102-g163cf151d451.exe).

Thanks for prompting to look into this, I assumed that it's not a bug.

**Comment by randomizedthinking** [comment]
Thanks, xaizek. The fix works out great...
