### ISSUE TITLE
Feature request: never display `..`

### ISSUE THREAD

**Issue by rr-** [vifm/vifm#324]
I'm trying to hide `..` and found out that right now `dotdirs` offers following values:

- `nonrootparent`: display `..` everywhere but `/`
- `rootparent`: display `..` only in `/` (I'm not sure what's the use case)

I think it would make sense to offer `never` option (and perhaps also `always` for consistency), since it's weird to see `..` in `/`.

>Note that empty directories always contain "../" entry regardless of value of this option.  "../" disappears at the moment at least one file is created.

Additionally, control over this behavior would be cool as well.

**Comment by xaizek** [comment]
I think you missed that `'dotdirs'` is an option of type `set`, so:

* `never` == `set dotdirs=`
* `always` == `set dotdirs=rootparent,nonrootparent` 

>> Note that empty directories always contain "../" entry regardless of value of this option. "../" disappears at the moment at least one file is created.
>
> Additionally, control over this behavior would be cool as well.

This was done because otherwise things get weird. There will be no place to put cursor, position will be 0 out of 0, nothing to preview, nothing to show on status line, etc. This would make empty directories standout among all directories. This is possible to do, but the result will look strange.

**Comment by rr-** [comment]
> >> Note that empty directories always contain "../" entry regardless of value of this option. "../" disappears at the moment at least one file is created.
> >
> > Additionally, control over this behavior would be cool as well.
> 
> This was done because otherwise things get weird. There will be no place to put cursor, position will be 0 out of 0, nothing to preview, nothing to show on status line, etc. This would make empty directories standout among all directories. This is possible to do, but the result will look strange.

I see, this definitely sounds like a lot of `if ()` for a very small cosmetic change. I guess it's not worth it.

> I think you missed that `'dotdirs'` is an option of type `set`, so:
> 
> * `never` == `set dotdirs=`
> * `always` == `set dotdirs=rootparent,nonrootparent` 

You're completely right. Thanks!
