### ISSUE TITLE
Colours for different file extensions

### ISSUE THREAD

**Issue by madders** [vifm/vifm#33]
Hi,

Are there any plans to enhance colour schemes so files can be coloured based on their extension (rather than just `Directory`, `Link`, `Broken Link`, `Socket`, `Device`, `Executable` and `Fifo`)? This would mean the directory list in vifm could be consistent with the output from `ls -l`. Currently, my `ls -l` looks much nicer than the file list in vifm.

If vifm was able to read the colour scheme directly from `.dir_colors`, that would be great!

Thanks,
Michael

**Comment by xaizek** [comment]
Hi Michael,

`:highlight` command is now finally able to highlight files which names match specific patterns.

I didn't write script for parsing `~/.dir_colors`/`/etc/DIR_COLORS`/`$LS_COLORS` yet, but that should be quite easy to do, will try that soon.

**Comment by madders** [comment]
Hi there,

Thanks for implementing this! Sorry for taking so long to respond. I've tested it out and it's working great. I tried out the curly braces notation first and that caused a segmentation fault when I started vifm. However with the regular expression notation it works perfectly.

Thanks,
Michael

**Comment by xaizek** [comment]
Hello,

Thanks for testing it out!

> I tried out the curly braces notation first and that caused a segmentation fault when I started vifm.

Thanks, looks like I broke it afterwards while adding `i`/`I` flags to regular expression patterns and it went unnoticed until now. Fixed (added tests for this, so won't happen again).

I forgot to leave a comment about dircolors script, which is located at `src/vifm-convert-dircolors` in the repository. It is also installed along with other executables on `make install` and there is a short man-page on its usage.

**Comment by madders** [comment]
Yes - I noticed the ```vifm-convert-dircolors``` script only after I had converted it manually! But I tested it anyway to see how it looked, it worked perfectly, and looked nicer (with the human readable option), than what I had done.

What does the ```I``` flag do?

Is there any order of precedence? It looks like it merges the colors when there is more than one match. For example, if I have a broken link, the background is supposed to be red, and foreground black. But if the file extension matches a regular expression with a red foreground, then the foreground is made red (and I can't read it). I've tried moving the order in the file, and it makes no difference.

**Comment by xaizek** [comment]
> What does the I flag do?

It makes patterns case sensitive, `ls` seems to be case sensitive always.

> Is there any order of precedence?

There is, amongst name specific highlights, but all of them are applied after regular highlight groups. Looks like I forgot to document this.

> It looks like it merges the colors when there is more than one match.

But at most one name specific highlight is applied.

> But if the file extension matches a regular expression with a red foreground, then the foreground is made red (and I can't read it). I've tried moving the order in the file, and it makes no difference.

Highlight with regular expression should overwrite `ctermbg`, otherwise it might be `default`, which means `transparent` (this is curses terminology).

Highlight hierarchy now looks like this:
```
Win
    Directory
        patterns
    Link
        patterns
    BrokenLink
        patterns
    Socket
        patterns
    Device
        patterns
    Fifo
        patterns
    Executable
        patterns
            Selected
              CurrLine
              OtherLine
```

**Comment by madders** [comment]
Ok - I was using ```ctermbg=default```, so I guess it picked up the background of the regular highlight group (for BrokenLink). I can probably get it to look how I want, but it's difficult because I like to use the ```default``` option, because I use transparency in the terminal window. So if I set the background to ```black``` instead of ```default```, it won't look so nice.

**Comment by xaizek** [comment]
Good point, as of now hierarchy items deeper than root are unable to use terminal default colors.

We could differentiate these special values. It shouldn't be hard to add, just need a separate value name since `default` is already taken. `-1` is one of `default` synonyms, so `-2`? Like "more default than that"... Or maybe `term` or `terminal` which at the same time states the meaning clearer than `default` does. I don't think there is a colour named `terminal`, so it shouldn't clash with any colour names.

**Comment by madders** [comment]
Could you explain this again. I don't fully understand. Above you said "at most one name specific highlight is applied". But the behaviour I'm seeing is two highlights are getting applied. Unless name specific just refers to Directory, Link, BrokenLink etc. So one of those is applied, then one of the regular expression / pattern highlights is applied? This seems to be the behaviour I am seeing.

I don't understand what you saying about hierarchy items deeper than root. I think with your suggestion you are saying that ```terminal``` would cause a transparent background for a regular expression highlight  regardless of the background set by the name specific highlight?

**Comment by xaizek** [comment]
> Could you explain this again. I don't fully understand.

Sorry, it's not always easy to understand me even when I use my native language.

I refer to `Directory`, `Link`, `BrokenLink` etc. groups as "type specific" because this is how they are chosen and I call those that match file names "name specific".

> So one of those is applied, then one of the regular expression / pattern highlights is applied?

Exactly.

> I don't understand what you saying about hierarchy items deeper than root.

Meaning of the `default` can change for different items, those that are closer to the left can use it for "default colour of terminal emulator", but for items to the right `default` means "mixed colour of previous items" or "transparent colour".

> I think with your suggestion you are saying that terminal would cause a transparent background for a regular expression highlight regardless of the background set by the name specific highlight?

Yes, you will be able to set `ctermbg=terminal` to use default terminal emulator colour no matter where that highlight group is located in the hierarchy.

**Comment by madders** [comment]
Ok thanks - that makes sense.

So I think ```terminal``` would be a good option.

However for me, the best thing would be to change the hierarcy. I think the type specific group should be applied after the name specific. If I have a BrokenLink, I would rather see those colours, instead of the colours for the name. If we go with the ```terminal``` option, and I use ```terminal``` for my name highlight, then it would totally overwrite the BrokenLink highlight (with the red background). This is better than what it currently does (keeping the background so I can't read the text), but for me the best would be to just apply the BrokenLink highlight (or apply it last). I don't know what you think, but I think the highlighting based on the type is higher priority.

But it's a small thing, I don't mind whatever you choose to do - it's great to have the name highlighting now - vifm looks a lot nicer!

**Comment by xaizek** [comment]
You're right, if I name directory say `dir.tgz`, `ls` displays it as a directory, while it's colored as an archive in vifm, which is wrong. Same can be said about symbolic links and other file types. Thanks for pointing that out.

I didn't test it much, but see `reverse-highlight-apply-order` branch, the change basically required swapping order of two lines (well, almost).

**Comment by madders** [comment]
I've been testing it tonight, and it looks good. It's exactly like the ```ls``` output now, which is perfect for me. Thank you!
