### ISSUE TITLE
Execution on pressing lower case L

### ISSUE THREAD

**Issue by Naegolus** [vifm/vifm#334]
Hi,

thank you so much for this amazing tool!
Can't imagine one day without it!

I have one question though.
When i am using lower case 'L' ('l') to navigate to sub folders then sometimes i accidentally hit 'l' on files.
The files are then either executed or opened. Depending on the option "norunexec" / "runexec".
Is there some way to disable 'l' for regular files completely?

Best Regards,
Joe

**Comment by xaizek** [comment]
Hi, glad to hear vifm serves you well.

There is no builtin option to do what you want, but it can be implemented by redefining meaning of <kbd>l</kbd> key in the following way:
```vim
command! enterdironly : if filetype('.') == 'dir' ||
                     \     filetype('.') == 'link' &&
                     \     system(expand('ls -d %c/. 2>/dev/null')) != ''
                     \|     execute 'normal! l'
                     \| endif
nnoremap l :enterdironly<cr>
```
Which doesn't look especially pretty due to special handling of symbolic links to directories, but seems to work fine.  Maybe I should add second optional argument to `filetype()` to make it resolve symbolic links.

**Comment by Naegolus** [comment]
wow. Works like a charm! Thank you!

**Comment by xaizek** [comment]
Better version that will work in the next release (the one after 0.9.1):
```vim
nnoremap <silent> l : if filetype('.', 1) == 'dir'
                   \|     execute 'normal! l'
                   \| endif<cr>
```

**Comment by Naegolus** [comment]
Hey cool thank you again!
I will try that.
