### ISSUE TITLE
sigint signal sent via ^c is sent to sshfs fuse mount program causing fs to be unmounted

### ISSUE THREAD

**Issue by jose1711** [vifm/vifm#356]
- step into sshfs mounted filesystem
(defined as manual suggests ```filetype FUSE_MOUNT2|sshfs %PARAM %DESTINATION_DIR```)
- run ```:!!ls```
- instead of hitting Return key, do <kbd>Ctrl</kbd>-<kbd>c</kbd>

Expected behaviour:
vifm panes are displayed, no errors are shown

Actual behaviour:
pane with fuse-mounted filesystem is emptied, when trying to enter its parent directory an error message is shown: ```FUSE UMOUNT ERROR - Can't unmount .... It may be busy```

**Comment by xaizek** [comment]
It's a bug, but I think it's in `sshfs`. They don't always call `setsid()` in [the code](https://github.com/libfuse/sshfs/blob/eac420791c667b038817aaa481c67646e9654e15/sshfs.c#L1064-L1076) and it should actually go after the first `fork()`. Since they don't untie daemon from the terminal, it gets affected by it. And vifm can't work around it, because it will break cancellation of mounting.

`archivemount` for example uses `fuse_deamonize()` and doesn't have such problems. I've also reproduced described behaviour of `sshfs` with midnight commander.

**Comment by xaizek** [comment]
Created libfuse/sshfs#141.
