### ISSUE TITLE
File browsing performance on NFS

### ISSUE THREAD

**Issue by 17dec** [vifm/vifm#357]
Thanks for vifm, I've been enjoying it for quite a while.

Unfortunately, the update from 0.9 [*] to 0.9.1 introduced a regression for me. It appears that vifm is now reading the contents of all the directories in the current view - at least, that's what a strace suggests - and this is causing browsing through a large directory on NFS to be intolerably slow.

Is this intended behavior? Are there settings to influence this behavior?

[*] I least, I think I upgraded from 0.9 some time ago, but it could be an earlier version. I wanted to do a git bisect to find the culprit, but #325 isn't making that easy.

**Comment by xaizek** [comment]
>  It appears that vifm is now reading the contents of all the directories in the current view [...]

Do you mean that vifm recurses into directories or just lists information of every file of current directory? It always pulled information about every file and I don't think anything has changed recently related to directory listing.

> I wanted to do a git bisect to find the culprit, but #325 isn't making that easy.

The fix is a [tiny change](https://github.com/vifm/vifm/commit/480d4f0681ac3dbec6ffaa9d7f4fd48d86923f16). I'd expect something similar to `sed 's/\btinfo\b/tinfow/g' src/Makefile` after bisect step to do it (it might be annoying yes, but sometimes had to do similar things).

**Comment by 17dec** [comment]
> Do you mean that vifm recurses into directories

Yes.

A simple sed did the trick indeed. I just finished doing the bisect, using `strace -fp $PID -e open` to see if vifm was reading subdirectories, and found a91feea82a939fb235397b9a9615daeca8a91bab to be the commit that introduced this behavior. If I interpret that commit correctly, it looks like entry_calc_nitems() is now called regardless of the `cfg.view_dir_size == VDS_NITEMS` check - that would indeed explain things.

At the same time, it also made me realize that there already is a 'slowfs' option to disable this behavior altogether. That option works beautifully well (everything is fast again!), so this issue is solved as far as I'm concerned.

Thanks for the help!

**Comment by xaizek** [comment]
> it looks like `entry_calc_nitems()` is now called regardless of the `cfg.view_dir_size == VDS_NITEMS` check

Damn it. I forgot about this directory listing. Thank you for bisecting and finding the cause!
