### ISSUE TITLE
Core dump: Duplicated file names in the list?

### ISSUE THREAD

**Issue by jose1711** [vifm/vifm#360]
```
mkdir /tmp/mnt
pakmount freedoom1.wad /tmp/mnt
vifm /tmp/mnt
vifm: filelist.c:2274: add_to_trie: Assertion `error == 0 && "Duplicated file names in the list?"' failed. 
5475 abort (core dumped)  vifm /tmp/mnt
```
indeed.. there are duplicate entries:
```
$ ls -1 | sort | uniq -d
BLOCKMAP
LINEDEFS
NODES
REJECT
SECTORS
SEGS
SIDEDEFS
SSECTORS
THINGS
VERTEXES
```
but somehow mc, ranger and nautilus can handle such situation (in a different way though)

**Comment by xaizek** [comment]
> but somehow mc, ranger and nautilus can handle such situation (in a different way though)

And always incorrect in some way I assume, because I don't think it's possible to make it work properly.

The assertion is there actually to catch bugs of vifm, it wasn't supposed to find a case when there are files with identical paths as it should never happen. Without this assertion it should work in some way.

**Comment by jose1711** [comment]
you're right that these situation should not happen but imagine you have an important  background job running and you step into a buggy fuse-mounted filesystem. maybe a user warning would be better?

**Comment by xaizek** [comment]
I was thinking about just dropping the assert, but a warning could be a better option, thanks.
