### ISSUE TITLE
Improve deletion confirmation dialog

### ISSUE THREAD

**Issue by ovk** [vifm/vifm#372]
Currently file deletion confirmation dialog shows a message similar to:
```
Are you sure you want to delete 1 file?
```
(link to the [code](https://github.com/vifm/vifm/blob/2039e24008f74a20db75f147c9e1055b3418d809/src/modes/dialogs/msg_dialog.c#L636))

However, even for one file the name of the file that is about to be deleted is not displayed.

It is especially irritating when the dialog overlaps the selected file so you have no way of telling whether you about deleting what you want or not.

I think displaying the file name would be really helpful (again, at least when just one file is selected).

This is what `rm -i test.txt` does, for example:
```
rm: remove regular file 'test.txt'? 
```

**Comment by xaizek** [comment]
I agree, it's actually in the [`TODO`](https://github.com/vifm/vifm/blob/02710c4cca53ded3187959ad39e4481c2697cc05/TODO#L14):
```
title: Better removal confirmation messages.
comment: They should contain list of files.
```
It should be quite easy to do after some recent changes in that part of the code. I think it wasn't done because of the [second place](https://github.com/vifm/vifm/blob/02710c4cca53ded3187959ad39e4481c2697cc05/src/ops.c#L283-L291), where there is no access to the list, but we can display at least one file name there.
