### ISSUE TITLE
Pane tabs don't persist between :restart's, but global tabs do

### ISSUE THREAD

**Issue by mwgkgk** [vifm/vifm#378]
Minor thing, because in general there's no good way (that I found) to kill Vifm without closing all the tabs first, so this inconsistency only applies to `:restart`, which is mostly used during config.

Having tabs persist after closing Vifm would make running new instances sort of awkward, since you'd have to close all the tabs first. Which technically can be avoided by passing args. (I do use multiple instances of Vifm in tmux tabs, which is sort of outclassed by `tabscope=global`, but `tabscope=pane` is super valuable I think, and this way I get both.) Vim's way of "persistent tabs" is sessions.

This ticket is about `:restart` & `tabscope=pane` behavior.

**Comment by xaizek** [comment]
That's a side effect of tabs getting cleared on switching value of `tabscope`. Tabs should disappear in both cases, but I forgot to do this explicitly, hence the inconsistency.

> Having tabs persist after closing Vifm would make running new instances sort of awkward, since you'd have to close all the tabs first.

That's another issue with persistent tabs. The first one is that what tabs get stored would actually depend on order in which instances are closed, because merging them won't make much sense.

> Vim's way of "persistent tabs" is sessions.

The way they are implemented makes them inconvenient to use without additional plugins for session management. Maybe Vifm needs something builtin for that. Otherwise the user will have to remember to do `:mksession` before `:qa` or all changes will be lost.

**Comment by mwgkgk** [comment]
Anecdotally, I don't use auto session saving in Vim :) But I do use [pielgrzym/ctrlp-sessions](https://github.com/pielgrzym/ctrlp-sessions) & a nice hotkey for :MkS (the command knows when we're "in" a session to re-save without prompting).

Since `:restart` is not really creating any conflicts in regards to new instances, does it make sense to leave tabs as they are as a special case?

If you feel that specialcasing this is too hacky, this issue can be closed. Big fan of your work :+1:

**Comment by xaizek** [comment]
> Since `:restart` is not really creating any conflicts in regards to new instances, does it make sense to leave tabs as they are as a special case?

It won't be a more special case than leaving current directory intact on `:restart`. However, without adding extra code all tabs except for current one are unaffected by the `:restart` (local options and filters aren't reset, history isn't reloaded). With that bit added, I'm fine with `:restart` not killing all tabs.

Thanks for reporting this, by the way :)
