### ISSUE TITLE
UI blocks when doing file i/o operations

### ISSUE THREAD

**Issue by enanajmain** [vifm/vifm#400]
I just wanted to know whether it's a feature of vifm to freeze the ui when doing copy/move. And what is the workflow to continue using vifm while doing copy/move. Do I use another tmux pane?

**Comment by xaizek** [comment]
Not sure about it being a feature, but it is intentional behaviour. If you start an operation, then you should either wait through it or cancel it. If you want to run something in background, there are [:put](https://vifm.info/vimdoc.shtml#vifm-%3Aput), [:copy](https://vifm.info/vimdoc.shtml#vifm-%3Acopy), [:move](https://vifm.info/vimdoc.shtml#vifm-%3Amove) and [:delete](https://vifm.info/vimdoc.shtml#vifm-%3Adelete) commands, which can be backgrounded. However, by running operations in background you lose ability to undo/redo them.
