### ISSUE TITLE
Autocmd ga or gA

### ISSUE THREAD

**Issue by sixcircuit** [vifm/vifm#402]
Great tool. Thanks a bunch. I read the manual and I've been trying to autocalculate (and cache) directory sizes when I change directories. I tried this `:autocmd DirEnter * :normal ga` but it doesn't seem to be working. Maybe it's not supposed to. Any ideas? I think it would be a nice feature.

Best,

Kendrick

**Comment by xaizek** [comment]
Looks like autocmd is invoked with view being mostly in old state, but not quite. And the command ends up trying to use file that doesn't exist. This is a bug, thanks for reporting. `:autocmd` is used mostly to set local options, which doesn't care much about file list, so I guess nobody noticed weird state until now.

By the way, `normal ga` updates only file under cursor (or selection, if present), this would try to calculate sizes of all files:
```vim
autocmd DirEnter * %select | exe 'normal ga' | %unselect
```

Since `ga` is recursive, it could be enough to run it once at some top-level directory when you need sizes.
