### ISSUE TITLE
Vifm 0.10 Crashes when resizing

### ISSUE THREAD

**Issue by Numeromancer** [vifm/vifm#405]
I'm running Vifm in Windows 7 withing ConEmu.

Whenever the window is resized, Vifm crashes. The resulting notice from windows states only that "the application stopped working", so I can't get more info. I'm running the binary downloaded from the web site.

#Windows #ConEmu

**Comment by xaizek** [comment]
Doesn't crash every single time for me, but I do get a crash after several tries. Thanks for the report.

**Comment by xaizek** [comment]
The bug is in a library, so if you're using (or don't mind using it) `vifm-w32-0.10-binary.zip`, you can take the [attached file](https://github.com/vifm/vifm/files/2870459/pdcurses.dll.zip) and copy it over in the directory of installation. After that crashes, should be gone.

Or you could use other binaries, but they include the rest of changes since v0.10: [32-bit][32bits], [64-bit][64bits].

[32bits]: https://builds.vifm.info/builds/vifm-w32-se-v0.10-123-gf505e12f73c6.exe
[64bits]: https://builds.vifm.info/builds/vifm-w64-se-v0.10-123-gf505e12f73c6.exe

**Comment by Numeromancer** [comment]
Great! Your skills and your courtesy are high quality.  Vifm is great, and up with my top five favorite programs.
