### ISSUE TITLE
filetype and directory patterns

### ISSUE THREAD

**Issue by afsheenb** [vifm/vifm#406]
I'm able to associate a command with a filetype using wildcards:

```
filetype *.pdf evince %f
```

But I don't seem to be able to get directory matching working. I'd like to associate certain programs only with files in a certain directory, e.g. "if directory is /home/user/Books, use evince to open the file, regardless of extension".

So far I've tried (using the sample logic above as an example):

```
filetype ///home/user/Books// evince %f
filetype *.[Books]/ evince %f
filetype *Books* evince %f
```

I have a feeling I'm missing something obvious about how filetypes and patterns interact, but it's I'm stumped as to what. Any suggestions?

Cheers,

--afsheen

**Comment by afsheenb** [comment]
(For background: ideally I'd like to associate files with .pdf extension in different directories with different programs.)

**Comment by xaizek** [comment]
`//...//`-patterns define path regular expressions, they get complete absolute path of the file to match against. If you want to match files in a single directory and not in its subdirectories, your command should look like this:
```
filextype //^/home/user/Books/[^/]*\.pdf$// evince %f
```
Note that `{{...}}` won't do in this case because `*` will match `/` as well, just like `.*` in regular expressions, that's why there is `[^/]` to stay in one directory. The expression can also match  by part of the path, so `^` and `$` might be needed.

**Comment by afsheenb** [comment]
Thanks for the quick response! That explains what I was mis-understanding about patterns. Unfortunately the above example doesn't work. As a test I've tried adding:

`filextype //^/home/user/Books/[^/]*\.pdf$// evince %f`

(with the keyword `user` changed to my username, and otherwise left intact) - no change.

To make sure I'm not running into any other issues, I've tried changing it to

`filetype *.pdf evince %f`

just to confirm that matching works, and it does.

Version information if it's any help:

```~ ❯❯❯ vifm -v
Version: 0.7.8
Git commit hash: 
Compiled at: Feb  7 2016 13:44:37

Support of extended keys is on
Parsing of .desktop files is enabled
Without GTK+ library
With magic library
With X11 library
Without dynamic loading of X11 library
With file program
With -n option for cp and mv
Without remote command execution```

**Comment by xaizek** [comment]
> Version: 0.7.8

`//...//` patterns were added in the next version which is `0.8`, that's why they don't work.

You either need a newer version ([building](https://wiki.vifm.info/index.php/Obtaining_Vifm#From_sources) with `--sysconfdir=/etc --prefix=/usr` and just making binary available in the `$PATH` should do) or a helper script which you would call like:
```
filetype *.pdf run-pdf %d %f
```
It then could run different applications depending on the first argument.

**Comment by afsheenb** [comment]
Ah ok, thanks! And apologies, I should have suspected versioning issues. I've installed an updated version and all is working as expected now. Cheers!
