### ISSUE TITLE
move loses ignored files

### ISSUE THREAD

**Issue by zsugabubus** [vifm/vifm#408]
I learned it in the hard way that ignoring errors during move could have unexpected consequences: Files will be lost.

**Steps to reproduce:**
 1. Create directory `blackmagic` with a single file in it, named `canuseeme?`.
 2. Move it to an exFAT FS. (`?` is an illegal character, so can't create the file.)
 3. Ignore that error and take a last glimpse to the file before its particles vanishes in the cosmos.
 4. Cry.

**Relevant vifmrc:**
```
set syscalls
set notrash " :(
```

Maybe not deleting non-empty directories could be a solution.

**Comment by xaizek** [comment]
Thanks for the report and sorry to hear that some data was lost. I believe this is the second such reported case, although there was one more bug where data had a copy and #391 isn't confirmed (@aleksejrs, could this be the same issue as yours?).

> 4. Cry.

Stopping using the mount and using data recovery tools would be a better suggestion.

> ```set notrash " :(```

`set trash` would make no difference, because deletion as part of a move is not the same as just a deletion.

> Maybe not deleting non-empty directories could be a solution.

When moving across mounts original files aren't touched until move is over, so this check wouldn't work. This way stopping the operation at some point won't mess up the source in any way. With there being no way to ignore errors, this guaranteed preservation of data. Then things changed and this wasn't revised. It probably should just avoid deleting original files if there were any errors, this is how it works for `set nosyscalls`.

**Comment by zsugabubus** [comment]
> Stopping using the mount and using data recovery tools would be a better suggestion.

I moved from `tmpfs`, so I guess pages were instantly freed. But never mind, at the end of the day I'm glad it happened to me and not with somebody else with way more important files.

> It probably should just avoid deleting original files if there were any errors

Yeah, then skipped files could be listed with `:compare`.
