### ISSUE TITLE
Size unit in the viewcolumns

### ISSUE THREAD

**Issue by laggardkernel** [vifm/vifm#410]
I wanna display size with the `set viewcolumns=-{root},-5{ext},9{size},16{mtime},12{perms}`. The problem is only the size numbers displayed. Can I make the unit displayed as well? It seems this couldn't be controlled by `sizefmt`.

**Comment by xaizek** [comment]
Please provide output of:
```vim
:set iec? sizefmt?
```
Nine character positions should be enough to display both value and units. Moreover the column is right aligned, so you shouldn't be able to see numbers without units.

**Comment by laggardkernel** [comment]
```
:set iec?
noiec

set sizefmt?
sizefmt=units:iec 
```

Setting `:set iec` makes me get the units. After some testing, I found that enlarging `16{mtime}` to `18{mtime}` solves my problem. I still don't understand why the `mtime` covers the size units. My sizefmt is `set timefmt=%Y/%m/%d\ %H:%M`, whose length should be 16. Right?

**Comment by xaizek** [comment]
That's 16 which leaves no space between columns, so you want to specify 17.

And the reason why vifm hides one character of the size column is because space is added implicitly when time is formatted (see #335). It won't be there with cropping:

```vim
set viewcolumns=-{root},-5{ext},9{size},16{mtime}.,12{perms}
"                                                ^
```

I'll better drop that space as it only causes confusion.
