### ISSUE TITLE
<c-f> and <c-b>: won't scroll when items less than one full page

### ISSUE THREAD

**Issue by randomizedthinking** [vifm/vifm#417]
I use vifm and really like it. Here is one small item regarding the scrolling in vifm: when in a normal panel, if the items are less than one page, then `<c-f>` and `<c-b>` won't scroll the page. On the other hand, `<c-u>` and `<c-d>` would do even if it is less than half a page.

In vim, `<c-f>` and `<c-b>` would scroll a page even less than one page. For instance, if keep pressing `<c-f>`, we will move to the end of the file. It is reasonable in my view, and would be great if vifm can have it too.

Thanks.

**Comment by xaizek** [comment]
> In vim, `<c-f>` and `<c-b>` would scroll a page even less than one page.

`<c-b>` in vim does nothing for me when window is scrolled to the top. vifm does the same.

`<c-f>` in vim scrolls window hiding the lines which otherwise would fit on the screen. vifm always shows as many files as possible, that's why `<c-f>` does nothing when all files are visible.

Current implementation seems to follow vim. Maybe there could be an option to enable alternative behaviour (would probably control menus as well, as they work the same way).

**Comment by randomizedthinking** [comment]
You are right ... I didn't realize that the behavior of `<c-f>` and `<c-b>` are not symmetric in vim.

Given this is the case, I will redefine `<c-f>` to `<c-d><c-d>` then. Thanks.
