### ISSUE TITLE
Improve media menu

### ISSUE THREAD

**Issue by zsugabubus** [vifm/vifm#440]
Currently, I use `udiskie` for removable device automounting and I made a bookmark to `/run/media/USER` and `:UUmount`/`:UDetach` commands for convenient unmounting. It Just Works™, however I have no (simple) solution for encrypted disk unlocking because master password is requested via `pinentry-curses`.

Vifm's `:media` menu is nice, however...
* (no support for `udisks2` out of box),
* no keybinding(s) for quickly navigating between devices,
* mounting command is spawned as a background process, so I still cannot get a tty for password retrieval,
* no detaching/device power-off command (I think it's useful),
* ...automounting is sometimes irritating.

I would happily make a pull request, if you think it would be a reasonable improvement.

**Comment by xaizek** [comment]
> (no support for udisks2 out of box)

There is now: a728ab4ebc5935f921d40d9c51560bf3eef766ec.

> no keybinding(s) for quickly navigating between devices,

I was thinking of adding them, but decided that `/^\w` and search in general might be enough.

> mounting command is spawned as a background process, so I still cannot get a tty for password retrieval,

You could use a custom pinentry, that spawns graphical one when terminal isn't available. But making mounting foreground (maybe optionally) would also be useful for such cases (graphics might not be available).

> no detaching/device power-off command (I think it's useful),

Never used such commands, but you're probably right.

> ...automounting is sometimes irritating.

What automounting?

> I would happily make a pull request, if you think it would be a reasonable improvement.

I rarely use removable media and added the menu largely due to requests, you seem to be using removable media much more than I do and improvements you suggest based on your experience seem reasonable.

**Comment by zsugabubus** [comment]
> You could use a custom pinentry, that spawns graphical

I know, but that is not really an option for me.

> What automounting?

What `udiskie` does. I would better stay with explicit mounting if I could choose.

> you seem to be using removable media much more

Not too much..., but if I mount some encrypted disks it takes a way longer than my acceptable upper limit and if I could do better with Vifm, why not?!

**Comment by zsugabubus** [comment]
I would like to ask your opinion. After a bit of thinking, I can imagine the following outcomes:
* make media menu smarter by creating a new "script menu".
  It does nothing more than, executes a given script, prints out the output lines and than you can take actions on them. Calling `script` without arguments returns the title of the menu and `key:action` pairs; `script list` returns  `data:line`s; `script {action} {data}` executes action on the line identified by `data`.
  **Pros:** custom everything.
  **Cons:** this functionality in general (selecting lines and take actions), is absolutely out of scope of a file manager. On the other side, (un)mounting is a good to have feature, and current implementation has some limitations so this "script menu" would offer a nice generalization of it, instead of writing specialized code only for media menu.
* completely remove media menu, because it's out of the scope and redundant (user can start shell with her custom mounter program with a single keystroke),
* keep it as is, and everybody (including me) who needs more functionality, goes and writes a custom script.

**Comment by xaizek** [comment]
>> What automounting?
>
> What udiskie does.

Looks like you can do `udiskie --no-automount`.

> After a bit of thinking, I can imagine the following outcomes:

The reason managing media was implemented in this way is that there is no other way that's flexible enough to accommodate various systems, so the external script is meant to be customizable by users and `vifm-media` is for cases when it's just enough.

I don't think removing it is an option. It adds some convenience, even if it doesn't cover all possible cases. I also dislike incompatible changes.

Replacing it with a more generic "script menu" also doesn't seem to work. If you are already inside a mount, `:media` will setup cursor on it and leave the directory before trying to unmount to make the unmounting possible. The latter is quite necessary and "script menu" probably won't allow for it. So "script menu" could be an extension/alternative, but not really a replacement.

And what happened to the initial option of adding missing things to the existing `:media` menu?

**Comment by zsugabubus** [comment]
> Looks like you can do udiskie --no-automount.

I know about it, but than I have to do *every* mounting manually (I have no script for it currently). I just wanted to explain that if I can use Vifm's media menu, I don't care about automounting anymore in the future.

> external script is meant to be customizable by users

Device and label isn't treated specially anywhere inside Vifm, so if you want filesystem type or free/total space (or for example last backup date to give a special example) to be printed, you start hacking `label=` or `device=`, but it well print in the fixed format "device [label]", so I ended up by it would be simpler to use just a single `header=`.
(I don't even like empty lines because if I will have several mounts I can't approximate lines to be jumped up/downwards and I will quickly need two-digit count prefixes (two shift keys + two number keys for me) + they unnecessary.)

> And what happened to the initial option of adding missing things to the existing :media menu?

I just started typing the first character of device eject code, than I realized that it will need disk devices (`/dev/sdb`) not partition devices (`/dev/sdb3`) (not sure about naming). Now, I had two choices: extend the script to emit disk devices, so user can eject these explicitly; or allow ejecting partition devices by finding the right disk device, but *I think* it would not be a good choice, because it would result in ejecting every partition of a disk (potentially visually far away from each other) that maybe against the intentions of the user (visually not clear). So a tree view would be an obvious solution, but mount points enumerated in separate lines after devices (+ intermediate blank lines) tear apart this visually. Maybe it could be improved somewhat, but it would require a new format anyway, so at this point it seemed simpler to let the script to do more (^2) and use a new "script menu".

2 For example Vifm checks if data starts with `m` or `u` before sends `(un)mount` commands to script, but script could fail silently in this cases; or could (un)mount devices if you are on device itself not on the `not mounted` line (it's easily fixable thought).

> If you are already inside a mount, :media will setup cursor on it and leave the directory before trying to unmount to make the unmounting possible

Chdir to `/` before enter and chdir back to the original directory before return. It's possible, isn't?

**Comment by xaizek** [comment]
> simpler to use just a single `header=`

This way formatting would be embedded into the script, which supposed to be just an adapter for managing media. A better way would be to add more fields (maybe catch all one like `info=`, which would overwrite description of the partition if present).

> Device and label isn't treated specially anywhere inside Vifm

Device is needed for implementing "unmount-device" in the future if necessary, that is to unmount all mount points of a partition in one go.

> I don't even like empty lines

They make menu fill vertical space better and make the list more readable. Maybe they could be made optional in some way.

> Chdir to `/` before enter and chdir back to the original directory before return. It's possible, isn't?

Sure, but this is a bit awkward to do for a generic "script menu". If someone's script depends on current directory, it would need to be communicated in some other way.

> As I guess current implementation just chdirs out of the current view one level,

No, it goes to the parent directory of the mount point.

> but user could have several tabs, several panes opened inside directory to be unmounted. These cases aren't handled.

They don't need to be handled explicitly.  Those views don't hold any descriptors to directory they are in and will detect the change when they become visible.

> I just started typing the first character of device eject code, than I realized that it will need disk devices 

Yes, this would need to be handled differently. Maybe by displaying devices apart from partitions. Tree seems too complicated for this hierarchy.

> Plus: I came up with the backup example previously, so it would be also a good thing if user could start backup with a single keystroke on a selected device from media menu.

This might be cramming too much in it. Although, it's still possible to add some sort of actions.

> After all, I happily go with the existing media menu, but generalizing it just seemed a nicer solution.

If you make it too custom, then it won't be possible to have any assumptions about it (not necessary now, though). I like the idea of "script menu" (modulo its likely issues with spaces), but in this case integration seems to be beneficial in some ways because views have loose relation to mounts and you can have custom bindings. Running external commands on menu items would be useful in other menus and it was brought up a couple of times.

**Comment by zsugabubus** [comment]
> If someone's script depends on current directory, it would need to be communicated in some other way.

Working directory of started process can be changed. It can't be a problem.

> Maybe by displaying devices apart from partitions. Tree seems too complicated for this hierarchy.

But hierarchy is important. I would like to know what mount point will disappear if I power off a device. I can't imagine other structure than tree otherwise dependencies won't be clear.

> This might be cramming too much in it. Although, it's still possible to add some sort of actions.

Actions completely controlled by user. If she doesn't want some functions, she modifies her script. It also has the advantage that keybindings can be customized too. I don't understand your point.

> integration seems to be beneficial in some ways

Do you mean integrating mounts just like "file views"? I think it would be the best solution, although I just slightly looked into the code of views, but it seemed very specialized. I don't see how it could be extended to handle new columns. (*)

> This way formatting would be embedded into the script, which supposed to be just an adapter for managing media. A better way would be to add more fields

What's your issue with formatting embedded into the script? So this way you customize it as you want. If you want columns, you generate columns. If you want blank lines, you print blank lines. I don't think adding more fields would be solution since you can't sort or do anything relevant with them (because of (*)).

**Comment by xaizek** [comment]
> Working directory of started process can be changed. It can't be a problem.

Yes, but it's an inconvenience. The script would get wrong working directory by default.

> I don't understand your point.

I meant that adding something like `action=` seems possible.

> Do you mean integrating mounts just like "file views"?

No, I just meant that changes to mounts affect file views. As opposed to things like `:grep` menu.

> What's your issue with formatting embedded into the script? So this way you customize it as you want. If you want columns, you generate columns. If you want blank lines, you print blank lines.

It makes it impossible to reuse the script for anything other than the menu without providing a separate machine interface. I wouldn't add it if there was a cross-platform library for managing media. It serves as its replacement. If formatting is embedded, it just becomes a backend of the menu rather than an interface for managing media.

I don't have a case for it at the moment in vifm, but it's just a matter of separation of concerns. Mixing them is like using `ls` in a bash script to iterate over files just to work around its issues. Spaces in labels and paths don't matter for formatting, but what to do for processing? Adding some escaping and a parser that can handle it?

**Comment by zsugabubus** [comment]
I've understood your point of view. My intention with my scripts were really just to be backends of menus.

Now, I would like to approach the issue from a different way, but keeping the concept of `vifm-media`–a thin layer between Vifm and user preferred (un)mounting etc system commands. Vifm could get block devices without any external program, `vifm-media` is just really needed if user has some mechanism for device mounting for unprivileged users.
Because menus aren't shine at easy customizability and displaying complex, structured things like columns, what do you think about a new kind of view? This way hard-coded keybindings and actions could be avoided, instead user could use `:map` and e.g. `function`... etc. I don't know how much work it means, but smartening media menu has its limitations for sure.

**Comment by xaizek** [comment]
> Vifm could get block devices (and details about them) without any external program

Not sure about that, I suspect this is very OS-specific. Especially to determine things like whether certain device is removable one. `:media`-menu is for removable things, not for generic management of mountable stuff.

> what do you think about a new kind of view?

It's more complicated than menus... This would need submodes for key bindings, which aren't implemented (known use case is bindings specific to custom views). And things aren't implemented in an extensible manner there, you can't just add a new kind of view.

> smartening media menu has its limitations for sure.

Well, yeah. And you're trying to make it do everything :) I guess you would be satisfied if menus would be completely reprogrammable with something like Lua :)

**Comment by zsugabubus** [comment]
Bad news.
