### ISSUE TITLE
View mode crash with bat %c %q and shellcmdflag=-ic

### ISSUE THREAD

**Issue by mimame** [vifm/vifm#471]
Hi

Perhaps it's my fault but I can't use bat for the view mode any more with shellcmdflag enabled 

Steps to reproduce the crash:
1. vifm --no-configs
1. :set shellcmdflag=-ic
1. :!bat %c %q

Full backtrace: [vifm-minimum-crash-bat.txt](https://github.com/vifm/vifm/files/3563554/vifm-minimum-crash-bat.txt)

Thanks so much for all the attention and support

**Comment by mimame** [comment]
I think the interactive shell flag is not working fine with commands finished with & to run in background

**Comment by xaizek** [comment]
Hi,

thanks for the report. The backtrace shows that libncurses is crashing. It apparently fails to deal with terminal state. I tried it with `:!cat %c %q`, which hangs instead of crashing. I wanted to allow using aliases in commands with `%q`, but not sure it's going to work, maybe `-i` shouldn't affect it.

> I think the interactive shell flag is not working fine with commands finished with & to run in background

Yeah, looks like they aren't being executed...

**Comment by xaizek** [comment]
Looks like using interactive shell non-interactively is just a bad idea in general.  Issues with ` &` is due to shell wanting to control the terminal and being automatically stopped:
```
[~]$ bash -ic 'echo hi > ~/bla' &
[1] 29050

[1]+  Stopped                 bash -ic 'echo hi > ~/bla'
```
It works if detached from the terminal:
```
[~]$ setsid bash -ic 'echo hi > ~/bla' &
[1] 29000
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
```
But then you get weird error messages.  In preview this also breaks cancellation on <kbd>Ctrl-C</kbd>.

This might not be fixable. Better make a wrapper that starts shell with aliases/functions available and use it for `'shell'`.

**Comment by xaizek** [comment]
The effect of #481 seems to be that previewing issue is fixed (all viewers are now run via `setsid` equivalent).

#631 has also given me an idea that you might want to use `-l` flag instead of `-i` provided that your profile configuration sources your functions and aliases. With `shellcmdflag=-lc` `v0.11` works fine while it fails with `shellcmdflag=-ic`. Using `-l` also fixes running external commands in background. I tested this with `bash`, but it should be similar with other shells.

Actually... even `-i` won't break background jobs if they are run after `setsid()` call. I guess there is no reason to not do `setsid()` now, so it might be that `-i` will work fine.

**Comment by mimame** [comment]
Thanks so much @xaizek I will use with `shellcmdflag=-lc` in `v0.11` which is working fine for zsh too
Should I close the issue?

**Comment by xaizek** [comment]
Thanks for confirming that it works for you too. I think this can be closed, so I did it.
