### ISSUE TITLE
[FR] "Press return to continue" - also accept Escape

### ISSUE THREAD

**Issue by laur89** [vifm/vifm#472]
It would offer a nice UX if printed error messages could be exited with `Esc` in addition to Return; perhaps also `q`?

**Comment by xaizek** [comment]
Doesn't it already work? It says "Enter" as it's treated specially, but <kbd>Esc</kbd> doesn't need special handling. Not sure about <kbd>q</kbd>, it would standout among other commands then.

**Comment by laur89** [comment]
> Doesn't it already work?
Nope, `Esc` does nothing.

**Comment by xaizek** [comment]
> `Esc` does nothing.

Works fine for me. What version are you using?

**Comment by laur89** [comment]
`0.10.1`, installed from debian repos (pkg ver 0.10.1-3).

**Comment by xaizek** [comment]
My bad, I was thinking about "Press ENTER or type command to continue" message on the status bar, while you're talking about error dialogs.

It was mentioned before, but I was reluctant to make the change, because it makes errors easier to ignore. Maybe this needs some kind of a flag, because I think I caught myself repeating failed actions automatically ignoring the dialog and might have even pressed <kbd>Esc</kbd> in between in an attempt to reset input sequence.
