### ISSUE TITLE
Failing to rename should not discard all changes

### ISSUE THREAD

**Issue by jose1711** [vifm/vifm#496]
Currently if a user makes a mistake while renaming and creates a conflict for a single file all the changes are discarded and (s)he must start-over. It would be nice if `vifm` offers a way to correct the error in a more friendly manner.

**Comment by xaizek** [comment]
Are you talking about renaming multiple files using `:rename`?

**Comment by jose1711** [comment]
Correct. Although even a renaming of a single file can be annoying if the name is long.

**Comment by dmlemos** [comment]
I'd appreciate at least an option to control this. When renaming multiple files, sometimes I use complex substitutions, depending on the situation, but when it fails it means I have to go back and construct the same thing again.

**Comment by xaizek** [comment]
It's not implemented not because it's not generally useful, but because it's not clear how to detect that you repeat a failed operation.

Just check set of files in the same order after an error and assume re-edit is what user wants? But now you don't have an option to repeat the operation from scratch. In Vim there will be a small inconvenience that you won't see original file names, but it's a minor thing if you can start from scratch.

**Comment by dmlemos** [comment]
Re-edit is a good option. Can you clarify, how would one know what renaming caused the error in the first place, since the original file names won't be visible in vim?

**Comment by xaizek** [comment]
Only from the error message when the operation fails (in addition to renaming it can also be `:move?`, `:copy?`, etc.).

Another possibility is to change format to something like (needs special treatment for leading `#`):
```
# original name 1
new name 1
# original name 2
new name 2
```
This allows adding comments about last error as well as preserves original file name. However, this format makes it harder to do something like block editing. Or maybe comments should be added only for re-edit, since by that time user has already made most of the editing.

**Comment by dmlemos** [comment]
> Only from the error message when the operation fails (in addition to renaming it can also be `:move?`, `:copy?`, etc.).
> 
Any error that occurs from file operations in general would benefit from a re-edit with your suggestion below 👍🏽

> Another possibility is to change format to something like (needs special treatment for leading `#`):
> 
> ```
> # original name 1
> new name 1
> # original name 2
> new name 2
> ```
> 
> This allows adding comments about last error as well as preserves original file name. However, this format makes it harder to do something like block editing. Or maybe comments should be added only for re-edit, since by that time user has already made most of the editing.

That's an interesting idea. It reminds me of the git commit editmsg. In the same thought, the change format would work better if it were all in a block at the beginning of the file. Now the information is there, but without blocking further editing.

**Comment by jose1711** [comment]
Thank you, so the way this works is.. select couple files, `:rename`, receive error. For a fix: `gv`, `:rename` - make the adjustments. Is that correct?

**Comment by xaizek** [comment]
Yes, you get edited list if you repeat an operation with the same set of files in the same order (how they are selected is irrelevant).

**Comment by jose1711** [comment]
Thank you, any chance to make `vifm` prompt user on failure? E. g.: `Error: error description, fix and repeat action? [Y/n]?`

**Comment by xaizek** [comment]
Doesn't make the code easier, but looks like the prompt can be added without much changes.

**Comment by dmlemos** [comment]
Is there a flag that needs to be changed? I've encountered this issue today. There is an error saying the file exists, but nothing else shows to edit the rename.

**Comment by xaizek** [comment]
Should work out of the box. How were you renaming?

**Comment by dmlemos** [comment]
I was using either `:rename` or `cw`

**Comment by xaizek** [comment]
Make sure you're using the latest version. And you edited file names in Vim?

**Comment by dmlemos** [comment]
I'm using 0.11 which is the latest, however I don't think it has the latest changes. Would you be able to issue a new release?

**Comment by xaizek** [comment]
Right, I meant `master`-latest. I wasn't going to make a release yet. Maybe you could [build from sources](https://wiki.vifm.info/index.php/Obtaining_Vifm#From_sources).

**Comment by dmlemos** [comment]
> Right, I meant `master`-latest. I wasn't going to make a release yet. Maybe you could [build from sources](https://wiki.vifm.info/index.php/Obtaining_Vifm#From_sources).

Done now. This feature makes the renaming a pleasure.

I have a few suggestions to improve it further, let me know if I should create new issues:
* When renaming files that already exist, I want to delete them as they are duplicates for 99% of the cases. For that reason, perhaps deleting the line would delete the file entirely?
* Report all rename conflicts at once. Right now, I have to do it one by one, which is time consuming.
* Allow some default option, e.g. all files with conflicts start with a prefix '_' so that they can be at the top. I noticed with a big batch of renames, it is also time consuming to scroll down and _take care_ of each one of them.
