### ISSUE TITLE
How to donate

### ISSUE THREAD

**Issue by Naegolus** [vifm/vifm#509]
Didn't find a donate button.

Since this is the most useful tool on my machine and because I use it EVERY single day I would like to give you something back.

**Comment by jubalh** [comment]
Some ideas for @xaizek: GitHub Sponsors, Patreon, Librepay, PayPal.. :)

**Comment by xaizek** [comment]
Appreciate your desire to donate, but there isn't a way at the moment. There was a PayPal account for that, but it got blocked due to me not being able to match account and password correctly in several tries (mixed my e-mails and passwords). I'll comment here if I setup an alternative or restore it.

**Comment by XVilka** [comment]
There are two options available:
- Setup an [OpenCollective](https://opencollective.com) account - fiat only.
- Or use [donate.go](https://github.com/jollheef/donate) for setting "bounties" for the issues - but only crypto for now.

**Comment by xaizek** [comment]
donate.go isn't really a good fit, it's more of a task-based reward system (its name isn't a good fit either, "reward" would be more on point).

I think I'd prefer Liberapay over OpenCollective, even though they have a crutch for non-recurring donations (make a recurring donation once and disable it).

**Comment by Naegolus** [comment]
> Appreciate your desire to donate, but there isn't a way at the moment. There was a PayPal account for that, but it got blocked due to me not being able to match account and password correctly in several tries (mixed my e-mails and passwords). I'll comment here if I setup an alternative or restore it.

k

**Comment by XVilka** [comment]
By the way, one more way is available since my last message - setup GitHub Sponsors. For example, Neovim and Zig language use it:
- https://github.com/sponsors/neovim
- https://github.com/sponsors/ziglang

**Comment by jubalh** [comment]
@XVilka has been mentioned in https://github.com/vifm/vifm/issues/509#issuecomment-576055075 already.

**Comment by xaizek** [comment]
Brought back "Donations" section on the site and enabled "Sponsor" button here.  It's just a BTC address though (because it works).

**Comment by xaizek** [comment]
Thanks to @TornaxO7 poking at me, GitHub Sponsors is [enabled for Vifm](https://github.com/sponsors/vifm) after all. [OpenCollective](https://opencollective.com/vifm) is enabled now too (although barely setup at the moment), because that's a way to make GitHub Sponsors work for countries that GitHub doesn't support directly.

**Comment by Naegolus** [comment]
Sorry took way too long. Didn't recognize the progress in this issue .. Done

**Comment by xaizek** [comment]
Thanks :)

**Comment by RayZ0rr** [comment]
Just to clarify, what is the preferred way?

1) Github sponsor?
2) [OpenCollective](https://opencollective.com/vifm)
3) Paypal? (did you manage to get it working?)

**Comment by xaizek** [comment]
Github Sponsor, I guess. It redirects to OpenCollective, so the first two options are basically the same, but donation will be visible on GitHub with the first one.

PayPal has finally come to my country, but I don't think I'll be able to restore my old accounts due to the changes in password recovery process while I was locked out of them, so I'm not sure I want to use it.
