### ISSUE TITLE
How to empty trash on all file systems?

### ISSUE THREAD

**Issue by therealmaxmoon** [vifm/vifm#512]
I deleted a lot of files on an external disk, but the free disk space was the same like before. I figured out, that vifm is creating a trash directory on every partition. 

It would be somehow nice to have a trash-empty function, which can be triggert by a key or by exiting vifm.

... or is there another way, which should be used?

**Comment by xaizek** [comment]
There is [`:empty` command](https://vifm.info/vimdoc.shtml#vifm-%3Aempty).

**Comment by therealmaxmoon** [comment]
It works really good as a shortcut (e.g. F9 key):
`nnoremap <f9> :empty<cr>`
But I am not a fan of non response tasks, because there is no clue if f9 worked or not. Is it possible to get a message, if the emptying the trash was successful or failed or get just a simple message in the status line? I tried echo, but it doesn't work. I don't even get a message in the status 
`nnoremap <f9> :!echo 'TESTING STUFF'<cr>`

**Comment by xaizek** [comment]
`:empty` doesn't really fail.  If there is nothing or very little to you, you won't notice anything, otherwise there should be an additional bar at the bottom of the screen showing that emptying is happening:

![vifm-job-bar](https://user-images.githubusercontent.com/459736/75081497-0b934b80-5518-11ea-9e67-c8e1d505ebb8.gif)

For showing a message you can either do
```vim
nnoremap <f9> :empty | !echo 'TESTING STUFF' %S<cr>
```
or
```vim
nnoremap <f9> :empty | echo 'TESTING STUFF'<cr>
```
The second is better as there is no need for external process here.
