### ISSUE TITLE
trash-cli integration

### ISSUE THREAD

**Issue by mb720** [vifm/vifm#513]
Hi!

I use [`trash-cli`](https://github.com/andreafrancia/trash-cli) which means I have two trash directories: `~/.local/share/Trash` and `/home/mb/.local/share/vifm`.

I was wondering if there's a way to unify this, maybe via configuring Vifm.

I'm aware of `set trash` but I'm not sure I want to change this given the comments from the default `vifmrc`:

    " Trash Directory
    " The default is to move files that are deleted with dd or :d to
    " the trash directory.  If you change this you will not be able to move
    " files by deleting them and then using p to put the file in the new location.
    " I recommend not changing this until you are familiar with vifm.
    " This probably shouldn't be an option.
    set trash

Thanks!

**Comment by xaizek** [comment]
Hello!

> I was wondering if there's a way to unify this, maybe via configuring Vifm.

Not really and I'm not sure it makes much sense. If it was used only as a trash directory, then why not, but since it's also a temporary buffer for moving files... The semantics of freedesktop's trash and vifm's trash differ and mixing those feels weird, to me at least.

Don't mind the comment from `vifmrc` if you didn't disable confirmation on deletion. Then it should be fine.
