### ISSUE TITLE
freeze while copying (other windows as well)

### ISSUE THREAD

**Issue by mb720** [vifm/vifm#518]
Hi!

I'm not sure if this is a Vifm bug: I was copying a few hundred GiB of data from one external drive to another. I noticed when Vifm reported 15% copy progress, that not only Vifm but my entire window manager (Sway) became unresponsive, I couldn't interact with any windows.

I gave up waiting, and tried the ["Raising skinny elephants is utterly boring"](https://en.wikipedia.org/wiki/Magic_SysRq_key#Uses) trick. Later in `journalctl`, I could see that it performed emergency syncs, but no error messages were logged.

I know this is little to go by, but do you have any tips how to debug this. Also, has this happened to anyone else in the past?

Thanks

**Comment by xaizek** [comment]
Hi!

Basically the kernel cached data that Vifm was writing to disk in memory, at the same time pushing other things out. Eventually it ran out of memory to use for caching and started writing data to disk, but because data of applications got pushed out they had to wait for disk to get it back, which degraded performance of the whole system to performance of the disk.

There is no error in here, it's a side effect of caching, which might not show up depending on settings.

However, Vifm can account for this by forcing synchronization to disk during copying (`fdatasync()`), the copying will happen longer, but the system as a whole shouldn't be affected by copying. I'll need to find out how to do this properly (from other file managers maybe), wasn't sure it's needed as I didn't see such effect, although knew it's possible.

**Comment by mb720** [comment]
Thanks for your insights!
This sounds to me that this issue should be reproducible given the same amount of RAM and a file large enough.

**Comment by xaizek** [comment]
I think there are more conditions. It depends on how write-back caching is configured for sure. And on how much free memory you have at the moment of copying. I also remember it being mentioned specifically with regard to external drives, maybe that's the reason why copying file larger than my RAM from one drive to another doesn't really affect the system too much.

I got more significantly degraded performance with these sort of extreme settings (stopped the copying before system halted), so it seems to be testable:
```terminal
# sysctl vm.dirty_background_ratio=90 vm.dirty_ratio=90
```
