### ISSUE TITLE
Build fails with new GCC 10

### ISSUE THREAD

**Issue by tim77** [vifm/vifm#534]
Hello. This is common GCC 10 bug
https://gcc.gnu.org/gcc-10/porting_to.html#common

Full [build log](https://gist.githubusercontent.com/tim77/ea2238852bd3b1951763d56f39e10861/raw/149e61083ae580d7d52db6341159175b9260f95e/vifm%2520gcc-10).

**Comment by xaizek** [comment]
Hi. It fails for 0.10.1, but should work on current master (see 0205c8d76bd33228b33bcceb6afffa2a77925c76). Do you need to compile 0.10.1 using GCC 10? It shouldn't be hard to make a patch based on that commit (I don't think it will work as is, there were a couple of variable renames).

**Comment by tim77** [comment]
> Do you need to compile 0.10.1 using GCC 10?

I already workarounded it and built so this is not critical probably.

> It shouldn't be hard to make a patch based on that commit (I don't think it will work as is, there were a couple of variable renames).

Yeah, l'll try to find time for testing this and leave feedback.

Thanks a lot for quick feedback and fix.

**Comment by marv** [comment]
I would be great to have a release with GCC 10 compatibility, so distros don't have to backport those fixes - are there plans to cut a new release soon?

**Comment by xaizek** [comment]
Specifying `CFLAGS=-fcommon` for `./configure` should be enough to build vifm with GCC 10 or any other software, so this doesn't seem to be a problem for packaging.

**Comment by marv** [comment]
Well, that depends how you look at it I suppose. All downstream projects that want to ship vifm to people need to add that workaround to their build files in order to make it work with GCC10. And get rid of it again once vifm builds with GCC10 out-of-the-box. Bumping a package to a new version is a common and straightforward task (usually just a simple rename) and the first thing I do when the current version of a package we ship has problems is to check if there's a new version available which fixes it. So this issue might not have been opened in the first place if there was a release with the fix for GCC10

**Comment by xaizek** [comment]
That's what happens if compiler changes defaults. I don't think that making releases to keep up with brand new compilers is a good strategy. I agree that it might be simpler for packaging, but it's also a weird reason for a release.

> And get rid of it again

Nothing bad happens if `-fcommon` remains, so in this case only one change is required.
