### ISSUE TITLE
'Redirection is not supported' message in 'Git Bash'

### ISSUE THREAD

**Issue by bataliero** [vifm/vifm#543]
Hi,
I have Git Bash (mintty) for Windows 10 and tried to run vifm but it doesn't work unfortunately.
```
$ vifm

Redirection is not supported.
```
Message as outlined above is displayed and vifm is not started.

My vifm is installed by **choco**:
```
Version: 0.10.1
Git info: v0.10.1-0-g546be4ebeff7
Compiled at: Jul 29 2019 16:35:50

Support of extended keys is on
Parsing of .desktop files is disabled
Without GTK+ library
Without magic library
Without X11 library
Without dynamic loading of X11 library
Without file program
With remote command execution
```

```
mintty --version
mintty 3.1.0 (x86_64-pc-msys)
© 2013/2019 Andy Koppe / Thomas Wolff
License GPLv3+: GNU GPL version 3 or later
There is no warranty, to the extent permitted by law.
```

Is there a solution for that? 
Thanks!

**Comment by xaizek** [comment]
Hello,

you're trying to run a Windows-console application in a Cygwin terminal emulator. That's why it doesn't work.

Execute vifm on its own or run it from `cmd.exe`/ConEmu/other terminal that provides Windows-console to the application. `bash` that comes with Git can also be used outside `mintty` (just start it outside of `mintty`) where vifm will be able to work.

Alternatively, vifm can probably be built for Cygwin (haven't done this for a while, but it used to work), which will make it runnable in `mintty` (but probably not outside of it).
