### ISSUE TITLE
Vifm can't spawn subshell in PowerShell

### ISSUE THREAD

**Issue by peromage** [vifm/vifm#556]
Vifm is really an ideal terminal file manager and I enjoy using it as my daily manager.

## Background

Most of time I work in Windows environment and PowerShell is my working shell. To reduce some efforts on configuring shell environment I cloned my pwsh configuration in Linux VM and use it there as well. However, there is a little glitch that prevent me from opening shell inside of Vifm if it's running in PowerShell.

## Environment

- Powershell: 7.0.1/5.1.18362.145
- Vifm: 0.10.1

Following environment variables are set:
```powershell
$Env:SHELL = "pwsh"
# Also tried
# $Env:SHELL = "c:\Program Files\PowerShell\7\pwsh.exe"

$Env:EDITOR = "nvim"
# Also tried
# $Env:EDITOR = "c:\Program Files\NeoVim\bin\nvim.exe"
```

Vifm configurations
```vifm
set vicmd=nvim

if has('win')
    filetype * start
else
    filetype * open
endif
```

## Actuall results

When press `s` to open a shell in current directory, there is nothing happening (tried to replace the `SHELL` env variable with full path of pwsh but it didn't work either).

When press `l` to edit a file, there is nothing happening (tried to replace the `EDITOR` env variable with full path of neovim but it didn't work either).

But it works for bash and zsh on Linux.

It also works for cmd on Windows without `SHELL` and `EDITOR` variables.

I'm not sure if it's duplicated. If it is please redirect this issue to the related one.

Thank you!

**Comment by xaizek** [comment]
Vifm ignores `$EDITOR`.

`$SHELL` is used for `:shell` and default value of `'shell'` and everything seems to work if you keep `'shell'` as `cmd.exe` while setting `$SHELL`. What doesn't work is setting `shell=powershell.exe`, because Windows is a nightmare when it comes to escaping. Vifm tries to run

    powershell.exe -c 'powershell.exe'

an apparently PowerShell thinks that it was passed a string and just prints it... It's hard to express how much I hate all this... I probably need to hard-code different escaping policy for `powershell[.exe]` and `pwsh[.exe]` values of `'shell'` as it's done for `cmd.exe`.

Thanks for reporting, I think some people use Vifm with PowerShell, but probably set it up in a different way or found a workaround.

**Comment by peromage** [comment]
Thanks for the reply!

I really like Vifm so I guess I have to use `cmd` to get it work for now.

For the escaping issue, if it doesn't work on Windows I wonder why it doesn't work on Linux either? Probably that's an issue of pwsh?

**Comment by xaizek** [comment]
> I really like Vifm so I guess I have to use `cmd` to get it work for now.

If you add this to your `vifmrc` on Windows
```vim
set shell=cmd.exe
```
you should get PowerShell when you do `:shell`, but `cmd` will be used for other things (like `:!cmd`).

> For the escaping issue, if it doesn't work on Windows I wonder why it doesn't work on Linux either? Probably that's an issue of pwsh?

You might need to change `'shellcmdflag'` on Linux to `-Command` if PowerShell doesn't understand `-c`  (default value).
