### ISSUE TITLE
:tree displays link to parent directory for empty directories

### ISSUE THREAD

**Issue by Melandel** [vifm/vifm#564]
Hello,

I noticed that on Windows10, using version 0.10.1, using `:tree` results displayes empty folders on two lines, one with the folder name, and the other with the `../` symbol :
![image](https://user-images.githubusercontent.com/48007894/86517922-2ca46b00-be2d-11ea-8b5c-cf7728f4c8f1.png)

I personally find it quite confusing/visually polluting. Is the second line useful/an expected behavior ?

Would it be hard to display empty folders on one line only?

**Comment by xaizek** [comment]
Hi,

This is expected behaviour. `../` leafs do have utility, positioning cursor at `../` is the only way to insert files in that directory (e.g., with <kbd>p</kbd> or `:touch`) without leaving `:tree`. Not showing them is easy, but it has to be optional and disabled by default because it reduces functionality of trees.
