### ISSUE TITLE
Custom tab delimiter

### ISSUE THREAD

**Issue by CoreCube** [vifm/vifm#571]
Hello,

Currently the tabs are delimited by square brackets and as I can see it's hard coded.
I find it more convenient to have spaces instead of square brackets.
So it would be nice to have the ability to configure the whole tab label.

**Comment by xaizek** [comment]
Hi,

v0.11 will have `'tablabel'` option, but it doesn't allow changing that part (the title is basically constructed as `[<tabnum>:<'tablabel'>]`). The reason is too be able to guarantee visibility of tab numbers and separators while shortening the label if necessary. Including those parts in `'tablabel'` poses some problems.

I just thought of `\ze`, `\zs` sequences in Vim, maybe something like that can be helpful in this case, not sure yet.

**Comment by CoreCube** [comment]
Thanks a lot for developing and maintaining the project. I use vifm every day.
