### ISSUE TITLE
Command :copy should display a file conflict dialog

### ISSUE THREAD

**Issue by windwp** [vifm/vifm#573]
Hi when i copy file already exist in another panel use command :Copy (key <f6>)
It will display a message "file abc.txt already exists". It will better if it can display a file conflict dialog 
I need to press "yy" for yank and move to another buffer and press "p" for paste then that file conflict dialog appear.

**Comment by xaizek** [comment]
Hello,

A workaround can look something like this:
```vim
:command! cp :yank | winrun , put
```

I'm not sure about changing current behaviour because it has its benefits (if the operation started it should finish without user's attention) and the semantics change is relatively significant.  Adding a flag to `'cpoptions'` might help though.

Related: https://github.com/vifm/vifm/issues/336#issuecomment-502431614

**Comment by windwp** [comment]
@xaizek 
Hi
Can you give me a command for move too :smile:
Many thank

**Comment by xaizek** [comment]
It's very similar:
```vim
:command! mv :yank | winrun , put!
```
