### ISSUE TITLE
Freezing on a regular navigation

### ISSUE THREAD

**Issue by halturin** [vifm/vifm#602]
version: 0.11
OS: NixOS

i've recordered this issue to demonstrate how it looks like.  https://youtu.be/Ec_yj_BHOv0
you might notice that the problem is exactly on the vifm side as there is no CPU overload and the keyboard works well with other applications. navigation through the tmux windows or cursor moving in vim works well except the vifm. 

i also noticed that there multiple instances of vifm are running when this problem appears. killing all these processes and starting vifm again usually fix this problem.

**Comment by xaizek** [comment]
Not sure why this would happen. I have multiple instances open most of the time and never noticed anything similar.

An unlikely scenario is that instances fight for the same named pipe (which shouldn't really happen). You can try starting several instances and listing them via `vifm --server-list` (or do `:echo v:servername` in each instance) to see that they have distinct names. If they are different, I don't see how number of instances could affect anything.

**Comment by xaizek** [comment]
Could you attach with `gdb` to a frozen instance to get the backtrace? (`gdb --pid {pid}` and then do steps from number 4 [from here](https://wiki.vifm.info/index.php/How_to_report_a_crash_in_a_most_useful_way_(with_a_backtrace))). Or run it under `gdb` from the start, if the issue is reproducible that way (probably the case).

**Comment by xaizek** [comment]
I guess it doesn't freeze anymore.
