### ISSUE TITLE
Use EDITOR for :help

### ISSUE THREAD

**Issue by xeruf** [vifm/vifm#622]
Follow-up to #540 - vifm should use $EDITOR if set to open help and fall back to vim if it is not set - or alternatively, default to `vim` and fall back to $EDITOR if that is not available.

**Comment by xaizek** [comment]
Inside Vifm `'vicmd'` is used to define editor and its value is used by `:help` as well. Using value of `$EDITOR` for `'vicmd'` by default won't always work as some level of similarity with Vim is assumed.

**Comment by xerus2000** [comment]
Well, it could first try to fall back to common alternatives such as `vi` and `neovim`.
People using `vifm` will probably have something vim-like in their `$EDITOR`, so I think at least adding it as fallback should be reasonable.

**Comment by xaizek** [comment]
I'm afraid this might cause much confusion. The setting in configuration file will say `vim`, however something else will be run due to a hidden list of editors to try.

How about showing a message like `Couldn't open help file, configure editor via ":set vicmd=your-editor"` if it looks like the help command has failed?

**Comment by xerus2000** [comment]
Yes, that would be fine! I had to search a while to find how to configure it. Maybe include the path to the `vifmrc`, since people seeing this message will probably be new to it ;)
