### ISSUE TITLE
Can it add the android mount point in the media menu?

### ISSUE THREAD

**Issue by yanwh0311** [vifm/vifm#623]
Can it add them android mount point in the media menu?

Android can be detected by libmtp ,and mount via fuse filesystem

It is beter to have a option in the media menu.

**Comment by xaizek** [comment]
`:media` menu is an interface to [`'mediaprg'`](https://vifm.info/vimdoc.shtml#vifm-%27mediaprg%27) script. The one shipped with Vifm uses `udisks`/`udisks2`/`udevil`, which apparently don't discover Android mounts. If there is a command-line tool to manage them, you could probably wrap it for use with `'mediaprg'`.

**Comment by jose1711** [comment]
:+1: for having virtual-type (e. g. `fuse`) mounts handled by `vifm-media` script. Perhaps for purpose of switching to and unmounting only.

**Comment by xaizek** [comment]
If https://github.com/phatina/simple-mtpfs is installed, `vifm-media` should now be able to mount/unmount MTP devices.

> 👍 for having virtual-type (e. g. `fuse`) mounts handled by `vifm-media` script. Perhaps for purpose of switching to and unmounting only.

That needs clarification.  You mean just any FUSE mount?  I think it can't be done nicely in general because you won't know what's being mounted (source of a FUSE mount is FUSE mounter instead of a file/device that's being mounted).
