### ISSUE TITLE
Using custom functions from .bashrc

### ISSUE THREAD

**Issue by og900aero** [vifm/vifm#631]
I have a custom function in .bashrc:

ex - archive extractor
usage: ex filename

ex ()
{
  if [ -f $1 ] ; then
    case $1 in
      *.tar.bz2)   tar xjf $1   ;;
      *.tar.gz)    tar xzf $1   ;;
      *.bz2)       bunzip2 $1   ;;
      *.rar)       unrar x $1     ;;
      *.gz)        gunzip $1    ;;
      *.tar)       tar xf $1    ;;
      *.tbz2)      tar xjf $1   ;;
      *.tgz)       tar xzf $1   ;;
      *.zip)       unzip $1     ;;
      *.Z)         uncompress $1;;
      *.7z)        7z x $1      ;;
      *)           echo "'$1' cannot be extracted via ex()" ;;
    esac
  else
    echo "'$1' is not a valid file"
  fi
}

I want use in vifm custom command. I set the following command in vifmrc:

command! ex ex %c

When write :ex in vifm, I get error message: LMA.rar Tmp file too large

My system is pure Arch Linux with Bspwm window manager.

**Comment by xaizek** [comment]
It doesn't work because `.bashrc` is sourced only by interactive shells and not when one does `bash -c 'ex file'`. Forcing interactive mode seems to be a bad idea, so I direct you to a similar question [on q2a](https://q2a.vifm.info/778/how-can-i-let-vifm-have-access-to-my-shell-environment?show=779#a779) where I outlined an approach which should work better.

**Comment by og900aero** [comment]
Ohh, I understand. Then I solved with custom script, and invoke this script. It's duplicate, but works.

**Comment by PRESFIL** [comment]
On my distribution I have this after user created:

```sh
cat .bashprofile
#
# ~/.bash_profile
#

[[ -f ~/.bashrc ]] && . ~/.bashrc
```

You can use it, if you think that all shells should re-read same config. Or store all inside `.bashrc`.

**Comment by og900aero** [comment]
I have too this line, but this is doesnt solve the problem.

**Comment by PRESFIL** [comment]
I was wrong. Yes, in non-interactive mode, `bash` does not read anything from configs, and even takes into account aliases without `shopt-s expand_aliases`. Perhaps making a script is the most logical solution, because an alias is a *purely interactive solution*...

p.s. And they came up with a stupid name :anger:  (`ex` is already used by the **Ex** text editor (`ex(1)`)).
p.p.s. There are more functional *shell archivers wrappers* on GitHub. I also searched that...

**Comment by xaizek** [comment]
From `man bash`:

> When bash is invoked as an interactive login shell, or as a non-interactive shell with the --login option, it first reads and executes commands from the file /etc/profile, if that file exists.  After that  file, it looks for ~/.bash_profile, ~/.bash_login, and ~/.profile, in that order, and reads and executes commands from the first one that exists and is readable.

`bash -c 'cmd'` is neither login nor interactive. `bash -lc 'cmd'` might make functions (not aliases, those need a `shopt` call) available though (if one sets `:set shellcmdflag=-lc`) if there are no negative side-effects.
