### ISSUE TITLE
How do I move highlighted file(in non-continuous range)?

### ISSUE THREAD

**Issue by ar1xwe** [vifm/vifm#648]
I've read
https://github.com/sitaramc/notes/blob/master/vifm.mkd
and
https://vifm.info/vimdoc.shtml
but I still can't understand how to move file by just using "/" with ":move" command.

The only way I can tell is use
:select \*[needle]\*
to select first and then use 
:move [path]
command to do it.

Can't I just use "/foo" to select all the highlighted files?

**Comment by xaizek** [comment]
> Can't I just use "/foo" to select all the highlighted files?

Yes, you can. For that [`'hlsearch'`](https://vifm.info/vimdoc.shtml#vifm-%27hlsearch%27) option needs to be enabled. Do `:edit $MYVIFMRC` and remove or comment out `set nohlsearch` line. It's disable by default because if don't expect this, you'll operate on selection by accident, which can be annoying.

**Comment by ar1xwe** [comment]
> > Can't I just use "/foo" to select all the highlighted files?
> 
> Yes, you can. For that [`'hlsearch'`](https://vifm.info/vimdoc.shtml#vifm-%27hlsearch%27) option needs to be enabled. Do `:edit $MYVIFMRC` and remove or comment out `set nohlsearch` line. It's disable by default because if you don't expect this, you'll operate on selection by accident, which can be annoying.

Thank you, this is insanely useful.
