### ISSUE TITLE
[info needed] vifm-convert-dircolors -e converts everything to lower case now

### ISSUE THREAD

**Issue by flux242** [vifm/vifm#660]
It wasn't like that as I generated the ~/.config/vifm/colors/Default.vifm

say I have a color definition for LS_COLORS in my .dircolors. But color definition for ls_colors will be generated by the vifm-convert-dircolors

why the change and what's the workaround?

**Comment by xaizek** [comment]
The change was 2 years ago in 0c0268ceacb16bc1c6ba2760ec16007b223e6b78 to speed up matchers.

Looks like I misinterpreted flags, because commit message says the pattern ignores case, but `I` flag makes it case-sensitive. You can remove the flag to ignore case.

Do you depend on case-sensitive matching? I can update the script to produce much faster highlighting by using globs, but they always ignore the case.

**Comment by flux242** [comment]
I have this in my .dircolors
```
# perl
.pl                   38;5;208
.PL                  38;5;160
```
previously the following was generated
```
highlight /.*\.PL$/I cterm=none ctermfg=160 ctermbg=default
highlight /.*\.pl$|.*\.xib$/I cterm=none ctermfg=208 ctermbg=default
```
now neither .pl nor .PL is in the generated highlight list
The matching pattern canno't be case insensitive imo
