### ISSUE TITLE
Changing directory

### ISSUE THREAD

**Issue by halturin** [vifm/vifm#675]
Is there any chance to change the directory without explicitly specifying 'cd' command?

it would be much convenient to have an option like 

:/tmp <enter> - to change current directory to /tmp
:.. <enter> - the same as 'cd ..'

**Comment by qsmodo** [comment]
This would clash with normal commands: Would `:q` go to directory `q` or would it quit Vifm?

**Comment by halturin** [comment]
yeah, i see, but i would prioritize a command over trying to change the dir. the same as it works in zsh.

**Comment by xaizek** [comment]
Wouldn't it be simpler to define a mapping like this one?
```vim
nnoremap ; :cd<space>
```

**Comment by halturin** [comment]
If I wanted to get rid of typing 'cd ', I definitely would have used this way of binding. But the main idea is to make it very similar to the zsh experience, which I found useful and simplifies the navigation. That's the reason I've posted this proposal. If you think it wouldn't fit, let's close this issue then.

**Comment by xaizek** [comment]
I use the same feature in bash. It works fine most of the time, but I don't like the ambiguity of input and that completion can change its nature as you type more characters, that's why I'd like to explore alternatives.

What about "navigation mode" which exists in some file managers and maybe in Emacs? While you in that mode, each command is a `:cd` command and you have to leave the mode explicitly so you can do multiple `cd`'s effortlessly. I think someone asked for this.

As an optional behaviour, this could be added. It's basically: if error is "no such command", call `:cd` handler.
