### ISSUE TITLE
core dump when returning from shell in dropdown window

### ISSUE THREAD

**Issue by Pierric82** [vifm/vifm#711]
Hi,

I've started using vifm and like it a lot. My window manager is Qtile, and I've set up a shortcut to bring up vifm on top of the screen as a Qtile dropdown window rather than a regular one that would be tiled among the other windows. I mention this because the issue I'm observing, strangely, happens only when vifm is called in that way (btw Qtile launches an Alacritty terminal, which calls vifm).

If I open a shell with the s key, it works fine, until I exit that shell. Then, vifm segfaults with the error: malloc() invalid size (unsorted). It says core dumped but I can't locate a dump file. However I've run it through strace and attach the resulting file.
[vifm.strace.txt](https://github.com/vifm/vifm/files/7104941/vifm.strace.txt)

If I run this directly from a regularly opened Alacritty terminal I don't have this issue (I've had a few occasional segfaults there too, but not nearly as systematic). Also, the shell is a sure way to make vifm crash, but it's not the only one, it crashes very easily when accessed that way. I find it strange as I don't see how a purely console-based app could be influenced by the window it's living in. But it is indeed vifm that crashes, not Qtile.

Cheers,
Pierric.

**Comment by xaizek** [comment]
Hello,

Thanks for the report. Are you using v0.11?

Output of `strace` shows system calls, while the crash is caused by memory issue in user space, so it's not very useful.

It might crash only in Qtile dropdown because that's the only case when you start Vifm outside of shell. Can you try if it fails if you start Vifm like in `xterm -e vifm` (or `alacritty -e vifm`).

It's hard to fix a crash that I don't see and it would be great if you could gather more details by using `gdb` or `valgrind` on Vifm, probably in the same way you captured `strace` output by replacing command for the dropdown.  For `valgrind` the command would look like this and generate `~/valgrind-report`:
```
valgrind --track-origins=yes --track-fds=yes --log-file=$HOME/valgrind-report --leak-check=full vifm
```
Instructions for `gdb` are available in [the wiki](https://wiki.vifm.info/index.php/How_to_report_a_crash_in_a_most_useful_way_(with_a_backtrace)), only the first step would be different (so you get `(gdb)` prompt in the dropdown when you open it and continue from there).

**Comment by Pierric82** [comment]
Hi xaizek,

Thanks for a quick and considerate answer! And apologies about my limited skills regarding traces and debugging!

I forgot to mention that interestingly, when I insert gdb between Qtile and vifm (for all kinds of traces, I've created one-line bash script that runs the command, and qtile runs that script, so in this case it would be qtile launching the script, the script launching gdb, gdb launching vifm), then the crash does NOT happen (but it's not very practical to type "run" everytime so it's not a workaround either ;) ). But with strace it did, which is why I had included that trace.

I don't know what valgrind really is but I've installed it, and here is the report, generated in the same manner (it does crash with this).
[valgrind-report.txt](https://github.com/vifm/vifm/files/7105892/valgrind-report.txt)

Running alacritty -e vifm from an existing terminal does NOT crash upon return from the shell.

Let me know if there's anything else I can do or check. I completely understand it's hard to fix if you can't reproduce it... Thanks for trying!

Cheers,
Pierric.

**Comment by xaizek** [comment]
`valgrind` is many things, but it's mostly used for tracking memory issues.

Thanks, `valgrind`'s report contains useful information. It looks like the bug might be in `libncursesw` rather than in Vifm. It's the library's code which allocates some memory and then ruins its metadata. Maybe I'll be able to reproduce it with some effort to confirm the bug in ncurses. If not, there might still be a workaround for the issue.

**Comment by Pierric82** [comment]
Thanks, that's great news! Do let me know how this goes!

**Comment by xaizek** [comment]
Couldn't reproduce it with newer versions of ncurses, but added a workaround, which might address it. If you would like to test it, building Vifm [isn't hard](https://wiki.vifm.info/index.php/Obtaining_Vifm#From_sources) (no need to install it, can be run from build directory).

@ThomasDickey, have you seen something similar to what is described in the commit message for 568aac2ee625b946806720cc3647dd0d9ad43579? Maybe there was a bug fix in that area.

**Comment by ThomasDickey** [comment]
not recently - there's no version information given, so I'm unsure.  (calling `wrefresh` after `endwin` sounds like a program shelled out temporarily -- nothing unusual in that).

**Comment by xaizek** [comment]
It's at least 6.2. I tried to reproduce it on 5.9, 6.2 and a recent snapshot, but it won't crash. Anyway, thanks for taking a look.

**Comment by ThomasDickey** [comment]
well... 5.7 is what comes up in discussion occasionally, and that's pretty much just Apple (there are tiny niches for Solaris and OpenBSD at the same version, but I don't see much discussion on those).

**Comment by Pierric82** [comment]
Hi,

It worked! Thank you so much. I really appreciate your taking my feedback into account and finding a solution so quickly in spite of the underlying issue lying elsewhere.

About vifm not being hard to compile, that is true, I just had a minor hiccup. To be able to compile, I had to symlink automake and aclocal to automake-1.15 and aclocal-1.15, as my system has 1.16 only, but these programs are called with version number in the file name, and I could not downgrade easily. I don't know if this means something in the Makefile should be made more generic, or if it's me who doesn't know something super obvious. In any case this has worked, which is what matters!

**Comment by xaizek** [comment]
Great, thanks for testing!

Instructions on the wiki didn't account for building from git repository, thanks for pointing it out. I've added the following line:
```
scripts/fix-timestamps # run this if the file exists, to avoid issues with autotools (they don't even need to be installed then)
```

**Comment by xaizek** [comment]
@Pierric82, it's possible that the bug is back for you again... I reverted the change in 5ac6d30ad92b99293cc3eca9c61fd8044fb3d4bf, because that call restores TUI when it gets ruined by binary data. However, I added a different workaround which might help.

If the issue is back, you can now run `./configure` with `--enable-developer` (in addition to other options) and run new binary under `valgrind`. This time the log will contain more information thanks to debug data.

**Comment by Pierric82** [comment]
Thank you for letting me know! I'm away from my main machine this week but
will have a look next week.

Cheers,
Pierric.

**Comment by Pierric82** [comment]
Hi!

I've cloned from git this morning and compiled (I had to add `CFLAGS=-Wno-error` this time, as errors on deprecation were causing the build to fail). Happy to report, I still have no crash with that new version!

Cheers,
Pierric.

**Comment by xaizek** [comment]
Hi. Glad to hear that, thanks!
