### ISSUE TITLE
Image preview on kitty

### ISSUE THREAD

**Issue by hutou** [vifm/vifm#731]
Hi,
It seems `vifm 0.12` introduced a regression.
Image preview on `kitty` worked fine with `vifm 0.11` with the following config : 
```
fileviewer *.bmp,*.jpg,*.jpeg,*.png,*.gif,*.xpm
    \ kitty +icat --place %pwx%ph@%pxx%py  --silent %c
    \ %pc
    \ kitty icat --clear --silent %pd
```
With `vifm 0.12`, I get : 
```
 Traceback (most recent call last):                                                     
   File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main                 
     return _run_code(code, main_globals, None,                                         
   File "/usr/lib/python3.9/runpy.py", line 87, in _run_code                            
     exec(code, run_globals)                                                            
   File "/usr/bin/../lib/kitty/__main__.py", line 153, in <module>                      
     main()                                                                             
   File "/usr/bin/../lib/kitty/__main__.py", line 144, in main                          
     namespaced(['+', first_arg[1:]] + sys.argv[2:])                                    
   File "/usr/bin/../lib/kitty/__main__.py", line 99, in namespaced                     
     func(args[1:])                                                                     
   File "/usr/bin/../lib/kitty/__main__.py", line 13, in icat                           
     rk('icat')                                                                         
   File "/usr/bin/../lib/kitty/kittens/runner.py", line 122, in run_kitten              
     runpy.run_module('kittens.{}.main'.format(kitten), run_name=run_name)              
   File "/usr/lib/python3.9/runpy.py", line 213, in run_module                          
     return _run_code(code, {}, init_globals, run_name, mod_spec)                       
   File "/usr/lib/python3.9/runpy.py", line 87, in _run_code                            
     exec(code, run_globals)                                                            
   File "/usr/bin/../lib/kitty/kittens/icat/main.py", line 583, in <module>             
     main()                                                                             
   File "/usr/bin/../lib/kitty/kittens/icat/main.py", line 507, in main                 
     sys.stdout = open(os.ctermid(), 'w')                                               
 OSError: [Errno 6] No such device or address: '/dev/tty'     
```
Thanks

**Comment by dusanx** [comment]
Can please somebody confirm this working? I am trying to make vifm + images in kitty working every couple of months but since this looks closed maybe I am doing something wrong.

Arch linux
> local/vifm 0.12-1
>    A file manager with curses interface, which provides Vi[m]-like environment

> local/kitty 0.24.4-1
>    A modern, hackable, featureful, OpenGL-based terminal emulator

My current vifmrc contains:

> fileviewer *.bmp,*.jpg,*.jpeg,*.png,*.gif,*.xpm
> 	\ kitty +icat --silent --transfer-mode=stream --place=%pwx%ph@%pxx%py %c %N
> 	\ %pc
> 	\ kitty icat --clear --silent %pd

Every preview attempt results in:
```

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/bin/../lib/kitty/__main__.py", line 185, in <module>
    main()
  File "/usr/bin/../lib/kitty/__main__.py", line 176, in main
    namespaced(['+', first_arg[1:]] + sys.argv[2:])
  File "/usr/bin/../lib/kitty/__main__.py", line 129, in namespaced
    func(args[1:])
  File "/usr/bin/../lib/kitty/__main__.py", line 12, in icat
    rk('icat')
  File "/usr/bin/../lib/kitty/kittens/runner.py", line 120, in run_kitten
    runpy.run_module(f'kittens.{kitten}.main', run_name=run_name)
  File "/usr/lib/python3.10/runpy.py", line 212, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/bin/../lib/kitty/kittens/icat/main.py", line 613, in <module>
    main()
  File "/usr/bin/../lib/kitty/kittens/icat/main.py", line 523, in main
    sys.stdout = open(os.ctermid(), 'w')
OSError: [Errno 6] No such device or address: '/dev/tty'

```
Since I am using all the latest packages any help is welcome. In current form it is _not_ working.

**Comment by xaizek** [comment]
@dusanx From https://github.com/vifm/vifm/issues/731#issuecomment-954577072

> It (`%N`) should be added to fileviewer command, but **it's not part of 0.12**. You need to build Vifm from sources or wait for the next release (or use something else like Ueberzug for now).

**Comment by sQVe** [comment]
This suggested solution no longer works for me. I'm getting `This should be run as kitten icat` outputted. It looks like `kitty` changed the API for `icat`.

**Comment by xaizek** [comment]
I guess, it's this now (haven't tested):
```vim
fileviewer *.png
    \ kitten icat --silent --transfer-mode=stream --place=%pwx%ph@%pxx%py %c %N
    \ %pc
    \ kitten icat --clear --silent %pd
```

**Comment by sQVe** [comment]
@xaizek That does, sadly, not work. It hangs `vifm`.

**Comment by xaizek** [comment]
Maybe try with `kitty +kitten icat` instead of `kitten icat` (don't know if there is a difference) and check whether it works outside of Vifm.

**Comment by xaizek** [comment]
It's not about the syntax, `kitty` is sending `SIGTTOU` to `kitten` and stops its process thereby shooting itself in the foot, although shooting in the head would be a much better idea in this case.

I'll probably change the meaning of `%N` (`kitty` is the only damn thing that needs it anyway) and this idiocy will work:
```vim
fileviewer *.png
    \ kitten icat --silent --transfer-mode=file --place=%pwx%ph@%pxx%py %c >/dev/tty </dev/tty %N
    \ %pc
    \ kitten icat --clear --silent >/dev/tty </dev/tty %N
```

Why `>/dev/tty`?  Because despite requiring the terminal to be present it doesn't write to it anymore (surprise!)!  Now it writes to `stdout`.

Why `</dev/tty`?  Because otherwise it refuses to process `--place` because it suddently thinks that you've passed in 2 files when `stdin` isn't `/dev/tty`!

***

I thought `gnome-terminal` was the worst, but `kitty` is now `#1` in my list of shitty terminals (`kitty's shit` terminal?).

**Comment by sQVe** [comment]
@xaizek Did I understand correctly that you need to change something with `vifm` for the above fileviewer code to work? I just tried it now and it still doesn't work for me.

**Comment by xaizek** [comment]
@sQVe Yes, kitty v0.27+ won't work without modifying Vifm. Theoretically, running `stty -tostop` before running `kitten` should help too, but kitty seems to ignore this setting.

**Comment by falsified** [comment]
kitty 0.26.5 is the highest working version with previews, currently. Thank you for the update!!

**Comment by ret2src** [comment]
The configuration posted above by @xaizek works for me:

~~~ vim
fileviewer {*.jpg,*.jpeg,*.png,*.gif}
    \ kitten icat --silent --transfer-mode=file --place=%pwx%ph@%pxx%py %c >/dev/tty </dev/tty %N
    \ %pc
    \ kitten icat --clear --silent >/dev/tty </dev/tty %N
~~~

![image](https://github.com/vifm/vifm/assets/2010034/230af623-cb11-4ea5-9473-22b2f058cd8b)

~~~ bash
$ vifm --version         
Version: 0.13
Git info: built out of repository
Compiled at: May 10 2023 21:21:48

Support of extended keys is on
Parsing of .desktop files is enabled
Without GTK+ library
With magic library
Without X11 library
Without dynamic loading of X11 library
With file program
With -n option for cp and mv
With remote command execution

$ kitty --version      
kitty 0.28.1 created by Kovid Goyal
~~~

**Comment by xaizek** [comment]
> Any idea why `:view` clears the preview, but `:wincmd o` does not and requires the workaround from above?

@ret2src, Vifm doesn't clear the preview on switching to single-pane layout.  It's not related to Kitty, the same will happen with any other previewer that requires clear command.  You might be the first one to notice this omission.  Thanks, will fix it.

**Comment by ret2src** [comment]
Great, thank you very much for your rapid reply and, most of all, for creating vifm. I use it daily and haven't found a more amazing file manager yet!

**Comment by jediaxe** [comment]
This works great for image files, thx! Is there anyway we can get this to work for the following formats?
Pdf
epub/eBook
Djvu
Audio files
Video files
Fonts

Similar to vifmimg
https://github.com/thimc/vifmimg

**Comment by ret2src** [comment]
@jediaxe Yes, I've hacked together a quick script based on <https://github.com/eylles/vifm-sixel-preview/blob/master/vifm-sixel>. For me, it works great so far. Here's the code:

<https://gist.github.com/ret2src/e0477a56ee272743aea9f47945073dcc>

**Comment by falsified** [comment]
epub-thumbnailer works fine, it shouldnt reaally matter if its outdated,  as its core functionality should still work.
just tailor the command line to your script, should be something similar to: 

"epub")
                epub-thumbnailer "$2" "blah.jpg" 1024 > /dev/null

**Comment by jediaxe** [comment]
.epub previews still didn't work unless I revert to pillow 9.4.0

Installing gnome-epub-thumbnailer from the main Arch repo and updating the visualpreview script from https://gist.github.com/ret2src/e0477a56ee272743aea9f47945073dcc seems to work fine for me.

`   epub)
     if [ ! -f "${thumbnail_file}" ]; then
         epub-thumbnailer "${input_file}" "${thumbnail_file}" 1024
     fi
     show_preview "${thumbnail_file}" "${width}" "${height}" "${xpos}" "${ypos}"
     ;;
`
to
`   epub)
     if [ ! -f "${thumbnail_file}" ]; then
         gnome-epub-thumbnailer "${input_file}" "${thumbnail_file}"
     fi
     show_preview "${thumbnail_file}" "${width}" "${height}" "${xpos}" "${ypos}"
     ;;
`
@falsified @ret2src

**Comment by xaizek** [comment]
> @ret2src, Vifm doesn't clear the preview on switching to single-pane layout. It's not related to Kitty, the same will happen with any other previewer that requires clear command. You might be the first one to notice this omission. Thanks, will fix it.

Finally pushed the fix from a local branch to d5791fa.

**Comment by ret2src** [comment]
> Finally pushed the fix from a local branch to [d5791fa](https://github.com/vifm/vifm/commit/d5791fab39db7e315885ffe11f440a6f64d4398b).

Thank you!

**Comment by iambumblehead** [comment]
A discussion with the kitty developer is here https://github.com/kovidgoyal/kitty/discussions/7275

According to that person, using "--use-window-size" param with kitten icat allows kitty to display images without messaging /dev/tty. When the param is included, however, vifm renders noise to the fileviewer area and, according the kitty developer, vifm could be wrongly processing the fileviewer response. From within the script called by vifm, kitty handles this call without error but only string-noise appears in the vifm view,
```bash
kitten icat \
  --use-window-size "${kicat_wh_cells/x/,},${kicat_wh_pixels/x/,}" \
  --place "${img_wh}@${img_tl}" \
  --align left \
  --stdin=no \
  --transfer-mode=stream "$img_path"
```

<img width="400" alt="Screen Shot 2024-03-27 at 10 16 05 PM" src="https://github.com/kovidgoyal/kitty/assets/2058705/84c06423-11b4-4bd5-b791-4937c22aabb7">

The `vifmrc` has been updated to use different fileviewer calls, however the image is always rendered string-noise,
```bash
thu.sh -ck %c %px %py %pw %ph %pd %pu %N
thu.sh -ck %c %px %py %pw %ph %pd %pu
thu.sh -ck %c %px %py %pw %ph %pd
```

A possibly related issue is that vifm+iterm2 using sixel seems to have the same behaviour here. This is the sixel call,
```
magick \
  -background "$color_RGBA_transp" \
  "$img_path" \
  -geometry "$img_wh" \
  sixel:-
```

And using various script calls from the fileviewer results in string-noise
<img width="400" alt="Screen Shot 2024-03-27 at 11 43 37 PM" src="https://github.com/vifm/vifm/assets/2058705/dda5672e-4825-4f54-abec-00b91a5adbb5">

**Comment by iambumblehead** [comment]
if your system still uses imagemagick 6, the issue can be reproduced using this 'convert' command in `bug.sh` (only imagemagick 7 defines the 'magick' command)
```bash
#!/usr/bin/env bash

convert \
    -channel rgba \
    -background "rgba(0,0,0,0)" \
    -geometry "400x400" \
    "/home/bumble/.config/thu/svg.804x375.png" \
    sixel:-
```

**Comment by xaizek** [comment]
@iambumblehead This isn't string noise, this is how Sixel actually looks like.  Vifm determines kind of graphical output by looking at macros used in a command.  Combination of `%px` and `%px` is taken for an indication of some graphical output (not Sixel).  `%pd` could be made to have higher priority, but `%px` and `%py` really shouldn't be used with it because Vifm does positioning on the screen if `%pd` is present.

**Comment by iambumblehead** [comment]
Thank you. This signature using `%px` and `%py` is, it seems, standard for other file managers and preview scripts
```bash
previewcmd $path $top $left $width $height $id
```

As well, kitty _basically_ requires all of those values to practically used inside this script for vifm. If vifm might accommodate the function signature for thu.sh that would be great and, humbly, no hurry from me for any thing or reply --thank you much for helping me and replying to me a stranger.

I'm not planning to "disappear" but will develop thu.sh at least a little bit more and hope it will one day meet your own requirements to be a worthy vifm image previewer,
 * adding more tests,
 * supporting caching and possible pre-processing ala https://github.com/sxyazi/yazi; I could be wrong but believe this last part could be implemented in a minimal sort of way in maybe an afternoon w/ some consideration.

**Comment by xaizek** [comment]
> As well, kitty _basically_ requires all of those values to practically used inside this script for vifm.

Try passing zeroes, Sixel image is the same regardless of where it's printed, but if kitty also tries to move the cursor it might not work.

> hope it will one day meet your own requirements to be a worthy vifm image previewer

Terminals aren't made for images, so they shouldn't actually be used for viewing them :)

**Comment by iambumblehead** [comment]
Thanks for replying despite you are not interested in image preview :)

Here are some possible arguments in favor of supporting the kitty-needed call signature.

**The image preview approach used by `thu.sh` comes at low cost to vifm.** Because image-processing tools are external and optional, they do not increase vifm's small size. Because image-processing scripts like `thu.sh` are developed externally, they do not greatly increase vfm's development surface. At low cost, vifm could support users interested in this type of terminal image preview: terminal-native, low-dependencies, bash, imagemagick+ffmpeg.

**Another argument: vifm is the best terminal file manager to support this type of image preview.** Partly, this is because vifm alone is extremely finished, polished, flexible, well-documented etc and there are no file managers to equal vifm. Vifm is super small and easy to use anywhere. If image preview could be enabled from ubiquitous bash+imagemagick+ffmpeg, vifm w/ image preview could readily be used in more places than any other image-viewing fm like yatzi or even vifm+vifmimg, which requires more dependencies that are less common (ueberzug, epub-thumbnailer, fontpreview with sxiv etc.) In my own experience, setting up vifm with thu.sh on guix, when it works, is amazing because hardly anything extra needs to be installed on the host system and I don't need to think about anythng. vfm and thu.sh are well suited to each other for the purpose of previewing images.

> Terminals aren't made for images, so they shouldn't actually be used for viewing them :)

For me as a user, image preview for media content like video and audio greatly increase recognizably. There is a youtube channel, from which I download videos from, that uses abstract video ttles and themed-imagery for each video and image preview helps me to recognize and differentiate these videos.

**A last argument is, my own activity is a sort of advertisement for vifm.** Some people will learn about vifm when they come across my discussions and investigations and screenshots. The impact is low but possibly worth mentioning anyway.

So that's all thanks for reading me :)

**Comment by xaizek** [comment]
> Here are some possible arguments in favor of supporting the kitty-needed call signature.

I was going to do it without any arguments, since it won't hurt anything and there is no reason to not allow it (it's just an accident or an omission that it's not allowed).

**Comment by xaizek** [comment]
@iambumblehead The change is on the master branch.

**Comment by iambumblehead** [comment]
@xaizek the master branch works great.

I used the guix recipe here https://git.savannah.gnu.org/cgit/guix.git/tree/gnu/packages/vim.scm?id=master#n916 and found this
```scm
;; This test segfaults
(substitute* "tests/Makefile"
   ((" menus misc") ""))
```

Building the package without that does fail with segfault. It is probably insignificant (feel free to ignore) but in case it is interesting to you the failed part of the build messages is attached

<details open>
  <summary>end of build output with segfault</summary>

```bash
make[4]: *** [Makefile:376: misc] Segmentation fault
make[4]: Leaving directory '/tmp/guix-build-vifm-e95c30ab2669eee19efe0ea89045f6b8f0ab4ee0.drv-0/source/tests'
FAIL runtests (exit status: 2)


error: in phase 'check': uncaught exception:
%exception #<&invoke-error program: "make" arguments: ("check" "-j" "4") exit-status: 2 term-signal: #f stop-signal: #f> 
phase `check' failed after 35.8 seconds
command "make" "check" "-j" "4" failed with status 2
```

</details>

**Comment by FugueSoft** [comment]
Not sure if I should make a new issue or nah

**Comment by xaizek** [comment]
@FugueSoft, order of `:fileviewer` commands matters.  This won't work:

```vim
fileviewer *[^/] pygmentize -O style=monokai -f console256 -g

" Displaying pictures in terminal

fileviewer *.png, *.jpg, *.gif
    \ kitty +icat --silent --transfer-mode=stream --place=%pwx%ph@%pxx%py %c %N
    \ %pc
    \ kitty icat --clear --silent %pd
```

because `fileviewer *[^/] ` matches all files including those matched by `*.png, *.jpg, *.gif`.  Move the bottom command up.  You can check order of commands using `:fileviewer bla.png` menu.

`Unknown option: --fish` looks weird, not sure where it comes from (could be `$SHELL`).

And yes, this issue is quite large and old, it shouldn't be used for all questions related to previewing images on kitty.

**Comment by FugueSoft** [comment]
@xaizek 
Thank you for the response!
I have moved that block above the previous line and even commented the single line out.

I'm still not seeing any images unfortunately

You can see in a newer config: https://0x0.st/8JS7.tmp 
I've been trying quite a bit.

But I'll make a new issue on it
