### ISSUE TITLE
"Rename" functionality not working

### ISSUE THREAD

**Issue by nandox** [vifm/vifm#762]
Today I updated from vifm_0.11 to vifm_0.12, and after using it for a while I noticed that the "rename" command opens correctly the list of files in Vim, but when I save the file list with the name changes, nothing happens, none of the files is renamed. This was working correctly with version 0.11

I use Vifm in Windows 10.

**Comment by xaizek** [comment]
Just tried `:rename` with `shell=bash` and `shell=cmd.exe` on Windows, both seem work fine. Does it fail for you every time? Anything unusual in `'vicmd'`?

**Comment by nandox** [comment]
You found the root cause, it was the vicmd configuration. I was using the following one, which doesn't work with 0.12 (but works with 0.11):

set vicmd="gvim.bat --remote-silent"

I changed it to vicmd=gvim.bat and now things work fine, but I don't have the functionality of one single vim instance running then.

**Comment by xaizek** [comment]
`--remote-silent` doesn't allow waiting for Vim to finish even with `--nofork` option which Vifm adds when it needs to wait for editor to finish. As far as I can tell, it shouldn't have worked in any version. It's possible that it waits when you don't have Vim instance already running and you just didn't notice this isssue before.

**Comment by xaizek** [comment]
Just to reiterate: `gvim.bat` should drop `--remote-silent` if `--nofork` is passed in to preserve correct interaction.

By the way, see [this Lua plugin](https://github.com/vifm/vifm/tree/master/data/plugins/editor) for editors. Won't work with 0.12, needs next release. I haven't tried it on Windows, but should work. It might be easier to handle this in Lua than in a batch file, because plugin just gets "nofork" as a boolean flag.
