### ISSUE TITLE
The character 'r' is missing from the help file

### ISSUE THREAD

**Issue by jeetsukumaran** [vifm/vifm#78]
This is a strange one!

None of the words that should have the letter 'r' in `vifm-help.txt` have them. The upper-case letter, `R` is present: it is just the lower case letter that is missing.

It is probably not a priority, as the the document is still largely readable. The only issue is if some command names or key mappings are wrong. But I thought I would just note it as an issue in case you were not aware. Thanks for a *GREAT* utility!

**Comment by xaizek** [comment]
I wasn't aware of this, thanks. It appears weird unless you know how non-printable characters are stripped on converting man-page into regular text file:
```sh
groff -Tutf8 -man ../data/vifm.1 | col -b | sed -e 's/\x1b\[[0-9]*m//g' -e 's/\r//g'
```
`\r` in `s/\r//g` is not expanded on your system, probably due to older version of `sed`. But if you don't see escape codes in `vifm-help.txt`, `\xHH` are expanded, so maybe replacing `\r` with `\x0d` will do it. Please try `fix-help-file-generation` branch, it might work, if not I'll try to find a better solution tomorrow.

Glad to hear you like vifm!

**Comment by jeetsukumaran** [comment]
Yes, this works now. Thanks!
