### ISSUE TITLE
Fallback to `.desktop` files

### ISSUE THREAD

**Issue by qsmodo** [vifm/vifm#799]
Vifm uses `filetype` to decide which application should open a file. If no matching `filetype` declaration is found, it falls back to `vicmd` (I reckon).

However, if one opens the `file` menu, additional handlers may be available via the desktop entry specification, a.k.a. desktop files.

In my opinion, desktop entries should have precedence over vicmd, at least for non text files, because

1. It isn't reasonable to use a text editor there.
2. If an application gets removed, no need to edit the configuration file, Vifm will seamlessly pick the next one.
3. It's more portable and eases maintaining the whole system, in that with a single `xdg-mime` command one can change the default application handling PDFs for all conforming applications (file-managers, browsers etc.).

**Comment by xaizek** [comment]
That's a rather noticeable breaking change. I for one prefer to see Vim when I accidentally open something rather than an application I've never heard of, but which happens to be installed.

> 1\. It isn't reasonable to use a text editor there.

It depends. Say, PDF files are quite readable and Vim has syntax highlighting for them.

> 2\. If an application gets removed, no need to edit the configuration file, Vifm will seamlessly pick the next one.

The same happens with `filetype`.

> 3\. It's more portable and eases maintaining the whole system, in that with a single `xdg-mime` command one can change the default application handling PDFs for all conforming applications (file-managers, browsers etc.).

Adding `filetype * xdg-open` as the last file type should give the desired behaviour, no? It's in sample `vifmrc`, but commented out.

**Comment by qsmodo** [comment]
Ah, of course, `filetype * xdg-open` does it! Thanks, this is already possible then.
