### ISSUE TITLE
Progress indicator could give ETA information

### ISSUE THREAD

**Issue by jose1711** [vifm/vifm#803]
Percentage and count is useful too but I would really appreciate seeing ETA in progress indicator.

**Comment by xaizek** [comment]
It's an easy thing to add, but I don't want it to be as wrong as it's often is. In my experience two kinds of ETA computations are in widespread use:
 * those which don't reflect immediate speed changes and look lagging
 * those which reflect only immediate speed and change every second in a huge range

Both work well in ideal conditions which rarely occur.

I'd want to find some sliding window/weighted average/etc. way to have an ETA that doesn't look random. ([This](https://stackoverflow.com/q/852670/1535516) might be a starting point.)

**Comment by jose1711** [comment]
Perhaps ETA would show only if operation is running for more than 5 seconds and would look like `approx. 5-7 minutes` where 5 would be the most optimistic and 7 the most pessimistic guess and both numbers would be updated in a defined interval. I think no one is really expecting the numbers to be too accurate to last second when talking I/O so minute granularity is OK.

**Comment by xaizek** [comment]
Finally, done comparing algorithms and added ETA. 5s delay is there. No interval as I don't see a good way of producing one. No rounding to minutes because then on jitter ETA can jump from 1m to 2m and back (when ETA goes between 60s and 61s) and showing seconds is better unless this jumping is handled in some nice way.
