### ISSUE TITLE
would you consider adding `os.getenv`?

### ISSUE THREAD

**Issue by haolian9** [vifm/vifm#829]
hi, me again, i mentioned os.getenv in another issue, but i still think it's worth a new issue.

my usecase is: i'm trying to communicate between nvim lua and vifm lua with a named? pipe, so i have to tell vifm lua where it is. but i failed to find a way to get environment var in vifm lua, nor set/get a custom global variable to vifm.

with latest issues, do you think i'm over using the vifm lua api? i do have this feeling now :sweat_smile:

**Comment by xaizek** [comment]
Hi.

Yes, it will be added. You can use `vifm.expand('$VARNAME')` for now. `os.getenv` is still needed for better API because `expand()` doesn't change its input if variable doesn't exist (also, the need for `$` and non-Lua name).

> with latest issues, do you think i'm over using the vifm lua api? i do have this feeling now 

The API is still early in development. There are many quite basic things which need to be exposed via it. Thanks for pointing some of them out.

**Comment by haolian9** [comment]
ah, `expand`, of course, thank you!
