### ISSUE TITLE
Lua: Segfault upon attempts to open closed pipe

### ISSUE THREAD

**Issue by PRESFIL** [vifm/vifm#830]
## Summary

The error occurs in the Lua-plugin `ueberzug`, apparently due to the fact that
`ueberzug` turns off and closes the channel. The plugin continues to use the
`FILE` of the closed channel, which calls `SEGFAULT` after a while.

## Details

Sometimes I've seen `SIGPIPE` or `Broken pipe` messages. After using GDB and
fiddling with the repository, it became clear that `SIGPIPE` is ignored by
`vifm` and it is not the cause of the crash. It occurs several times in a row,
with each byte sent :) before `vifm` crashes.

Perhaps the Lua-API needs some way to understand that `FILE` is invalid. But
there is no such way in C as far as I can tell. Perhaps it makes sense to write
a `SIGPIPE` handler that will properly close a broken pipe and help the Lua
plugin know about it.

## How to reproduce

1. Install `ueberzug`
2. Install `ueberzug` plugin
3. Launch `vifm`
4. Cd to folder with `*.png`'s
5. Press <kbd>w</kbd> to enable preview
6. Change selected file, enable/disable preview multiple times...
7. Segfault!

## System info

**vifm version:**

```
Version: 0.12.1
Git info: v0.12.1-8-g373df9d31402-dirty
Compiled at: Oct  9 2022 17:02:02

Support of extended keys is on
Parsing of .desktop files is enabled
With GTK+ library
With magic library
With X11 library
With dynamic loading of X11 library
With file program
With -n option for cp and mv
With remote command execution
```

**ueberzug version:** 18.1.9

**Comment by xaizek** [comment]
`SIGPIPE` is ignored precisely to not crash with unhandled signal in such cases, but I haven't noticed the crashes when was testing this or maybe they started appearing later.

I can reproduce it now if I edit command to run `ueberzug` to something that doesn't exist, thanks for the report.

I guess, you haven't added `$HOME/.local/bin` to your `$PATH`, otherwise `ueberzug` would start. The way it works is that pipe is kept open all the time, it's when the command fails to start there is no pipe at all and you get `SIGPIPE`, which used to close Vifm on hovering the first image file.

**Comment by PRESFIL** [comment]
> I guess, you haven't added $HOME/.local/bin to your $PATH, otherwise ueberzug would start.

My `ueberzug` is `/usr/bin/ueberzug`. It's works with `vifmimg`.

It looks like `ueberzug` starts up and immediately crashes.  I'm
more concerned that the Lua-plugin is unable to detect this. And
he can call `SEGFAULT`. This isn't due to `SIGPIPE`, but after some
retries later (see _How to reproduce_).

My meager GDB skills didn't help me localize the root of problem.

**Comment by xaizek** [comment]
Looks like it's because `job_stream_gc()` calls `bg_job_decref()`, while `jobstream_closef()` whould be doing it. I think this is a leftover from a different ownership model for streams. What happens in this bug is:
1. Lua garbage-collects job object (even though it's still reachable, but maybe Lua deduces that it won't be used).
2. It removes C-level job which closes streams along the way.
3. Lua uses streams thinking that they are still valid and this crashes eventually.

**Comment by PRESFIL** [comment]
> I'm more concerned that the Lua-plugin is unable to detect this.

I found something in the Lua documentation, maybe this is how SIGPIPE can be detected:

**Comment by PRESFIL** [comment]
> I'm more concerned that the Lua-plugin is unable to detect this.

I found "it's in the documentation", maybe this is how SIGPIPE can be detected.
Maybe it will be more useful after `pcall(...)` support is implemented

> file:write(···)
> 
> Writes the value of each of its arguments to file. The arguments must be strings or numbers.
> 
> In case of success, this function returns file. Otherwise it returns nil plus a string describing the error.

But for my case `print()` displays 

```
file(0x.....)
```

what says that no error occurred?

**Comment by xaizek** [comment]
New behaviour: streams are functional until Vifm detects the job has exited, then streams are closed and Lua raises an error if you try to do something with it.

> Maybe it will be more useful after `pcall(...)` support is implemented

 It should work as is.

> what says that no error occurred?

I'm not sure what `fwrite()` returns on a `SIGPIPE`, but looks like it's `> 0`.

**Comment by PRESFIL** [comment]
> I'm not sure what fwrite() returns on a SIGPIPE, but looks like it's > 0.

It shouldn't. But I was looking for a way to at least return something and
signal an error (because there are no exceptions in Lua).

**Comment by PRESFIL** [comment]
> It should work as is.

You fix works as is! I think this is a topic for a separate issue.
