### ISSUE TITLE
unable to map `<c-/>`

### ISSUE THREAD

**Issue by haolian9** [vifm/vifm#834]
hi, i tried to map `<c-/>` in two ways, and tested them in terminal st and kitty, but none of them works.

* `:nnoremap <c-/> :echo 'hello'<cr>`
* `assert(vifm.keys.add({
      shortcut = '<c-/>',
      modes = { 'normal' },
      handler = function() vifm.sb.info('hello') end,
    }))`

i'm using the default configuration of kitty 0.26.4; for st 0.8.5, i have changed `<c-/>` to `CSI u`, `\x1b[47;5u`, according to [this article](http://www.leonerd.org.uk/hacks/fixterms/).

do you think there are something wrong in my setup? or it's a problem specific to vifm?

**Comment by xaizek** [comment]
Hi.

Trying <kbd>Ctrl+V</kbd> <kbd>Ctrl+/</kbd> in bash in xterm gives me `^_` (`\x1f`) and mapping `<c-_>` works as `<c-/>` in Vifm. `<c-/>` isn't handled (not listed [here](https://vifm.info/vimdoc.shtml#vifm-mappings)).

**Comment by xaizek** [comment]
I was thinking about using `define_key()` of ncurses (https://github.com/vifm/vifm/pull/636#issuecomment-765509184), which is probably a better way than using `bracket_notation.c`, but I haven't figured out how portable it is and didn't try it either.

The problem is the sequences are terminal-specific and hard-coding them is not great. Just mapping `<esc>[47;5u` should work essentially the same as extending `bracket_notation.c`.

**Comment by haolian9** [comment]
wow, lhs `<esc>[47;5u` works! never thought this approach, but after i tried what i said before, i understand what you mean immediatly, haha.
had a look at there, i'm fine with `<esc>...` lhs.
