### ISSUE TITLE
ViFM in Alacritty / Cursor in Commandline Mode

### ISSUE THREAD

**Issue by Grueslayer** [vifm/vifm#845]
At least on Windows the cursor is not displayed correctly using ViFM under Alacritty (works fine in default CommandLine / new Windows Terminal / ConEmu):

If you typing `:` switching to Commandline mode and entering multiple characters, the cursor correctly moves further to the right to the end of the line.
But if you moving the cursor to the left and later to the right (using cursor keys), it is still displayed at the very end of the line.
Newly entered chars will be inserted at the right position, you can see the cursor flickering short at the correct position, but being display at the end afterwards.

**Comment by Grueslayer** [comment]
same bahaviour using "Contour" (except cursor shape is correct)

**Comment by xaizek** [comment]
This sounds like it might be an issue with those terminals. If it works in other terminals, then `SetConsoleCursorPosition()` must have been called correctly. Alacritty/Contour might move the cursor on a draw operation, would be nice to confirm it with some other application.

**Comment by bitraid** [comment]
This is probably because they (Alacritty/Contour) use the new ConPTY API which has some issues. The new Windows Terminal contains/uses a more recent version of ConPTY, while the default/old Windows terminal and ConEmu use the old (ConHost) API. See https://github.com/alacritty/alacritty/pull/4501 on how to use ConPTY from the new Windows Terminal with Alacrity.

**Comment by xaizek** [comment]
> works fine in default CommandLine / new Windows Terminal / ConEmu

Seems to contradict the speculation about API.

**Comment by bitraid** [comment]
default CommandLine, ConEmu: conhost
Alacritty, Contour: ConPTY which ships with Windows 10+ (and has issues - see https://github.com/alacritty/alacritty/issues/5693 for a similar example)
New Windows Terminal: newer version of ConPTY (with fixed issues).

**Comment by bitraid** [comment]
If I'm right, [WezTerm](https://github.com/wez/wezterm) should also work, because it includes and uses `openconsole.exe` and `conpty.dll` from the New Windows Terminal package. The affected terminals should be the ones that use the version of ConPTY that comes with Windows. Legacy (conhost) terminals like Cmder and ConEmu should also work without issues.

**Comment by xaizek** [comment]
Thanks, I missed there are two versions of the API and two implementations of the new one, making three variants in total. Will need to look more into this and what it means in terms of dependencies if this actually fixes the issue.

**Comment by Grueslayer** [comment]
Hi, just applied the mentioned patch (needs some tweaks cause they replaced winapi by windows_sys) and it runs fine. The maintainers of alacritty don't want to apply that simple patch despite it makes no harm: As long you don't have a conpty.dll in path it (which you haven't because it will be linked static in default installation from windows) works like standard [But this is another case].

I'll close this, cause it's alacrittys fault (and they'll blame MS).

**Comment by xaizek** [comment]
Hm, I actually thought loading that library into Vifm might help. If it's only on the side of the terminal, there is nothing to do here.
