### ISSUE TITLE
expand function will have escape char `\`

### ISSUE THREAD

**Issue by NEX-S** [vifm/vifm#848]
`set statusline=" [ %u ] [ %{ expand('%d:~') }  %E ] %= [ %A ] [ %d ] "`

![image](https://user-images.githubusercontent.com/97107165/204911516-123132e2-77ea-48bc-ab01-4592ccc2b8d3.png)
will show `\` near `~` :sob: I've tried to solve it by reading the doc but I didn't find the way to do that :(

**Comment by xaizek** [comment]
Yes, `expand()` escapes its result, because it's primary use is to format shell commands like in:
```vim
set statusline=" [ %u ] [ %{ system(expand('echo %d:~')) }  %E ] %= [ %A ] [ %d ] "
```
However, this will run a shell on every update of the statusline. `extcached()` can help, but I should probably add second parameter to `expand()` to disable escaping. It shouldn't be doing escaping, but too late to change that.

A better workaround is to use a Lua plugin like:

```lua
-- assumming saved as $VIFM/plugins/sbar/init.lua, use like `set statusline=#sbar#format`

local added = vifm.addhandler {
    name = "format",
    handler = function()
        local cwd = vifm.fnamemodify(vifm.currview().cwd, ':~')
        return { format = " [ %u ] [ "..cwd.."  %E ] %= [ %A ] [ %d ] " }
    end
}
if not added then
    vifm.sb.error("Failed to register #format handler")
end
```

Also an overkill in this case, but better than running an external command too often and is more customizable.

**Comment by xaizek** [comment]
> can we use init.lua instead of using vifmrc to setting some options and keybindings?

`vifmrc` is for configuration, Lua API is for extensions. Maybe Lua will become more suitable as an alternative for configuration in the future, but it's definitely not there yet. In particular setting `'number'` will at least need:
```lua
vifm.currview().locopts.number = true
vifm.currview().viewopts.number = true
vifm.otherview().locopts.number = true
vifm.otherview().viewopts.number = true
```
but really needs to iterate over each view in all tabs (which is doable via `vifm.tabs`, but isn't worth the trouble).
