### ISSUE TITLE
:copy, strange blinking in the middle of the screen

### ISSUE THREAD

**Issue by ranousse** [vifm/vifm#87]
Each time I use :copy, I notice that during a fraction of second vifm shows in the middle of the screen a message (as when there's a warning message). It's very short, so I just see a kind of blinking.
It seems strange anyway.

I use the last git version. This behaviour is new (it appeared one or two days ago I think)

**Comment by xaizek** [comment]
That's progress dialog, not an error. It turned out to be quite annoying for fast operations, when you can't even read what it says. I'm thinking about displaying progress on status bar as before and displaying dialog only after user hits some key (say, <kbd>d</kbd>, for *d*etails). This "additional information on request" should be less confusing and annoying.

**Comment by xaizek** [comment]
Done, I decided to use <kbd>i</kbd> for safety reasons, to prevent accidental deletion of files.
