### ISSUE TITLE
Operations in ":jobs"

### ISSUE THREAD

**Issue by SylEleuth** [vifm/vifm#877]
If I want to stop operation in ```:jobs``` I have to just delete it with ```dd```. But there in no indication of stopping it and process is still visible after that, which is confusing. Would it be possible to add some confirmation? Ask if I want to stop or some information after stopping (and removing from the list)?

**Comment by xaizek** [comment]
There is an indicator in a form of ` (cancelling...)` being appended to the entry. Maybe putting it in front would be easier to notice.

A job doesn't react to cancellation immediately and might completely ignore it, which is why jobs can't be just dropped from the menu. The menu isn't interactive so the job won't be there only on the next run of the menu after the job has actually finished.

Do you worry that you'll cancel something by accident and want confirmation for that?

**Comment by SylEleuth** [comment]
I was testing with a really long folder (cause I had a big files in there) and information was out of the window. I'm also using vifm in drop-down terminal and it takes quarter of the screen so it would be much better if info was at the beginning of the job.

**Comment by xaizek** [comment]
Moved the mark and added <kbd>r</kbd> key to reload the list of jobs without leaving the menu.
