### ISSUE TITLE
Adding column "type" crashes vifm

### ISSUE THREAD

**Issue by beli-sk** [vifm/vifm#89]
Hi,
I managed to crash vifm just by adding a column `{type}`

```
:windo set viewcolumns=-{name}..,6{size},6{type}
```

resulted in a crash with error message

```
vifm: column_view.c:183: columns_add_column: Assertion `column_id_present(info.column_id) && "Unknown column id."' failed.
```

Furthermore, contents of column `{mode}` looks like it belongs in column `{type}`. They seem to be mixed up somewhere.

Tested against latest pull from master branch.

**Comment by xaizek** [comment]
Hello,

thanks, forgot to add column description after adding this sorting key. Will change code so it won't compile if I do this again in the future.

> Furthermore, contents of column {mode} looks like it belongs in column {type}. They seem to be mixed up somewhere.

Well, they overlap. `mode` existed for a long time, but it doesn't affect ordering of files and directories, `type` was introduced to overcome this. The name `mode` comes from corresponding field of the `stat` structure, which in addition to permissions contains file type.
`type` basically differentiates only between files and directories ignoring the rest (this is intentional, so that what `type` added implicitly it doesn't cause unexpected results in presence of sockets/fifo/etc.). This is more of a terminology issue.

It might make sense to make these two synonyms in context of view columns.

**Comment by beli-sk** [comment]
Ok, but I thought `mode` would look more like e.g. `0644`, but instead it shows `dir` for a directory and `reg` for a regular file.

**Comment by xaizek** [comment]
I agree, it is confusing to me as well (I didn't write this). Maybe it's worth to rename values in incompatible way, this will cause some inconvenience, but as it's just sorting, nothing bad will happen. Something like:
 * rename current `type` to `dirs`;
 * rename current `mode` to `type`;
 * use `mode` to display actual mode in octal.

**Comment by beli-sk** [comment]
Perfect!
