### ISSUE TITLE
Windows: attempting to create/delete directory in C:\ results in error

### ISSUE THREAD

**Issue by theorlangur** [vifm/vifm#896]
attempting to create a new folder in the root of `C:\` under Windows produces a message box with an error `Destination directory is not writable`.
Attempting to delete a directory issues a similar message: `Current directory is not writable`.
As it seems the problem lies in the `fs.c:389`, `is_dir_writable` function call. That elaborate call to CreateFileW is prohibited for some reason for `C:\` but at the same `_wmkdir`, `_wrmdir`, `_wchdir` work just fine and do the necessary thing without problems.
Question: does it have to be `CreateFileW` under Windows? 
Wouldn't it be more convenient to check just for existence via `os_access` call?

Or is there maybe some other solution to this?

**Comment by xaizek** [comment]
`CreateFile` was introduced in bd3b412424 to "fix check of directory write permissions on Windows", because `access()` check didn't work.

@bitraid, thanks for clarifying things.  Don't want to create directories to do the check, so `AccessCheck` should probably be used.  Differentiation between file and directory write operations likely needs to be introduced.

**Comment by theorlangur** [comment]
I read that _waccess doesn't actually check access, only the existence of a directory. I thought that maybe it would be ok to just let the subsequent call to e.g. `_wmkdir` fail and report that failure then. But I admit I have no idea what other use cases this would break. It just seems way easier than diving into the whole [AccessCheck](https://learn.microsoft.com/en-us/windows/win32/api/securitybaseapi/nf-securitybaseapi-accesscheck) thing.

**Comment by xaizek** [comment]
I think the purpose of 6bf587c64b was to give a more user-friendly message and avoid showing things like confirmation dialog when no operation is possible.  It can be dropped in favour of showing errors, but I'll try using `AccessCheck` first.

**Comment by xaizek** [comment]
Fixed via `AccessCheck()` by considering a directory writable if you can delete or add something in it, which is not that much different from Unix systems due to sticky bit (well, and ACLs).

CI builds can be found at https://builds.vifm.info/.  Noticed that 32-bit builds don't error like that, likely due to WoW64, so using 32-bit 0.13 could be a workaround in case the bug is annoying.  Now I also seem to remember that when I tried to reproduce the issue after hitting it, it confusingly wasn't there, so I must have used 32-bit version for a test.
