### ISSUE TITLE
Suppress output while opening a file

### ISSUE THREAD

**Issue by loonies** [vifm/vifm#90]
Is there any way of suppressing all the output messages while opening a
file, preferable as a global setting? I didn't find anything related in
the documentation.

For example, Gimp throws a bunch of errors about optional missing
dependencies. This is the _filetype_ definition for opening files with
Gimp in my `vifmrc` file:

    filextype *.jpg,*.jpeg,*.gif,*.png,*.bmp,*.xcf
        \ {Edit in GIMP}
        \ gimp %f > /dev/null 2>&1 &

but I'm still getting errors output. I'm I missing something?

Running Vifm 0.7.8

**Comment by xaizek** [comment]
There is [`%i` macro](http://vifm.info/vimdoc.shtml#vifm-%25i), but it's not global and one should put it in every command that produces uninteresting output.

Global setting might hide errors from you so that you won't even know that something went wrong, e.g. say you run `tar cvf %c:r.tar %f &` from `:filetype` and some of selected files can't be read. Theree could be an option for this, but anyone who would use it should be careful while adding new commands.

> gimp %f > /dev/null 2>&1 &

This should work the same way as `%i`, works here. Maybe you have other definition above that overwrites this one or configuration wasn't reloaded.

**Comment by loonies** [comment]
My bad, I was opening a PhotoShop file with Gimp, which was not defined
in the aforementioned `filextype` rule, but was handled by the last,
"catch all" rule:

    filetype *
        \ {System association}
        \ xdg-open

Another thing. In case of using _%i macro_ as suggested, you can't send
a program in the background as noted in the documentation:

> Note that %m, %M, %s, %S and %i macros have bigger priority than &. So
> command containing at least one of them can't be backgrounded and " &"
> at the end will be just silently ignored.

Correct?

**Comment by xaizek** [comment]
> > Note that %m, %M, %s, %S and %i macros have bigger priority than &. So
> > command containing at least one of them can't be backgrounded and " &"
> > at the end will be just silently ignored.
> 
> Correct?

Hm, it's inconsistent. The paragraph is correct for `:!`, but not for `:file[x]type`. What we really have is:

 * Anywhere except `:file[x]type` `%m`, `%M`, `%s`, `%S` and `%i` macros have bigger priority
than `&`.
 * In `:file[x]type` commands `%m`, `%M`, `%s`, `%S` macros are ignored and `%i` forces
ignoring messages from backgrounded applications.

I don't think this is intentional. These two cases should be merged to get behaviour as in `:!`, but with `%i` not disabling `&` (`&` is really odd if we make menu or something, but combines fine with `%i`). And maybe display error on combinations that don't make much sense.

**Comment by loonies** [comment]
_%i makros_ works great. Thanks for detailed explanation.
