### ISSUE TITLE
Sorting is to difficult

### ISSUE THREAD

**Issue by ghost** [vifm/vifm#904]
Hi. 
I like vifm, I really do. 
But I'm struggling how to sort the view of the panels. 
I want to have mixed directories and files, sorted alphabetically, ignore cases and correct placement of files and dirs that begin with umlauts like the german ä, ö and ü. 

I can type 
`:sort`
and hit Enter to get a list I can choose from, but not the way I wanted (except sorting by name ignore case). 

When I run 
`:set sort=+name,dir`
I get mixed dirs and files but adding an i to it to ignore case doesn't work, not to mention, that all umlauts are at the bottom... 

Help.... :.(

**Comment by xaizek** [comment]
Hello,

```vim
set sort=+iname,dir
```
should ignore the case.  Picking `Name (ignore case)` in the sort dialog just sets `sort` option to `iname`.

> Sorting is to difficult

`:sort` is meant to be simple while `:set sort=...` is meant to be flexible.

> all umlauts are at the bottom

That's probably because that's how code points in Unicode are ordered.  Vifm does simple byte comparison of UTF-8 strings, which doesn't take Unicode craziness into account and even produces different results depending on how a character is encoded (umlauts can be either characters of their own or a combination of a normal character and dots, a.k.a. "craziness").

The problem is that there is probably no simple way of doing comparison properly and it requires huge pain-in-the-ass libraries (ICU).  Vifm, however, optionally depends on GTK/GDK for mime type detection, maybe it can also be used to sort things using  language-specific collation when available.  I've never thought of that before.

**Comment by hacksenwerk** [comment]
Ah thank you very much iname does the trick!

That sounds complicated what you wrote about utf-8... 
My graphical filemanager (pcmanfm at the moment) handles it like I described it in my first post, it treats ä as a, ö as o and ü as u.

Best Regards

**Comment by xaizek** [comment]
So, Vifm incorrectly optionally depended on GTK while it has actually ever used GDK...  That was fixed months ago, but this issue helped to figure this out.

Regarding improving sorting.  I've imported `utf8proc` library which is now used to normalize completion items and file names in views on sorting (these two better agree with each other).  This is not a proper collation because as mentioned above Unicode is quite anal.  In particular, it doesn't support case-sensitive collation, so if employed there will be no case-sensitive sorting or `iname` and `name` will differ wildly.  This is why it's normalization followed by byte ordering, which takes care of multiple ways to write the same symbol, but some will still be in the wrong place (e.g. German `ß`; but `ä`, `ü` and `ö` should be handled well now).

Taking this further requires collation function that can behave in a case-sensitive way.  `utf8proc` has no collation as of now, so no option to modify it to do that (and I don't know how easy that would be).  This might also allow tweaking relative ordering of symbols, which was requested couple times and can be done in a naive way but will be slow without a collation function that produces a buffer that can be compared via `strcmp()`.  I haven't looked much into this anyway because this Unicode stuff was in the making on and off since this issue was opened and I'm quite sick of Unicode by now.
