### ISSUE TITLE
vifm.startjob() does not support to allocate a tty

### ISSUE THREAD

**Issue by haolian9** [vifm/vifm#908]
hi, i'm trying to integrate fzf into vifm so that i can cd in a directory more quickly, it can be speaked in shell like this:
```
cd $(find -type d | fzf)
```

so there are two things will be needed: a tty for fzf, the stdout of fzf.
and i have tried `vifm.run`, `vifm.startjob` and `io.popen`, but unfortunatelly none of them fits this usecase: `.run()` allocates a tty, but returns no stdout; `.startjob()` gives job.stdout() but  allocates no tty; `io.popen()` suffers the same as `.startjob()` does.

although there are workarounds outside vifm i'm aware of right now:
* redirect the stdout to a file and read it from vifm later
* use `tmux display-popup` to eliminate the need of tty for the process spawned by vifm

i'm still wondering if it's worth to do it using vifm's lua api solely.

**Comment by xaizek** [comment]
Hi.

> `.run()` allocates a tty, but returns no stdout

It just doesn't detach child process from the TTY used by Vifm.

> `.startjob()` gives job.stdout() but allocates no tty

This was intentional, although a flag for TTY access is possible.  There can be many background jobs at the same time and it's undesirable to let them mess with the terminal.

> `io.popen()` suffers the same as `.startjob()` does.

This one should actually work.  It comes directly from Lua.  You command probably lacked some redirection.

`vifm.run()` works like `:!` and probably shouldn't try to return an output because it can't always do it (due to a terminal multiplexer), but there can be `vifm.system()` for that.
