### ISSUE TITLE
nmap <c-h> <c-w>h doesn't seem to work

### ISSUE THREAD

**Issue by fogine** [vifm/vifm#91]
I set following line in my vifmrc file:
`nmap <c-h> <c-w>h` - it does not work for me
`nmap <c-j> <c-w>j` - it's not binded as well
but `nmap <c-l> <c-w>l` - works fine
`nmap <c-k> <c-w>k` - works fine as well - it's binded

I checked `:nmap` ...and those mappings which don't work are not listed there.
But I can see that there is build-in shortcut `<c-l>` binded to something... don't know what it does...

**Comment by xaizek** [comment]
Hm, was puzzled why I was sure it works when it didn't and understood: it used to work in xterm, but not inside tmux, and it's the opposite now... I'll probably make `<c-h>` and `<bs>` differ, and let user figure out which one works, otherwise there will be a case when one can't bind the key at all.

> nmap <c-j> <c-w>j - it's not binded as well

Seems to work, although might not be displayed properly in the menu due to special meaning of this key.

> But I can see that there is build-in shortcut <c-l> binded to something... don't know what it does...

Redraws the screen, as in shell and a lot of other terminal applications.

**Comment by xaizek** [comment]
`<c-j>` should be displayed properly now.

`<c-h>` and `<bs>` differ now (see updated docs for details), but only one of them will work in each environment (probably, I haven't seen them both working). So it's advised to map to both of them and it should work on all systems/terminals.

Thanks.
