### ISSUE TITLE
[FEATURE REQUEST]  Provide a built-in fuse archive mounter to easily mount every archives in every distro

### ISSUE THREAD

**Issue by thealio** [vifm/vifm#932]
Hi, 

in vifm , the archive mounting is provided by fuse archive mounter (for example fuse-7z and fuse-zip)

Not all the distros ships all the related packages, I assume . 

Surely, Arch Linux doesn't provides fuse-7z .

For made this fantastic file manager  more compete and usable out of the box, I'd like a fuse mounter to be included by default.

A good choice could be integrate fuse3-p7zip

https://github.com/andrew-grechkin/fuse3-p7zip

**Comment by xaizek** [comment]
Hello.

Including one project into another as a workaround for lack of packages doesn't sound like a good idea.  It will combine dependencies, complicate build process and packaging.  FUSE mounters also primarily target GNU/Linux and might not be used on other systems.  The actual effect would likely be reduced packaging of Vifm or building it without the mounter.

Contributing a package is an easier and more scalable approach, even if somewhat annoying.  An alternative is to build an AppImage with `fuse3-p7zip` which will work in most distributions.

**Comment by thealio** [comment]
> Hello.
> 
> Including one project into another as a workaround for lack of packages doesn't sound like a good idea. It will combine dependencies, complicate build process and packaging. FUSE mounters also primarily target GNU/Linux and might not be used on other systems. The actual effect would likely be reduced packaging of Vifm or building it without the mounter.
> 
> Contributing a package is an easier and more scalable approach, even if somewhat annoying. An alternative is to build an AppImage with `fuse3-p7zip` which will work in most distributions.

If you don't consider this convenient , it's OK

I  thought that at the least this  it could be done providing a compiling option just for Linux  

Appimage is not the way, at the least  the users can try to compile fuse3-p7zip for their disto, but I'd like a more out of the box solution for archive management in vifm (at the least on GNU/Linux)

**Comment by xaizek** [comment]
The issue with compiling options is that they make things harder for package mainterners as they need to decide whether to enable or disable those options.  In this case when only build process is affected, that might be an easier choice (althought it introduces runtime dependencies), but it makes the result basically equivalent to providing Vifm and FUSE mounter packages separately, so bundling them together doesn't really achieve anything except for limiting the mounter to usage in Vifm only.  That's why it's just better to have a separate package.  More people should become maintainers to make things easier, it's hard to deal with your first package, but then it much less of a problem.

> I'd like a more out of the box solution for archive management in vifm (at the least on GNU/Linux)

Are you reinstalling your system often or using many different systems?  Usually this needs to be setup only once.

**Comment by thealio** [comment]
> The issue with compiling options is that they make things harder for package mainterners as they need to decide whether to enable or disable those options. In this case when only build process is affected, that might be an easier choice (althought it introduces runtime dependencies), but it makes the result basically equivalent to providing Vifm and FUSE mounter packages separately, so bundling them together doesn't really achieve anything except for limiting the mounter to usage in Vifm only. That's why it's just better to have a separate package. More people should become maintainers to make things easier, it's hard to deal with your first package, but then it much less of a problem.
> 
> > I'd like a more out of the box solution for archive management in vifm (at the least on GNU/Linux)
> 
> Are you reinstalling your system often or using many different systems? Usually this needs to be setup only once.

Hi,
I use Arch & Arch based distros.

**Comment by xaizek** [comment]
> Hi,
> I use Arch & Arch based distros.

Hi,

Then adding desired package to AUR sounds like the best course of action to me.  From what I've seen those are just bash-files with simple functions, so it shouldn't be hard especially if you start with some other package as a template.

Embedding a runtime dependency needs some strong reason beyond simple convenience because of the cost it incurs, so I'll close this as "not planned".

**Comment by gl-yziquel** [comment]
I'd like this feature in OSX and MacPorts.

**Comment by xaizek** [comment]
> I'd like this feature in OSX and MacPorts.

I think it needs a kernel module, would be really weird to include that in a file manager.  Apple also makes it hard to use such modules and workarounds are used by something like https://github.com/macos-fuse-t/fuse-t which isn't even open-source.

This is why I don't think it's a good idea in general, stuff would pile up pretty quickly and managing it would become hard (even for a single family of OSes).
