### ISSUE TITLE
Building under OpenBSD

### ISSUE THREAD

**Issue by hofheinz** [vifm/vifm#97]
Hi xaizek,

I'm trying to build and run vifm (current version on github) under OpenBSD 5.7 (the current release version of it). (Sorry if this scenario is not on the vifm agenda, but I thought it would be great to have an up-to-date version of vifm on OpenBSD. Sadly, the version in the OpenBSD ports/packages system is 0.4. Unfortunately, the patches from that port that make 0.4 build are pretty useless for 0.7.8 or 0.8 beta.)

Since your recent commit on src/utils/mntent.c, the build in fact succeeds, it's possible to start vifm and browse around directories, but entering the command line (with ':') seems to lock up vifm. (No ':' displayed, further keypresses ignored. It doesn't help to bind, e.g., :quit, to another key.) This is with an empty vifmrc, and on a real (i.e., non-qemu/-VirtualBox) amd64 installation.

Looking at a ktrace (OpenBSD's systrace) output, the last few syscalls before locking up are:
```
[...]
  3674 vifm     1434908355.657606 CALL  sigaction(SIGTSTP,0x14070a993d90,0)
  3674 vifm     1434908355.657615 STRU  struct sigaction { handler=SIG_IGN, mask=0<>, flags=0x2<SA_RESTART> }
  3674 vifm     1434908355.657619 RET   sigaction 0
  3674 vifm     1434908355.657625 CALL  sigaction(SIGTSTP,0x14070a993da0,0x14070a993d90)
  3674 vifm     1434908355.657630 STRU  struct sigaction { handler=SIG_IGN, mask=0<>, flags=0x2<SA_RESTART> }
  3674 vifm     1434908355.657634 STRU  struct sigaction { handler=SIG_IGN, mask=0<>, flags=0x2<SA_RESTART> }
  3674 vifm     1434908355.657639 RET   sigaction 0
  3674 vifm     1434908355.657644 CALL  poll(0x7f7ffffc0810,1,0)
  3674 vifm     1434908355.657649 RET   poll 0
  3674 vifm     1434908355.657665 CALL  poll(0x7f7ffffc0810,1,0)
  3674 vifm     1434908355.657672 RET   poll 0
  3674 vifm     1434908355.657754 CALL  write(1,0x14076d8d5510,0x9f)
  3674 vifm     1434908355.657782 GIO   fd 1 wrote 159 bytes
       "\^[[0;1m\^O\^[[30m\^[[47m  ..                                                           512 B       drwxr-xr-x r\
        oot:wheel       47 files filtered  \^[[35;97H\^[[39;49m\^[[m\^O"
  3674 vifm     1434908355.657803 RET   write 159/0x9f
  3674 vifm     1434908355.657815 CALL  sigaction(SIGTSTP,0x14070a993d90,0)
  3674 vifm     1434908355.657828 STRU  struct sigaction { handler=SIG_IGN, mask=0<>, flags=0x2<SA_RESTART> }
  3674 vifm     1434908355.657834 RET   sigaction 0
  3674 vifm     1434908355.657848 CALL  sigprocmask(SIG_BLOCK,~0<>)
  3674 vifm     1434908355.657852 RET   sigprocmask 0<>
  3674 vifm     1434908355.657864 CALL  mprotect(0x1404f4baa000,0x2000,0x3<PROT_READ|PROT_WRITE>)
  3674 vifm     1434908355.657899 RET   mprotect 0
  3674 vifm     1434908355.657921 CALL  mprotect(0x1404f4baa000,0x2000,0x1<PROT_READ>)
  3674 vifm     1434908355.657928 RET   mprotect 0
  3674 vifm     1434908355.657932 CALL  sigprocmask(SIG_SETMASK,0<>)
  3674 vifm     1434908355.657936 RET   sigprocmask ~0x10100<SIGKILL|SIGSTOP>
  3674 vifm     1434908365.186187 PSIG  SIGTERM caught handler=0x1404f486f430 mask=0<>
[...]
```
(No idea what this means...)

Any idea what I could do to debug this? (Do you want additional information? Or maybe this is a deeper problem?)

**Comment by xaizek** [comment]
Hi hofheinz,

I just merged in changes made by @ibara without trying them on OpenBSD. I actually thought that it builds there fine before.

I've downloaded OpenBSD image to try it myself and what I see is very strange. vifm hangs on its first call to curses function that processes wide strings. And the reason of the hang is that *there is nothing but infinite loop in place of wide functions* inside `libncursesw.so.14.0`.

I suspect that this hack is to fix compilation of programs that require wide functions even when they are absent. And if you install `libncursesw` (note trailing `w`), everything should work. But I didn't try that, because can't find a way to install it (my first time using OpenBSD).

Does this sound reasonable? I.e. is there a way to install real libncursesw in OpenBSD, because by default there are just stubs that hang (this is not a good idea, really, it would be better if application terminated with a message).

The command I used is `objdump -d /usr/lib/libncursesw.so.14.0 | less -p mvwaddwstr`, and its output is below, in case you'll want to check particular library:
```
[...]
0000000000015070 <mvwaddwstr>:
   15070:       eb fe                   jmp    15070 <mvwaddwstr>
   15072:       66                      data16
   15073:       66                      data16
   15074:       66                      data16
   15075:       90                      nop
   15076:       66                      data16
   15077:       66                      data16
   15078:       66                      data16
   15079:       90                      nop
   1507a:       66                      data16
   1507b:       66                      data16
   1507c:       90                      nop
   1507d:       66                      data16
   1507e:       66                      data16
   1507f:       90                      nop
[...]
```

**Comment by hofheinz** [comment]
Wow, this is really strange. (Thanks for the objdump pointer btw! I can confirm the output and the infinite loop.)

I also don't have much OpenBSD experience, but there seems to be no package or port for ncursesw. (Installing from source would probably not be a good idea.) UTF-8 support in OpenBSD is not optimal:
  http://www.openbsd.org/faq/faq10.html#charset
("Few utilities in the base system support UTF-8 at this time.") Also, regarding ncurses specifically, I found this comment
  http://openbsd-archive.7691.n7.nabble.com/ncurses-with-wide-character-support-ncursesw-td123580.html
(which is 8 years old however).

Mmh, so I'm not sure, but I guess at this point there's not much that can be done. Thanks for looking into this, though!

**Comment by hofheinz** [comment]
...however, what is weird is that there is even an OpenBSD manpage for that function: man 3 curs_addwstr yields
NAME
       addwstr, addnwstr, waddwstr, waddnwstr, mvaddwstr, mvaddnwstr,
       mvwaddwstr, mvwaddnwstr - add a string of wide characters to a curses
       window and advance cursor

SYNOPSIS
       #include <curses.h>

       int addwstr(const wchar_t *wstr);
       int addnwstr(const wchar_t *wstr, int n);
       int waddwstr(WINDOW *win, const wchar_t *wstr);
       int waddnwstr(WINDOW *win, const wchar_t *wstr, int n);
       int mvaddwstr(int y, int x, const wchar_t *wstr);
       int mvaddnwstr(int y, int x, const wchar_t *wstr, int n);
       int mvwaddwstr(WINDOW *win, int y, int x, const wchar_t *wstr);
       int mvwaddnwstr(WINDOW *win, int y, int x, const wchar_t *wstr, int n);

DESCRIPTION
       These routines write the characters of the (null-terminated) wchar_t
       character string wstr on the given window.  It is similar to
       constructing a cchar_t for each wchar_t in the string, then calling
       wadd_wch for the resulting cchar_t.
[...]

This is a bit misleading... (it does say "Note that all of these routines except waddnwstr may be macros.", but macro would be a bad name for "infinite loop".)

**Comment by hofheinz** [comment]
(sorry for the spam...)

Judging from
  https://groups.google.com/forum/#!topic/fa.openbsd.tech/Q9xGzgQw5rg
someone did prepare a patch to add the wide character functions in 2010, but this patch did not get in. Weird.

**Comment by xaizek** [comment]
It seems to be easier to make libncursesw optional in vifm, which turns out to not be a problem (there is actually only four wide functions used).

See `no-wide-chars` branch for proof of concept. This is just a quick try, but it won't take much to make it look better and make it OpenBSD specific (not sure how to check for this fake ncursesw in autoconf, so maybe just check for OpenBSD explicitly). Vifm built from that branch doesn't hang for me anymore.

**Comment by hofheinz** [comment]
Hey, that's fantastic, thanks for your work on this! I tried out the no-wide-chars branch, and here's a preliminary report: building works (of course), there are no hangs anymore. (I tested a few standard operations, copying, moving, deleting, etc., work both with syscalls and with nosyscalls.) However, so far, I've noticed two things:
 - there are lots of core dumps on funny keys: press, e.g., ctrl-left (or ctrl-right etc.; actually already c "works reliably" to produce a core dump), and the core dumps.
 - maybe (probably) this is just OpenBSD here, but just browsing directories and moving up and down feels way more sluggish than under Linux. ("top" says that vifm hogs a lot of cpu, in the high one-digit percent range when just browsing, but a trace looks like it's mostly lstat calls. I might be missing something of course, and probably it's just OpenBSD, but I thought I'd mention it anyway.)

I'll try a bit more later.

**Comment by xaizek** [comment]
Thanks for giving it a try.

> there are lots of core dumps on funny keys

Looks like those are not handled by ncurses, so vifm sees them as at least two keys, tries to display partially typed sequence and crashes due to stack overflow. Added change to the branch to fix this "typo" that caused stack overflow.

> a trace looks like it's mostly lstat calls

One `lstat` call per file, this is a small issue on GNU/Linux as well, noticeable for huge directories that include 100k files or more. I'm not sure what can be done here. Don't see a caching strategy that won't lead to displaying outdated meta-information at some point. And lazy loading is not convenient because each update might result in reordering of files in the view.

**Comment by hofheinz** [comment]
Did you push the change (fixed typo) to the branch? (I don't seem to be able to pull any changes.)

**Comment by xaizek** [comment]
Right, I forget to push, sorry about that.

**Comment by hofheinz** [comment]
Thanks! No more core dumps no as far as I can see. (I'll try some more in the next days.) One curious thing about the sluggishness: experimenting some more, I don't think anymore that the lstats are the problem. (Thanks for the lstat explanation! Of course I understand, that's a general problem, and there is probably no perfect solution. Maybe inotify or something, but that seems like a complex thing to do.)

Here's my experience: even when both panes are showing a directory with only a handful (e.g., 3) files, keeping the up (or down) key pressed constantly generates a CPU usage of about 15 percent. (This means about 20 keypresses per second. Same thing on GNU/Linux: about 1 percent CPU usage. Also, I noticed a flickering on OpenBSD, even when idling, so maybe it has to do something with ncurses.) However, I'm perfectly willing to believe this is simply because applications generally run slower on OpenBSD. (Perhaps ncurses is way less optimized than other systems.) If you think it's worth it, let me know what I can do to debug it.

Either way, thanks for making this run on OpenBSD in the first place!

**Comment by xaizek** [comment]
> key pressed constantly generates a CPU usage of about 15 percent

I'm using VirtualBox and SSH connection, it gives me 2-4 % CPU usage in this case (not sure how relevant VM is here). Actually profiling should provide more accurate results, I'll try that tomorrow.

> Also, I noticed a flickering on OpenBSD, even when idling, so maybe it has to do something with ncurses.

It seems to redraw whole screen too often, even when only a couple of lines could be refreshed (ktrace output seems to confirm this: full list of visible files repeats over and over again). Maybe it's their ncurses version, it looks like it differs from the upstream one.

**Comment by hofheinz** [comment]
Thanks for looking into this! (Don't know about VirtualBox; here it's an i5-based laptop, 4 cores with 2.5 GHz. I tried to eliminate CPU throttling with `sysctl hw.perfpolicy=high`. Still in a 50-file directory it's easy to push CPU usage to 30% by moving up and down. But this may have to do a lot with the OS.)

**Comment by xaizek** [comment]
That branch (somewhat reworked) is now part of `master`. What doesn't work is displaying of non-ascii symbols, but I used `C` locale, so maybe they will work on properly localized system (maybe I was fooled by ssh, which echoed them correctly for the shell, in which case vifm's behaviour is fine).

> Still in a 50-file directory it's easy to push CPU usage to 30% by moving up and down. But this may have to do a lot with the OS.

Nope, it's neither OpenBSD nor ncurses, that was my mistake when comparing structures. Using `memcmp()` is a bad idea due to possible padding and nothing was padded on other systems so I missed this (or there was exactly the same content in those bytes). Thanks for helping me find this! With default settings this mistake caused complete directory reload and most (effectively all) of TUI redraw every 150 ms, which affected CPU usage that much, it should be way better now.

**Comment by hofheinz** [comment]
The current version works like a charm. Great work! I tested locale-related things (filenames with wide characters, viewing text in files with wide characters) and keybindings (binding things like `<esc>[1;5A`, i.e., `<ctrl>-<up>`), all works perfectly with a `de_DE.UTF-8` locale. CPU load has gone down dramatically (it's hard to push above 1% now), and there is no noticeable flicker anymore (except sometimes very slightly while moving, but this is not OpenBSD-specific and does not disturb).

Thanks! (I'll keep on trying this out and will report if I find any problems.)

**Comment by hofheinz** [comment]
(I'll close the issue then, hope that's ok.)

**Comment by xaizek** [comment]
That sounds great, thanks for testing!

> except sometimes very slightly while moving, but this is not OpenBSD-specific and does not disturb

This might be due to absence of double buffering and is exactly the issue double buffering is meant to solve. I have xterm without double buffering (it can be enabled when building from source) and st with this feature, if I hold <kbd>Ctrl-L</kbd> in xterm, there is some flicker and none in st. The drawback of double buffering is that image preview doesn't work with it (images are lost on buffer switch&redraw).

**Comment by hofheinz** [comment]
Thanks for the explanation! Yes, that's it indeed. (st works fine for me, I was using xterm.)
