### ISSUE TITLE
viewcolumns align right not rendered properly

### ISSUE THREAD

**Issue by fogine** [vifm/vifm#98]
Hello,
When using following rule:

` set viewcolumns=-70%{name},10%{ext},10%{size},10%{mtime}`

Second "size" column should be aligned to right side, but it's cropped somehow... viz image
I think there's enough space for proper alignment...
(if "size" column alignment is set to left side, everything is rendered properly)

Am I missing something?

![vifm](https://cloud.githubusercontent.com/assets/7884288/8316493/18da4e36-1a00-11e5-864b-85554f458993.jpg)

**Comment by xaizek** [comment]
Hi,

Here contents of the last column is bigger than 10% of width of the view, so previous column is overwritten. I've removed this strange looking gap after the last column, so it might behave better in some cases, but still won't be in all of them. It's actually better to specify absolute width if you know it, e.g.
```
set viewcolumns=-{name},10{ext},7{size},16{mtime}
```
It's done this way so that layout remains fixed regardless of the content. It might be not what everyone would expect, but this prevents unexpected resizing when content changes or infinite layout adjustments, which are worked around in different ways in graphic frameworks (using maximum recursion level, refusing to adjust same size twice in a row, or sometimes just crashing like WPF does). So the layout is static and requires more precise manual adjustments.

If you do
```
set viewcolumns=-70%{name},10%{ext},10%{size},10%{mtime}..
```

you'll see the last column get truncated, by default it doesn't happen (it might be worth letting some fields overwrite part of other fields in cases when previous field is almost never full).

**Comment by fogine** [comment]
Thank you @xaizek  for the fix, it's better now. I ended up with absolute width as you pointed out, it's better for most of the cases.
