### ISSUE TITLE
What is the meaning of <cr>l, and <cr>gv?

### ISSUE THREAD

**Issue by sazam0** [vifm/vifm#988]
I have searched on the man page and in the wiki. I have not found the meaning of <cr>l and <cr>gv.

Also, when to use them?

Thank you.

**Comment by xaizek** [comment]
<kbd>l</kbd> and <kbd>Right</kbd> are  the same as <kbd>Enter</kbd> in most cases (https://vifm.info/vimdoc.shtml#vifm-l).  If you use Vim-like controls, that's what you'll use instead of <kbd>Enter</kbd>.

<kbd>gv</kbd> restores last visual mode state (https://vifm.info/vimdoc.shtml#vifm-gv).  Could be handy if had to leave visual mode for some reason, did that accidentally or want to repeat some action on the same files.

**Comment by sazam0** [comment]
Thank you.
