### ISSUE TITLE
Sixel preview is very slow

### ISSUE THREAD

**Issue by petersanchez** [vifm/vifm#999]
Hi all. I updated my `st` to 0.9.2 with the sixel patch (using [st-flexipatch](https://github.com/bakkeby/st-flexipatch)) and updated vifm config using the methods in #419 and preview works and the images look nice. However it takes like 1-2 seconds to generate and display the preview. The images are not terribly large either, most are smaller than 3mb (maybe some are around 5mb)

Any ideas on how to make this faster? With Uberzug it was pretty much instant. Maybe the current behavior is expected?

Here's the vifm info:

```
pjs:thinkpad ~ $ vifm --version
Version: 0.13
Git info: built out of repository

Support of extended keys is on
Parsing of .desktop files is enabled
Without GTK+ library
With magic library
Without X11 library
Without dynamic loading of X11 library
With file program
With -n option for cp and mv
With remote command execution
```

Alpine Linux, 3.20

Thanks in advance!

**Comment by xaizek** [comment]
Hello.

I'd recommend to keep using Ueberzug.  Don't know if you've seen [ueberzugpp](https://github.com/jstkdng/ueberzugpp), but there is [this plugin](https://github.com/vifm/vifm/tree/master/data/plugins/ueberzug) (see [how to install](https://wiki.vifm.info/index.php/Using_Lua_plugins#Installation) and comments in `init.lua`).  It should be useable with https://github.com/thimc/vifmimg as well if that's what you had before.

If you want to use Sixel, need to identify what takes that time.  Use `time your-sixel-converter you-image > /dev/null` to see how much it takes to produce the image, then try `time your-sixel-converter you-image` which might take longer because now output should go to the terminal which needs to process it.  You can also try another terminal and see how it works there for comparison.  Depending on the results and what tools and commands you use, there might be a way to improve the situation, or not.

**Comment by petersanchez** [comment]
OK I went with ueberzugpp and it has much better performance. Thanks!
